### ISSUE TITLE
How to write a Tango attribute with a Taurus Command Button 

### ISSUE THREAD

**Issue by TNoga0** [taurus-org/taurus#1000]
Hello,

as in the topic, I would like to create a Taurus Command Button with the ability to write a Tango Attribute, is there an easy way to do it?

**Comment by cpascual** [comment]
`TaurusCommandButton` is specifically for commands. So, it could only be used like that if your device provides a command that writes to the attribute.

But if what you want is to create a button widget that writes a given value to an attribute when clicked, you can do it.

Basically you need to inherit from the Qt button and from TaurusBaseComponent then implement a slot where you do `self.getModelObj.write(value)` and connect your clicked method to that slot.

If you need more help I could try to write an example snippet for you

**Comment by cpascual** [comment]
PS: congratulations: you wrote the issue #1000 ! 
;-)

**Comment by cpascual** [comment]
Here is a snippet that does it using a `TaurusBaseWritableWidget` instead of `TaurusBaseComponent`, which provides some extra features such as a tooltip:

```python
from taurus.qt.qtgui.application import TaurusApplication
from taurus.qt.qtgui.base import TaurusBaseWritableWidget
from taurus.external.qt import Qt


class AttrWriteButton(Qt.QPushButton, TaurusBaseWritableWidget):
    """A Taurus button that writes to an attribute"""
    def __init__(self, *args, **kwargs):
        super(AttrWriteButton, self).__init__(*args, **kwargs)
        self._value = None
        self.clicked.connect(self.onClicked)

    def getValue(self):
        return self._value

    def setValue(self, value):
        self.setText("click to write value={}".format(value))
        self._value = value

    def onClicked(self):
        self.writeValue()
        print("written", self._value)


if __name__ == '__main__':
    import sys
    app = TaurusApplication(cmd_line_parser=None)

    class _Demo(Qt.QWidget):
        def __init__(self):
            super(_Demo, self).__init__()
            self.sb = Qt.QSpinBox()
            self.bt = AttrWriteButton()
            self.sb.valueChanged.connect(self.bt.setValue)
            lyt = Qt.QVBoxLayout()
            lyt.addWidget(self.sb)
            lyt.addWidget(self.bt)
            self.setLayout(lyt)
            self.sb.setValue(33)
            
    w = _Demo()
    model = 'sys/tg_test/1/short_scalar'
    w.bt.setModel(model)
    w.show()
    sys.exit(app.exec_())
```

**Comment by TNoga0** [comment]
Thanks @cpascual,
unfortunately it didn't work with **super**, but after changing it to "old style" init the button began to write attribute values. Sadly, another problem appeared - I can't change the button colour using PyQt's SetStyleSheet, if you happen to know what might cause this error, I would be grateful for any info.

**Comment by cpascual** [comment]
>  it didn't work with super

that's odd... it worked for me. Maybe it has to do with the python version (in my case 3.7) or with the Taurus version (make sure to try at least with 4.6)

> I can't change the button colour using PyQt's SetStyleSheet

Not sure... I first thought that `TaurusBaseWritableWidget`, might be updating the stylesheet on events via the `TaurusBaseWidget.updateStyle()` or `.updatePendingOpsStyle()` mechanism, but looking at the code, it does not seem to be the case.

Please make sure that you are setting the style properly (i.e., make sure you manage to change the style of a pure Qt `QPushButton`, and then with a dummy class derived from `QPushButton`) (the Qt's style sheet API is somewhat tricky, IMHO)

**Comment by TNoga0** [comment]
Taurus updating mechanisms didn't seem to work, but Qt's palette setting does the trick:

``     palette = self.palette()``
       `` palette.setColor(self.backgroundRole(), self.btn_colour)``
       `` self.setPalette(palette)``

Thank you for your help!
