### ISSUE TITLE
Dynamically add and remove panels in TaurusGui

### ISSUE THREAD

**Issue by stanislaw55** [taurus-org/taurus#1001]
Hello Taurus community.

I have a question regarding TaurusGui. I would like to add slot which will remove/hide or create/show panels based on value passed to it. However, after little bit of trying with `TaurusGui.removePanel` and TaurusGui.createPanel` I was unable to do so: panel was present even if I performed `remvoePanel` on it.

Am I on right path? Is it possible at all? Maybe there is better way to do it?

**Comment by cpascual** [comment]
If you want to hide/show, then just calling to `panel.setVisible(bool)` should work (haven't tried)

If you want to remove the panel (as in *"completely removing it and not having it the next time I launch the GUI"*), then `TaurusGui.removePanel()` should do it **but** keep in mind that if the panel has been stored in other perspectives and you load one of them, then it would be recreated, so you may need to ensure that the panel is removed from all perspectives.
Also, if you call `removePanel()` programmatically, make sure that the name of the panel is matched... just to be sure, you can try first to remove using the "remove panel" option in the panels menu.

For debugging, using `taurus config` (aka `taurusconfigbrowser` in taurus v<4.6) may be a good idea.

If it does not work, please post a simple snippet that we can try

**Comment by stanislaw55** [comment]
Thank you for response.
Actually I completely forgot about perspectives! 
Also `setVisible` is quite obvious, haven't tried that yet
