### ISSUE TITLE
Taurus4 Python3 debian9: encoding issue when executing a 'taurus gui'

### ISSUE THREAD

**Issue by mrosanes** [taurus-org/taurus#1014]
Taurus4 Python3 debian9
encoding issue when executing a 'taurus gui'
Tested with migration of ctbl09 taurus gui in BL09-Mistral from ALBA Synchrotron. 

```
taurus gui tgconf_bl09
MainThread     WARNING  2019-10-02 13:19:00,977 TaurusRootLogger: <frozen importlib._bootstrap>:222: DeprecationWarning: taurus.external.qt.Qwt5 is deprecated since 4.5

MainThread     INFO     2019-10-02 13:19:01,088 TaurusRootLogger: Starting execution of TaurusGui
X11 connection rejected because of wrong authentication.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/taurus/external/qt/__init__.py", line 197, in taurusMsgHandler
    return f("Qt: " + msg)
TypeError: Can't convert 'bytes' object to str implicitly

```

**Comment by cpascual** [comment]
Hi can you please run the same in a shell where you previously export `QT_API=pyqt5`?

**Comment by mrosanes** [comment]
I saw this issue once today and some times yesterday, but it seemed to go away when using a relative import with the dot '.foo' 
However now I cannot reproduce the issue anymore. Anyway, for now, I would not close the issue. It could reappear.

**Comment by cpascual** [comment]
If it is spurious, it may also be related with incompatible settings file (e.g. a settings file created with different python, taurus and/or qt version from the one used for loading)

**Comment by mrosanes** [comment]
I cannot reproduce it anymore, I think that as @cpascual said, it was a problem of the settings file
