### ISSUE TITLE
[question] Deprecated setUseParentModel

### ISSUE THREAD

**Issue by vallsv** [taurus-org/taurus#1026]
Hi,

It looks like i was using a lot `setUseParentModel` (i also created Taurus widget on my side implementing this function). But I saw that it is now deprecated.

How does it work now? The error message is not obvious. If i could have some input to know what to do with, it could be very useful.

I think i use to create a widget with an address to a Tango device, and containing sub widgets which was reaching specific attributes (using only the suffix of the address).

How can i do it now?

Thanks a lot.

**Comment by reszelaz** [comment]
Does this example help you: https://github.com/taurus-org/taurus/issues/734#issuecomment-381114203 ?

**Comment by vallsv** [comment]
Thanks. Yes and no cause it looks like there is not at all the concept of parenting anymore.

I mean from a UI file i can't define anymore composition that i can copy paste.

I was not a big fan of `setParentModel`, But i think the relative parent/attribute path makes sense.

Without an extra `setParentModel` property i could be easy to specify an attribute from the parent, with this kind of paths for example `${parent}/attribute`. Anyway that's another question.

THanks for the feedback. From by base cause, anyway i have to use it. Then it's fine it is not yet removed.
