### ISSUE TITLE
Dynamically add widgets

### ISSUE THREAD

**Issue by felocru** [taurus-org/taurus#1045]
Hi, I hope someone can guide me.
I am adding attributes dynamically with PyTango's `add_attributes` method.
I would like to know what is the best approach to visualize these attributes in Tauros.
I am currently thinking of executing the command that adds the attributes before initializing the taurus application.
I thought that through the `TaurusCommandButton` button to execute the command, but doing so will not make the new attributes displayed in the GUI.
I have found the `TaurusBaseModel.refresh` and` TangoDevInfo.refreshAttributes` methods but I don't know if these will help me refresh the GUI to visualize the new attributes.
Thanks for your help.

**Comment by cmft** [comment]
Hi @felocru ,
Which kind of taurus widget are you using?  
Some ideas:
- The `taurus device` widget should show you (all cmd and attrs of this DS), this widget allows to filter the showed attr and commands, this will work at least before executing the command.
- Using a GUI with taurus form and taurus command button, you can customize the second (creating a custom command button inherited from `TaurusCommandButton`). In your widget, you can add new models in the form (for the added attrs) every time that you define an attr. (via this button) This solution will show you all attributes (in the form) in runtime.
- Other options is to manage any kind of listener to the existing attributes in the DS and update a form (but it depends on the DS)

Hope this help you

**Comment by reszelaz** [comment]
Just an idea on how to improve the `taurus device` widget or a `TaurusDevice` core object...
If I'm not mistaken in Tango 9 there is an event mechanism for this kind of interface changes. I have never tried it but I think that this [example](https://github.com/tango-controls/pytango/blob/develop/examples/interfacechangeEvents/IfchangeClient.py) should be useful.
So, basically whenever the interface is changing the widget could automatically add/remove the corresponding attribute/commands sub-widgets.

**Comment by felocru** [comment]
Thank you very much for giving me some ideas. I had my doubts if this feature was available. But now I have it clearer. I will do some tests and add my comments. Regards.
