### ISSUE TITLE
TaurusForm: give more info when failing to handle a model

### ISSUE THREAD

**Issue by alvaro-phyiscs** [taurus-org/taurus#1046]
In taurus form add verbosity to get better error information instead of getting "Cannot handle model 'redis://localhost/0/float_scalar'. Using default widget." In this case I need to write the password to enter the correct database ("redis://:password@localhost/0/float_scalar"). It would be great to get more info of the exception

**Comment by cpascual** [comment]
#1049 should fix this.
@alvaro-phyiscs , can you please confirm it?
