### ISSUE TITLE
Numpy Array Data corruption in taurus cache

### ISSUE THREAD

**Issue by sf-migrator-bot** [taurus-org/taurus#107]
This is a worrying bug: 

In certain conditions (see below) reading a Tango SPECTRUM attribute with Taurus (which by default uses cache) returns an array full of garbage instead of the right values (actually it seems that the pointer to the numpy array buffer has been moved).

To reproduce, it is necessary that 
a) the device pushes events for that attribute
b) a listener is added to that attribute
c) the read is done soon after an event has been emitted

We observe it only in Suse11 machines with Tango8.Python2.6, Numpy 1.3.
It does not seem to affect

I created an automatic test to show it. It automatically takes care of registering a device, trying the reads and cleaning the DB when finishing. So you just need to copy the attached files into some dir and run "python test_arraycorruption.py":

This is an example of the output in an **affected** system:

``` 
sicilia@ct32suse11:/siciliarep/projects/ctgensoft/issues/sprint4/5525/test_arraycorruption> python -c 'import numpy,PyTango,taurus,sardana; print (numpy.__version__, PyTango.__version__, taurus.Release.version, sardana.Release.version)'
('1.3.0', '8.1.1', '3.2.0', '1.3.1')
sicilia@ct32suse11:/siciliarep/projects/ctgensoft/issues/sprint4/5525/test_arraycorruption> python test_arraycorruption.py
/homelocal/sicilia/lib/python/site-packages/PyTango/__init__.pyc
MainThread     INFO     2014-08-06 12:22:10,897 Starter: Starting server ArrayCorruptor/arraycorruptor...
MainThread     INFO     2014-08-06 12:22:11,903 Starter: Server ArrayCorruptor/arraycorruptor has been started
FMainThread     INFO     2014-08-06 12:22:15,086 Starter: Deleted device unittests/arraycorruptor/temp-1
MainThread     INFO     2014-08-06 12:22:15,086 Starter: Hard killing server ArrayCorruptor/arraycorruptor...
MainThread     INFO     2014-08-06 12:22:18,086 Starter: Server ArrayCorruptor/arraycorruptor has been stopped
MainThread     INFO     2014-08-06 12:22:18,098 Starter: Deleted Server ArrayCorruptor/arraycorruptor

======================================================================
FAIL: testArrayCorruption (__main__.ArrayCorruptionTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_arraycorruption.py", line 52, in testArrayCorruption
    self.assertTrue(all(v==self._firstRead), msg=msg)
AssertionError: False is not True : Corrupted (on try 5): array([ -4.22608972e-38,  -7.70346396e-44,   0.00000000e+00,
         0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
        -4.10454254e+77,  -9.00021178e-42]) != array([ 123.4,  123.4,  123.4,  123.4,  123.4,  123.4,  123.4,  123.4])

----------------------------------------------------------------------
Ran 1 test in 7.235s

FAILED (failures=1)
```

And this is an example of the same test on an system **not affected**:

```
sicilia@ct64suse121:/siciliarep/projects/ctgensoft/issues/sprint4/5525/test_arraycorruption> python test_arraycorruption.py
/homelocal/sicilia/lib/python/site-packages/PyTango/__init__.pyc
MainThread     INFO     2014-08-06 12:40:56,664 Starter: Starting server ArrayCorruptor/arraycorruptor...
MainThread     INFO     2014-08-06 12:40:57,677 Starter: Server ArrayCorruptor/arraycorruptor has been started
MainThread     INFO     2014-08-06 12:41:01,396 Starter: Deleted device unittests/arraycorruptor/temp-1
MainThread     INFO     2014-08-06 12:41:01,396 Starter: Hard killing server ArrayCorruptor/arraycorruptor...
MainThread     INFO     2014-08-06 12:41:04,407 Starter: Server ArrayCorruptor/arraycorruptor has been stopped
MainThread     INFO     2014-08-06 12:41:04,418 Starter: Deleted Server ArrayCorruptor/arraycorruptor
.
----------------------------------------------------------------------
Ran 1 test in 7.787s

OK
```

We tested with several combinations of machines /OS/library versions. Here is a table that summarizes the tests so far:

OS               |  numpy  | PyTango | Taurus | Affected?
-----------------|---------|---------|--------|----------
suse11.1, 64b    |  1.3    | 7.2.3   | 3.2    |   No
suse11.1, 32b    |  1.3    | 8.1.1   | 3.2    |   Yes
suse11.1, 64b    |  1.3    | 8.1.1   | 3.2    |   Yes
suse11.1, 64b    |  1.8.1  | 8.1.1   | 3.2    |   Yes
suse12.1, 32b    |  1.6.1  | 8.1.1   | 3.2    |   No
suse12.1, 64b    |  1.6.1  | 8.1.1   | 3.2    |   No
Debian 8, 64b    | 1.8.1   | 8.1.1   | 3.2    |   No

Note: The problem may take a varying number of reads to be triggered, and my test "only" reads 1000 times, so it sometimes passes without triggering even if the system is affected So just in case, to be sure, in case the test is passed re-run it 3-4 times to be sure.

Reported by: cpascual ( http://sf.net/u/cpascual )

**Comment by cpascual** [comment]
If this cannot be reproduced in current machines, I propose to close this issue as "wont-fix" (we at alba are in the process of getting rid of most of the suse11 machines, and have been living with this for many years already)

what do the other @taurus-org/integrators think?

**Comment by cpascual** [comment]
Note. This forresponds to [SF103 bug](https://sourceforge.net/p/tauruslib/tickets/103/). The unit test files for reproducing the issue can be found [here](https://sourceforge.net/p/tauruslib/tickets/103/attachment/ArrayCorruptor.py) and  [here](https://sourceforge.net/p/tauruslib/tickets/103/attachment/test_arraycorruption.py)

**Comment by teresanunez** [comment]
Carlos, I agree with you. If the bug is not affecting the current machines, don't worry any more about it and close the issue.

**Comment by cpascual** [comment]
I am closing as wontfix since we do not support the affected systems anymore
