### ISSUE TITLE
taurus as caQtDM replacement

### ISSUE THREAD

**Issue by dschick** [taurus-org/taurus#1074]
Hi,

I am currently running both EPICS and TANGO/Taurus/Sardana in one lab which is quite harmonic.

EPICS runs actually because of some historic reasons but I have most of my environmental and safty hardware implemented within EPICS, like vales, shutters, temperatures, pressures, etc.

One thing I like very much is the usage of caQtDM to build a graphical control panel of the lab.

However, as we are currently setting up a new lab, I am thinking of trying to get rid of EPICS completely, but I got somehow stuck with the caQtDM replacement.

I have something like this here in mind: http://caqtdm.github.io/snapshot8.png
How would you build something like that in Taurus?
I would start with a TaurusGUI but I havn't found out, how to combine the grphical representation of the lab with the according position of the indicators, etc.

Are there maybe any examples around?

**Comment by cpascual** [comment]
I would say that what you are looking for is provided by the taurus *synoptics* support

Here you have two options:

- You can use the [Tango Synoptics](https://tango-controls.readthedocs.io/en/latest/tools-and-extensions/built-in/jdraw/jdraw.html), for which Taurus provides the [TaurusJDrawSynopticsView](http://taurus-scada.org/devel/api/taurus/qt/qtgui/graphic/jdraw/_TaurusJDrawSynopticsView.html) widget. This is what we use at ALBA. The synoptic file in this case is a plain text file that can be generated with the jdraw tool (which is installed as part of the libtango-java tools). For a very basic example, you can run:
```console
wget https://github.com/taurus-org/taurus/raw/develop/lib/taurus/qt/qtgui/graphic/jdraw/test/res/SimpleScalarViewer.jdw
python3 -m taurus.qt.qtgui.graphic.jdraw.jdraw_view SimpleScalarViewer.jdw
```

- Alternatively, in MAXIV they implemented [SVG-synoptics](https://github.com/MaxIV-KitsControls/lib-maxiv-svgsynoptic) which uses SVG files for defining the synoptic and a javascript engine to render the graphics within a Qt widget integrated with Taurus. I've got no personal experience with it, but from the demos I've seen, it looks beautiful and provides interesting features such as layerable and zoomable schematics.

I hope this helps.

**Comment by cpascual** [comment]
no updates here, so I am closing this question assuming it is solved. If not, feel free to reopen
