### ISSUE TITLE
Memory leak in notifd (Tango7) when using a device panel in taurus4 with python2

### ISSUE THREAD

**Issue by jordiandreu** [taurus-org/taurus#1084]
There is a memory leak in notifd (Tango7) when using a device panel in taurus4 with python2, which does not occur in taurus4 with python3.

Adding this trace:
`print("***** full name: {}".format(self.getFullName()))`
to _taurus/core/tango/tangodevice.py:209_ we see the reported URI is not the same (the Tango DB host is _tbl0402_ aliased to _tbl04_).

python2 (mem leak here):

> full name: tango://tbl0402.cells.es:10000/bl04/eh/nhq

python3:

> full name: tango://tbl04.cells.es:10000/bl04/eh/nhq

**Comment by cpascual** [comment]
(just for context, this comes from an internal ALBA ticket: https://jira.cells.es/browse/CSGSW-4037 )

**Comment by cpascual** [comment]
This was due to using an outdated version of taurus for the py2 tests. It works on the latest version
