### ISSUE TITLE
Context menu does not appear in plot panel

### ISSUE THREAD

**Issue by LluisGi** [taurus-org/taurus#1107]
Right click menu doesn't appears when reload a GUI

**Comment by cpascual** [comment]
Confirmed with py3qt5:

- create an empty TaurusGui with `taurusgui newgui`
- launch the gui
- add a custom panel of type TaurusPlot . If you right-click on it, you get the contex menu.
- exit the gui (saving the custom panel as permanent)
- re-launch the gui
- if you right-click, the context menu does not appear now

**Comment by cpascual** [comment]
Note: this may be a problem in taurus_pyqtgraph, since it does not affect other types of panels (e.g. TaurusImageDialog)

**Comment by cpascual** [comment]
I managed to reproduce it with pure Qt and pyqtgraph (no taurus involved) :

```python
import sys
from PyQt5 import Qt
import pyqtgraph as pg

app = Qt.QApplication([])
mainWin = Qt.QMainWindow()
plot = pg.PlotWidget()

mainWin.setCentralWidget(plot)
s = plot.saveState()
plot.restoreState(s)  # <-- commenting this out , the context menu appears
mainWin.show()
sys.exit( app.exec_() )
```
