### ISSUE TITLE
Taurus GUI - no new panel feature

### ISSUE THREAD

**Issue by evaki1** [taurus-org/taurus#1164]
Hello,

I am new at using Taurus and and I am trying to use the Taurus GUI, but when I launch taurus newgui, no matter the configuration in the wizard, the gui created doesn't have all features available (I cannot add any panels). I have tried with leaving all pages from the wizard empty (including the monitor page as suggested in another post)

I am on Windows 10, Python 3.6.8, PyQt5, Taurus 4.7.0, Tango 9.3.3., PyTango 9.3.1
I installed everything with pip.
For the created GUI I first installed it and then run it using taurus gui NAME

I have attached a picture as well
![TaurusGUI](https://user-images.githubusercontent.com/72862683/100452305-87cb4880-30c1-11eb-9911-3d8423e8fcc2.png)

Thank you,
Eva

**Comment by cpascual** [comment]
Have you ["unlocked" the view](http://taurus-scada.org/users/ui/taurusgui.html?highlight=lock%20view#re-arranging-panels-moving-resizing-hiding)? 

You can access this option in the "View" menu --> "Lock View"

**Comment by cpascual** [comment]
> I am new at using Taurus

Welcome!
It can be confusing, specially at the beginning, and the docs are not always too good. Please do not hesitate to ask!

**Comment by evaki1** [comment]
That was it! Thank you! I did read that part, but didn't realize it was disabling the other features.
