### ISSUE TITLE
QLoggingWidget: can it show tango device server logs?

### ISSUE THREAD

**Issue by mariocaptain** [taurus-org/taurus#1174]
Hi all,

I am trying to build something similar to the logviewer java tool of tango, embedded in my taurus application.
As far as I have been reading and experimenting with taurus's logging functionalities, especially the QLoggingWidget, I see that the widget may be meant to show "local" log messages emitted within the taurus application only, and there is no mechanism to connect to tango to show device server's log messages.

So my next attempt would be to try PyTango so see if I can make it work.

Would anyone throw some insights into this?
Thanks!

**Comment by cpascual** [comment]
I have a vague notion that what you want already exists, but I cannot remember the details. 
Maybe @tiagocoutinho or @reszelaz remember something?

**Comment by cpascual** [comment]
Apart, I just had a look at the `QLoggingWidget` (I admit that I've never actively used it), and I saw that it has the ability to show remote logs served via a socket connection (see the `QRemoteLoggingTableModel`). I understand that this works for remote taurus applications, not arbitrary Tango servers, though

**Comment by reszelaz** [comment]
The only thing that I remember is what @cpascual already mentioned in https://github.com/taurus-org/taurus/issues/1174#issuecomment-779705271. I do not remember that taurus was ever handling Tango DS logs.

As a totally different approach you could evaluate using elastic stack to store and visualize logs. A couple of years ago I tried this project from MaxIV: https://github.com/MaxIV-KitsControls/dev-maxiv-logger. If not, you could store logs in a file and use a File Beat.

**Comment by mariocaptain** [comment]
Thanks all for the clarifications. Not a problem though, as I can always use the stand-alone logviewer tool of tango for the purpose.
Best,
Dave
