### ISSUE TITLE
Move buildmock funtions to the taurus.core.util

### ISSUE THREAD

**Issue by sf-migrator-bot** [taurus-org/taurus#161]
It would be interesting that taurus provide utility functions used  by taurus/doc/buildmock.py script. 

They could be included in the taurus.core.util module.

Reported by: reszelaz ( http://sf.net/u/zreszela )

**Comment by cpascual** [comment]
This may not make sense if we get rid of mocks as we suggest in #408

**Comment by cpascual** [comment]
the merge of #408 makes this obsolete
