### ISSUE TITLE
Taurustrend DataInspector data format

### ISSUE THREAD

**Issue by sf-migrator-bot** [taurus-org/taurus#181]
Hi,

We would need the DataInspector tool from taurustrend either:
- to use the data format of the Tango DB or 
- to have the possibility to configure it from taurustrend application

The problem appears when trying to plot the RF Frequency of the Accelerators, which have 9 significant numbers (499.654.125 Hz) and it is configured at Tango DB as %16.4f. When we plot it with taurustrend it is not possible for us to know the frequency value using data inspector because it only shows the first 5 most significant numbers (4.9965e08).

This feature is necessary for us, specially when we have to retrieve the frequency value after som machine failures.

Thanks in advance,
Marc

Reported by: marcalvarez ( http://sf.net/u/marcalvarez )

**Comment by cpascual** [comment]
I am looking into this to see if I can do something quick for Jul17...
