### ISSUE TITLE
Add link to TEP in docs

### ISSUE THREAD

**Issue by sf-migrator-bot** [taurus-org/taurus#183]
Currently the TEPs are in https://sourceforge.net/p/tauruslib/wiki/TEP/ , but it would be nice to have an indirection from the official docs so that the TEPs could be linked to even if they are moved to some other place (e.g. from the wiki to a git repo, or to the docs themselves, or outside of sf.net,...)

One possibility is to add a file taurus/doc/source/tep.rst which then has a link pointing to wherever the TEPs are really hosted. 

Important: note that the requirement is **not** just having a link from the docs to the wiki, but actually having some "TEP" page in the docs to which one can link and that page may eventually contain a link to the wiki.

Reported by: cpascual ( http://sf.net/u/cpascual )

**Comment by cpascual** [comment]
This was fixed by TEP16.
See:
https://www.taurus-scada.org/tep/?TEP16.md
