### ISSUE TITLE
RuntimeError('Please define environment variable $HOME',)

### ISSUE THREAD

**Issue by sf-migrator-bot** [taurus-org/taurus#288]
Hello here the code use to build taurus

override_dh_auto_build:
        dh_auto_build -- --no-doc --with-extra-widgets
        xvfb-run -a python setup.py build_doc

the xvfb-run is used to simulate a working X11 during the build.
This way the icones can be generated with the QPixmap.

I attach the .build log which shows the problem.

It seems that during the build process of the documentation taurus try to find the tangorc file.

It would be great if this could be avoid or at least taken into account during the build process.

Cheers

Frederic

Reported by: picca ( http://sf.net/u/piccaf )

**Comment by cpascual** [comment]
Hi @picca, just checking... is this still an issue? 
Or can we close it?

**Comment by cpascual** [comment]
I think this is no longer an issue
