### ISSUE TITLE
TaurusJDrawSynopticView fails to update values (Taurus4 regression)

### ISSUE THREAD

**Issue by NexeyaSGara** [taurus-org/taurus#360]
On Windows machine with Taurus 4.0.1

It seems if I don't click on the synoptic my objects aren't updated. It's a simple synoptic with just a background image and less than 10 basic forms.

**Comment by cpascual** [comment]
Could you please provide the synoptic file (you can upload it to https://gist.github.com/ ) and the steps for reproducing?

**Comment by NexeyaSGara** [comment]
It's reproducible with a simple file.

<script src="https://gist.github.com/NexeyaSGara/a5efa9b65b8845a3a7a8efa24df4876d.js"></script>

It seems if I don't select the item, it isn't refreshed

**Comment by cpascual** [comment]
I cannot see the synoptic file... only javascript gibberish...

**Comment by NexeyaSGara** [comment]
jdraw_test.jdw file content : 
`JDFile v11 {
  Global {
  }
  JDRectangle {
    summit:33,74,324,183
    origin:179,129
    fillStyle:1
    name:"sys/tg_test/1/State"
  }
}`

Here for the gui part

`# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/Fflor.ui'
#
# Created: Thu Dec 01 14:23:35 2016
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
import taurus
from taurus.qt.qtgui.graphic.jdraw import TaurusJDrawSynopticsView

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Test(object):
    def setupUi(self, Test):
        Test.setObjectName(_fromUtf8("Test"))
        Test.resize(1153, 591)
        self.taurusJDrawSynopticsView = TaurusJDrawSynopticsView()
        self.taurusJDrawSynopticsView.setObjectName(_fromUtf8("taurusJDrawSynopticsView"))
        self.taurusJDrawSynopticsView.setModel(_translate("Test", "jdraw_test.jdw", None))
        self.verticalLayout = QtGui.QVBoxLayout(Test)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.verticalLayout.addWidget(self.taurusJDrawSynopticsView)

if __name__ == "__main__":
    import sys, os
    sys.path.insert(0, os.getcwd())
    taurus.changeDefaultPollingPeriod(500)
    try:
        shutil.rmtree("C:\\Users\\sgara\\.taurus\\")
    except:
        pass
    app = QtGui.QApplication(sys.argv)
    Test = QtGui.QWidget()
    ui = Ui_Test()
    ui.setupUi(Test)
    Test.show()
    sys.exit(app.exec_())`

And this for showing my problem
`# -*- coding: utf-8 -*-

import PyTango
import time

test = PyTango.DeviceProxy("sys/tg_test/1")
test.init()
time.sleep(1)
test.switchstates()
time.sleep(1)
test.init()
time.sleep(1)
test.switchstates()
time.sleep(1)
test.init()
time.sleep(1)
test.switchstates()
time.sleep(1)
test.init()
time.sleep(1)
test.switchstates()
time.sleep(1)`

Like I said in the previous message, the refresh seems to happend only when the item is selected with the contour

**Comment by cpascual** [comment]
I was able to reproduce the problem with taurus 4.0.3-alpha on linux and with a slightly simpler setup:

1- I used the following jdraw file (adapted from the one from @NexeyaSGara ):

```
~$ cat bug-360.jdw 
JDFile v11 {
  Global {
  }
  JDSwingObject {
    summit:33,74,324,183
    origin:179,129
    fillStyle:1
    name:"sys/tg_test/1/long_scalar"
  }
}

```

And , I simply ran it with jdraw_view:

```
python -m taurus.qt.qtgui.graphic.jdraw.jdraw_view jdwbug-360.jdw
```

Then I launched `taurusform sys/tg_test/1/long_scalar` and made sure to write 200 in the write value and apply so that the rvalue was automatically varied...

The jdrawview shows the number, but it is not refreshed unless a redraw is done (e.g., by switching the focus to another window and then back to the synoptic window).
Also, the following (maybe related) error is logged:

```
Traceback (most recent call last):
  File "/nfs/home/cpascual/src/taurus/lib/taurus/qt/qtgui/graphic/taurusgraphic.py", line 154, in run
    self.emitter.updateView.emit(v)
AttributeError: 'TaurusGraphicsUpdateThread' object has no attribute 'emitter'
```

Also, I checked and this is a regression (with taurus 3.7.2 and it does not happen)

**Comment by cpascual** [comment]
I confirm that the  exception was related to the problem. The PR #363 should fix this issue.

**Comment by NexeyaSGara** [comment]
I tried with the modification of PR#363 but I still get my exception with lextab.

For the Synoptic, it's clearly better but on my test with tg_test state, with 3 second between calling commands init and switchstates, it seems to me that some events aren't totally updated at this rate but I will try with my main synoptic and tell you how it goes.

**Comment by cpascual** [comment]
> I tried with the modification of PR#363 but I still get my exception with lextab.

Yes, but I think that is a separate issue (I opened #364 )

> For the Synoptic, it's clearly better but on my test with tg_test state, with 3 second between calling commands init and switchstates, it seems to me that some events aren't totally updated at this rate but I will try with my main synoptic and tell you how it goes.

Note that the synoptics use their own updating thread, which may cause a slight additional delay in refresh. see `TaurusGraphicsUpdateThread.period`
