### ISSUE TITLE
TaurusMainWindow's "Change Tango Host" action does "nothing"

### ISSUE THREAD

**Issue by cpascual** [taurus-org/taurus#379]
All `TaurusMainWindow `-based applications have a "Change Tango Host" Action by default (TaurusMainWindow menu-->Taurus-->Change Tango Host)

In its default implementation, it just stores the new tango host variable in a `tangoHost` property and does nothing else. Users may get confused by this (they may reasonably expect e.g. that all models in the whole GUI get updated to new values, like jive would do). 

But note forcing a change of all models is both technically difficult (think perspectives) and probably not desired in many situations.

IMHO, the only safe thing to add  to the *default* behaviour of this action is to emit a `tangoHostChanged` signal. Then, **for the particular case of TaurusGui aplications**, the MainWindow could be registered by default as a writer and reader of a shared data called "TangoHost". In this way, it would be up to the person adding a panel to register it as a reader/writer and act on changes of "TangoHost" as they see fit.

But note that even if implementing the above changes, the action would still "do nothing" in general, so IMHO it would make sense to either disable, or even hide it *by default* (i.e. so that it does not appear in menus). This would make special sense to me considering that the default options and actions should gradually be made less "Tango-centric".

**Comment by reszelaz** [comment]
I agree to not show this action by default. The action of changing the TangoHost have sense to just a subset of widgets e.g. Tango DB browser or the MacroServer/Door chooser in the macro execution widgets applications and of course it is clearly Tango centric.

It should be a programmer's choice to use it or not and in one way or the other. It could be either used locally on a widget level so, for example, two Tango DB browsers could be used in the same application pointing to different databases. Or one common database could be used for all widgets in the same application.

**Comment by cmft** [comment]
Since it is pure "Tango-centric" concept and nowadays does not do nothing, I will be more radica, and l would remove this functionality (following the deprecation cycle). If any Tango GUI would like to use it, a new subclass of TaurusMainWindow (TangoTaurusMainWindow) can be created adding Tango specialization.

**Comment by cpascual** [comment]
#557 will do the deprecation (in the Jan18 release), so I am assigning this issue to the Jul18 milestone (for which the action should be finally removed)
