### ISSUE TITLE
mixed linux and dos newline characters in taurus sources

### ISSUE THREAD

**Issue by jkotan** [taurus-org/taurus#391]
Hi, 

I've just noticed that in some files there are \newline characters are from dos 
while in the most cases \newline characters are from linux., e.g.
in support-3.x branch:

    lib/taurus/qt/qtdesigner/containerplugin.py
    lib/taurus/qt/qtgui/util/taurusropepatch.py
    lib/taurus/web/examples/tornado/demo4.html
    lib/taurus/web/static/js/taurus.js
    taurus.svg

It can be easily fixed by use of the dos2unix command.

I think it would be better to use only one type of the \newline characters.
Messing up dos and linux endline characters causes  problems in some tools to
building packages. 

Best regards,
Jan

**Comment by cpascual** [comment]
Thanks for reporting. I agree with what you propose. Would you open a PR?

Related to this: did you use some automated tool for checking? 

I would like to check on the develop branch. I am thinking that maybe we could check that as a part of the Travis CI...

**Comment by bilderbuchi** [comment]
In my experience, consistency is best insured with a nice .gitattributes file. You can normalize the line endings in a repo using git, see e.g. [here](http://stackoverflow.com/a/15646791/599884).

**Comment by cpascual** [comment]
Thanks @bilderbuchi for the tip!

I created PR #399 for forzing autonormalization in the develop branch. But I was surprised that when applying the recipe mentioned in #399, no file was found needed correction in the develop branch. And even more strange, when I did the same in the support-3.x branch, no files were changed there:

```
$ git checkout support-3.x 
$ git checkout -b bug-391-3.x
Switched to a new branch 'bug-391-3.x'
$ echo "* text=auto" >.gitattributes
$ rm .git/index     # Remove the index to force Git to
$ git reset         # re-scan the working directory
$ git status        # Show files that will be normalized
On branch bug-391-3.x
Untracked files:
  (use "git add <file>..." to include in what will be committed)

        .gitattributes
    
nothing added to commit but untracked files present (use "git add" to track)
```

So I wonder if this may really fix this issue ...

**Comment by cpascual** [comment]
@jkotan can you check if PR #400 fixes your issue?

(try on a fresh clone)

**Comment by bilderbuchi** [comment]
I am sorry, I should have been more verbose. In my experience, the instructions from the first link don't work correctly (no clear idea why), in those cases I found that following Github's procedure given in the second link gives better results.
In this case, after committing the new gitattributes, doing a ` git rm --cached -r .", followed by `git reset --hard` yields for me
```
$ git status
On branch fix-400
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   lib/taurus/qt/qtgui/util/taurusropepatch.py
        modified:   lib/taurus/web/examples/tornado/demo4.html
        modified:   lib/taurus/web/static/js/taurus.js
        modified:   taurus.svg

no changes added to commit (use "git add" and/or "git commit -a")
```
I don't know why containerplugin.py` does not get picked up, maybe it's been changed/corrected in the meantime?

**Comment by cpascual** [comment]
I do not understand what goes on... even when following "the github procedure" just as explained  in https://github.com/taurus-org/taurus/issues/391#issuecomment-280320936, I do not get any files modified...
 
Can someone please check PR #400 and tell me if you still get windows EOL there?

**Comment by teresanunez** [comment]
@cpascual, do you mean checkout your branch bug-391-3.x and check it there?.
I did that and there are still windows EOL there.

**Comment by teresanunez** [comment]
@cpascual the file containerplugin.py is the one that I see with windows EOL, as it was mentioned above ... it seems that it is not corrected.

**Comment by bilderbuchi** [comment]
@cpascual I don't know what's going on on your end, I just replayed the same procedure on a linux VM, and it worked, so it can't be my Windows. I think I can send a PR in the evening/this week.

**Comment by cpascual** [comment]
Thanks @teresanunez  and @bilderbuchi  for looking at it.

>  I think I can send a PR in the evening/this week.

that would be awesome, thanks!

**Comment by bilderbuchi** [comment]
alright, see #404.

**Comment by bilderbuchi** [comment]
Ah, nevermind, see #405 for a PR against `develop`.

**Comment by cpascual** [comment]
Thanks a lot for both PRs! I 'll review them ASAP.
Just FYI, support-3.x is not intended to be merged back. It is a "support branch" as defined in the [gitflow FAQ](https://github.com/nvie/gitflow/wiki/FAQ)

**Comment by bilderbuchi** [comment]
Ah thank you for clearing that up. From the name I thought it was your approach to support 3.x and 4.x at the same time, i.e. the branch where backported bugfixes (but not features) land.
