### ISSUE TITLE
qtpy exception (setResizeMode is only available in Qt4)

### ISSUE THREAD

**Issue by sergirubio** [taurus-org/taurus#401]
It seems that a deprecated Qt4 method is called:

  File "/home/sicilia/src/taurus/lib/taurus/qt/qtgui/table/taurusdevicepropertytable.py", line 186, in updateStyle
    QtGui.QHeaderView.ResizeToContents)  # .Stretch)
  File "/usr/lib/python2.7/dist-packages/qtpy/_patch/qheaderview.py", line 83, in setResizeMode
    raise Exception('setResizeMode is only available in Qt4. Use '
  Exception: setResizeMode is only available in Qt4. Use setSectionResizeMode instead.

**Comment by sergirubio** [comment]
Same error on TaurusValuesTable

Traceback (most recent call last):
  File "/home/sicilia/src/taurus/lib/taurus/qt/qtgui/base/taurusbase.py", line 319, in filterEvent
    self.handleEvent(*evt)
  File "/home/sicilia/src/taurus/lib/taurus/qt/qtgui/table/taurusvaluestable.py", line 726, in handleEvent
    hh.setResizeMode(Qt.QHeaderView.Fixed)
  File "/usr/lib/python2.7/dist-packages/qtpy/_patch/qheaderview.py", line 83, in setResizeMode
    raise Exception('setResizeMode is only available in Qt4. Use '
Exception: setResizeMode is only available in Qt4. Use setSectionResizeMode instead.

**Comment by cpascual** [comment]
This is strange...
I was not aware that we are (yet) be using qtpy in Taurus (maybe I forgot?).

Taurus should be only using PyQt4 for now... I wonder if there is something unusual in your installation?

That said, it is interesting to note these kind of warnings since we are eventually going to have to deal with them.

**Comment by cpascual** [comment]
Note:" the same exception can be triggered by e.g.,
```
taurusform sys/tg_test/1/boolean_spectrum
```

**Comment by cpascual** [comment]
Can anybody help in reproducing the problem (of loading qtpy) with an small snippet?

**Comment by cpascual** [comment]
Here is a smaller snippet for reproducing the exception.
(it seems that importing the taurus.qt.qtgui.editor module triggers the issue)

```python
from taurus.external.qt import Qt
from taurus.qt.qtgui.application import TaurusApplication
app = TaurusApplication()

# Commenting this import makes the exception disappear
from taurus.qt.qtgui.editor import TaurusBaseEditor

Qt.QHeaderView(Qt.Qt.Vertical).setResizeMode(Qt.QHeaderView.Fixed)
```

**Comment by cpascual** [comment]
It looks like this is a bug introduced by qtpy.
qtpy has side effects even when you do not import it directly: 
https://github.com/spyder-ide/qtpy/pull/65#issuecomment-252472704

**Comment by cpascual** [comment]
Here is a way of showing the side effects of importing qtpy:

If the qtpy import is removed, the program reaches the `print 3` line, but if the import is done, an exception prevents reaching that line.
Note that that occurs even if qtpy is not used at all in this snipped (in a real situation, it may happen when a module that imports qtpy is imported)

```python
import sip
sip.setapi('QString', 2)
sip.setapi('QVariant', 2)
sip.setapi('QDate', 2)
sip.setapi('QDateTime', 2)
sip.setapi('QTextStream', 2)
sip.setapi('QTime', 2)
sip.setapi('QUrl', 2)

from PyQt4 import QtGui, QtCore
app = QtGui.QApplication([])

w = QtGui.QHeaderView(QtCore.Qt.Vertical)
w.setResizeMode(w.Fixed)
print 1, w.setResizeMode

# Importing qtpy.Qwidgets (even if indirectly and never using it) changes w!!!
import qtpy.QtWidgets

print 2, w.setResizeMode
w.setResizeMode(w.Fixed)
print 3
```

**Comment by cpascual** [comment]
As a workaround in the meanwhile we could do the ugly thing of trying `setSectionResizeMode` before defaulting to `setResizeMode` (note that we have to try both because we cannot predict whether the user has already imported qtpy or not when we want to do the resize).

Or, alternatively, we could do an early import of qtpy in taurus.qt to make sure that the intrusive patching is done (note that this is just pushing the same problem towards taurus users, whose code could be broken)

**Comment by cpascual** [comment]
I finally opted for the "early import" workaround. See #473
