### ISSUE TITLE
pip does not install dependencies 

### ISSUE THREAD

**Issue by cpascual** [taurus-org/taurus#407]
Reported on Windows 10. See https://github.com/taurus-org/taurus/pull/397#issuecomment-281933818

**Comment by bilderbuchi** [comment]
How this happens is puzzling. 
Even your own CI [succeeds](https://ci.appveyor.com/project/taurusorg/taurus/build/1.0.109/job/fafffhq0n7hbtoid#L7895)
```
Collecting taurus
Installing collected packages: taurus
Successfully installed taurus-4.0.4a0
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
appdirs (1.4.1)
lxml (3.7.0)
numpy (1.12.0+mkl)
packaging (16.8)
pip (9.0.1)
pyparsing (2.1.10)
PyQt4 (4.11.4)
setuptools (34.2.0)
six (1.10.0)
taurus (4.0.4a0)
wheel (0.29.0)
```
despite your setup.py [demanding](https://github.com/taurus-org/taurus/blob/3fb0bfe9a8388e1c850a96bde31a3676de90198c/setup.py#L59-L66)
```
requires = [
    'numpy (>=1.1)',
    'PyTango (>=7.1)',  # [Taurus-Tango]
    'PyQt4 (>=4.8)',  # [Taurus-Qt]
    'PyQt4.Qwt5 (>=5.2.0)',  # [Taurus-Qt-Plot]
    'ply (>=2.3)',  # [Taurus-Qt-Synoptic]
    'lxml (>=2.1)',  # [Taurus-TaurusGUI]
    'spyder (>=2.2)',  # [Taurus-Editor] --> or maybe move it to sardana
    'guiqwt (==2.3.1)',
]
```
, so missing are PyTango, PyQt4.Qwt5, ply, spyder, guiqwt.

Btw, maybe pip's `--only-binary` option could help in your win-test.bat to point at the silx wheelhouse and make sure numpy et al are installed from there (as opposed to downloading/installing them separately).
