### ISSUE TITLE
[doc] Get rid of mocks for docs

### ISSUE THREAD

**Issue by cpascual** [taurus-org/taurus#408]
The docs generation requires importing all modules of taurus for introspection.

This forced us to generate mocks for the various taurus dependencies... but this is an ugly hack which is not easy to maintain (see, e.g. #267).

I see two different options:

a) Move the document creation to Travis.

b) Make use of the now-available [conda support in RTD](http://docs.readthedocs.io/en/latest/conda.html) to install the dependencies using Conda 

I prefer a) because I think that it is easier to maintain in the longer term (we maintain the docker images for the CI anyway), but this needs a bit more initial work since we need to configure the artifact deployment in travis to upload the docs somewhere else.

On the other hand, b) may be less disruptive and quicker to implement on the short term. But I personally have no experience with Conda... so any help would be welcome (@bilderbuchi?  , @pgap ?)

**Comment by bilderbuchi** [comment]
If you have to mock purely because to make the import taurus pass so that sphinx can grab the docstrings, couldn't you get away with a MagicMock(), and a trick like [this](http://stackoverflow.com/a/8658332/599884) to actually mock away the imports of your dependencies? I.e. something like (untested)
```
import sys
sys.modules['pytango'] = MagicMock()  # and the others
import taurus
```
Regarding b) are all the dependencies of taurus and its dependencies (looking at pytango and Tango, here) available on conda? I have just tried to install Taurus on Windows on an Anaconda environment, and it didn't work out, I needed at least Tango and the VC++ Compiler for Python 2 from the general internet, probably boost, too, in the end.

regardig a) uploading from travis to RTD seems to be an open issue: rtfd/readthedocs#1083

**Comment by cpascual** [comment]
> couldn't you get away with a MagicMock()

Actually our mocks are using MagicMock, but the  needed implementation (in order to meet the documentation requirements) is a *lot* more complex than the simple examples. And, what is worse, for many modules, it requires special tweaks. If you are curious, have a look at the buildmock.py script in the doc/ dir

> are all the dependencies of taurus and its dependencies (looking at pytango and Tango, here) available on conda?

I think they are (but I've never used conda myself). I think that PyTango uses conda for CI (maybe @tiagocoutinho or @vxgmichel can confirm). Also, if I remember correctly, someone ( was it  @pgap? ) told me that pyepics was also conda-installable. 

> uploading from travis to RTD seems to be an open issue rtfd/readthedocs.org#1083

I was aware... actually the [last comment](https://github.com/rtfd/readthedocs.org/issues/1083#issuecomment-256403881) in the thread (from a few months ago) is mine ;)  . But note that we do not need to use RTD. We have our own domain which we can redirect somewhere else without affecting existing links, so we could explore any of:
- deploying to github pages
- deploying  to https://pythonhosted.org/ (in the past this was problematic due to space limits, but we could re-check)
- deploying to some other host (we could even rent one)
- ... or use some server at a participating institution (ALBA, DESY, ...), which would be easy, but we prefer to avoid it in order to keep the taurus infrastructure as decoupled as possible from the participating labs.

**Comment by vxgmichel** [comment]
I'm hosting the tango and pytango packages on my channel, though this might change in the future:

    conda install -c vxgmichel pytango
    conda install -c lightsource2 pyepics

**Comment by bilderbuchi** [comment]
> I'm hosting the tango and pytango packages on my channel, though this might change in the future:

Ah, good to know, unfortunately Linux only, so not so useful for me personally. :-/

**Comment by bilderbuchi** [comment]
> Actually our mocks are using MagicMock, but the needed implementation (in order to meet the documentation requirements) 

Ah, ok, didn't realize that the docs rely on details of the dependencies, I thought it was only to get around the failing imports.

**Comment by vxgmichel** [comment]
@bilderbuchi 
> Ah, good to know, unfortunately Linux only, so not so useful for me personally. :-/

If you're interested in tango packages for other platforms, you might want to push things in this direction: conda-forge/staged-recipes#1334. Let me know if you want more information.

**Comment by cpascual** [comment]
I am experimenting with gh-pages, and it seems pretty simple (just put the sphinx html output in a branch called gh-pages in the repo of the project)

I did a [first test on my personal fork](https://cpascual.github.io/taurus/) but  something got wrong with images and css... but probably it is my fault.

**Comment by cpascual** [comment]
As for automating the deplyment, we could get inspired by this: https://gist.github.com/domenic/ec8b0fc8ab45f39403dd

**Comment by cpascual** [comment]
Before putting more effort into the Travis+gh_pages solution for the docs, I tried the conda+readthedocs alternative, following @vxgmichel 's instructions:

> install conda

Done (I used `docker run -i -t continuumio/miniconda /bin/bash`)

> set up a build environment

I installed many of them:
```
conda install -c lightsource2 pyepics
conda install -c tango-controls pytango=9.2.1
conda install pyqt=4
conda install ply
conda install spyder
conda install -c praxes pymca=5.1.1
```
... but got stuck on installing PyQwt 5 and guiqwt with conda

Anyone has a suggestion? (IMHO unless **all** dependencies can be installed, there is not much point in using conda for the docs... and I don't feel like packaging PyQwt5 for conda myself... )

**Comment by cpascual** [comment]
The ideal solution would be if RTD supported custom docker images for their build environment, so [I requested it](https://github.com/rtfd/readthedocs.org/issues/2966).

**Comment by vxgmichel** [comment]
@cpascual You can use `pip` within your conda environment when packages are missing:

```
# Conda environment
conda create -n test pyqt=4 pillow numpy scipy cython python=2
source activate test
# Pip install
pip install pythonqwt guidata
pip install guiqwt
# Tests
conda install h5py spyder
python -c "from guiqwt import tests; tests.run()"
```

**Comment by cpascual** [comment]
> You can use pip within your conda environment when packages are missing:

Thanks for the hint  @vxgmichel !
Do you know if that will work within the environment.yml for readthedocs?

Also, any idea for  PyQwt5? (which requires Qwt 5)
I guess that **for the purpose of building the docs** I could try to mock PyQt.Qwt5 using PythonQwt ...  but still it would be ugly... (although we want to get rid of this dependency, so it may not be critical)

**Comment by bilderbuchi** [comment]
I know that you can prescribe pip-installed packages in an environment.yml. if that works on rtd no idea, but I don't see why not.

**Comment by LJBD** [comment]
@cpascual  - AFAIK there's no official PyQwt package for Linux (there's only one for Windows [here](https://anaconda.org/petebachant/PyQwt/files)). There are some packages for Qwt5, but I haven't been able to install any of those.

**Comment by cpascual** [comment]
@LJBD 
> There are some packages for Qwt5, but I haven't been able to install any of those.

yes, I also tried, with same lack of results

@bilderbuchi: 
> I know that you can prescribe pip-installed packages in an environment.yml. if that works on rtd no ideaI 

guess it is worth giving it a try...

Also, note that there [may be some hope of RTD allowing uploads of already-built docs](https://github.com/rtfd/readthedocs.org/issues/2966#issuecomment-310511079). That would be the perfect solution for us

**Comment by bilderbuchi** [comment]
Huh, that sounds more like a bug in guiqwt, to be honest (I.e. bad dependency situation)

**Comment by mrosanes** [comment]
Testing with gh-pages:

Dependency comment:
- sphinx_rtd_theme would be needed on cpascual/taurus-tests dockers used for CI, in order to build the documentation on them using Travis.
It can be installed with:
```apt-get install python-sphinx-rtd-theme```

**Comment by mrosanes** [comment]
Pull request https://github.com/taurus-org/taurus/pull/562 deals with gh-pages documentation building using the taurus-test dockers.

Done in .travis.yml:
- install sphinx-rtd-theme
- build documentation
- Add file .nojekyll in order allow usage of sphinx-rtd-theme
- Add local_dir: ./build/sphinx/html (directory that is automatically deployed to gh-pages branch)
- Add $GITHUB_TOKEN variable (Set in travis-ci.org dashboard, after creating the token in GitHub)

The build documentation when pushing to the branch develop of https://github.com/mrosanes/taurus, can be seen in:
https://mrosanes.github.io/taurus/

--

TODOs:
- Study if it is allowed in gh-pages to keep documentation for different branches
- Study if it is allowed to maintain documentation of different Taurus versions, as it is now done on RTD

**Comment by cpascual** [comment]
> TODOs:
>    Study if it is allowed in gh-pages to keep documentation for different branches

I do not think so, but if we can keep the artifact (even temporally) without deploying it would be even better

>    Study if it is allowed to maintain documentation of different Taurus versions, as it is now done on RTD

Not directly, but maybe it is possible making use of the fact that the github pages are themselves version-controlled (we can always deploy previous versions somewhere else)

**Comment by cpascual** [comment]
I think I managed to find a satisfactory solution based on travis and github pages. See #572

Note, #572 does *not* close this issue because the mocks are intentionally not removed to allow for further testing before moving from RTD to GH pages.

Once (or if) we decide to move, we should do the following changes (already proposed by @mrosanes as part of #562 ):
- https://github.com/taurus-org/taurus/pull/562/commits/f196978e352319fa0d6e342748a02c2581cbdab6
- https://github.com/taurus-org/taurus/pull/562/commits/1c6e3bfe4cd8a8b1a1de7c3f0faf0e35390ef014
- https://github.com/taurus-org/taurus/pull/562/commits/d11d4b785130e12569e3f7b1906b9ad04de11a25
- https://github.com/taurus-org/taurus/pull/562/commits/217aa549f18a354e8b5fa93421a91b3fb63d01ad

**Comment by cpascual** [comment]
Now that #572 is merged, we can compare the docs built with Travis:
https://taurus-org.github.io/taurus-doc/

with those built with RTD:
http://taurus.readthedocs.io/en/latest/

Apart from the fundamental difference that Travis does not require to maintain the mocks, I only see the following differences:

- Travis is not currently building pdf, epub or single-page html docs for download. But it should *not* be difficult to do it just as we do with the normal ones (although personally I would only worry about the pdf, if at all). 
- Travis is not currently linking to other versions of the docs. This can be solved by adding links to the other versions in the TOC of index.rst
- The inheritance diagrams are more complete in Travis (the inheritance for mocked classes is not show in the RTD docs). See the snapshot below: 

![image](https://user-images.githubusercontent.com/4115224/30484296-4631832a-9a2a-11e7-85f7-10fa05f73c2e.png)
