### ISSUE TITLE
TaurusValueLineEdit has wrong behaviour when is using sip API#1

### ISSUE THREAD

**Issue by cmft** [taurus-org/taurus#411]
TaurusValueLineEdit is not compatible with sip API#1 and it shows wrong behaviours. w_value line edit does not work and shows inappropriate colours. See the attached images.

![grey_wvalue](https://cloud.githubusercontent.com/assets/6168722/23307983/d859be50-faa9-11e6-801c-3230ad7e6520.png)
![orange_wvalue1](https://cloud.githubusercontent.com/assets/6168722/23307988/ddc22cf6-faa9-11e6-88f9-36de037ed41d.png)

The API#1 can be enabled if you import  some module from PyQt4 before any Taurus widget, and taurus did not advise you about the compatibility.

I know that the recommendation is to use the taurus.external modules but IMHO taurus should report a message if it can not switch to API#2

```
from PyQt4 import QtCore, QtGui
from taurus.external.qt import Qt
import sip
sip.getapi('QString')
Out[4]: 1
```

```
from taurus.external.qt import Qt
from PyQt4 import QtCore, QtGui
import sip
sip.getapi('QString')
Out[4]: 2
```

**Comment by cpascual** [comment]
Your analysis is correct.
Taurus>= 4 should not try to provide API#1 compatibility, but it should warn (or err) if API#2 cannot be set.
I think that the proper way to handle this is by explicitly setting the API when loading taurus.qt (AFAIK, this will report an exception if API#1 is already set)

**Comment by cpascual** [comment]
I created a PR (#472 ) that fixes this by forcing API2 (and if API1 is already set, an exception is raised)
