### ISSUE TITLE
qwheel as no attribute 'lostFocus'

### ISSUE THREAD

**Issue by pinam** [taurus-org/taurus#417]
Hi,
I upgraded my Taurus version from 3.6.0 to 4.0.4alpha. When I try to use a TaurusWheelEdit, have got the following error : 

  File "d:\taurus\lib\taurus\qt\qtgui\input\tauruswheel.py", line 44, in __init__
    self.call__init__wo_kw(QWheelEdit, qt_parent)
  File "d:\taurus\lib\taurus\core\util\object.py", line 60, in call__init__wo_kw
    klass.__init__(self, *args)
  File "d:\taurus\lib\taurus\qt\qtgui\input\qwheel.py", line 215, in __init__
    self._build()
  File "d:\taurus\lib\taurus\qt\qtgui\input\qwheel.py", line 319, in _build
    ed.lostFocus.connect(ed.hide)
AttributeError: '_NumericEditor' object has no attribute 'lostFocus'
__del__

I use Windows 7 and the versions of depencies are : 
>>> taurus.check_dependencies()
Checking required dependencies of taurus.core...
        Checking for Python >=2.6.0... [←[0;32mOK←[0m] (Found 2.7.10)
Checking OPTIONAL dependencies of taurus.core...
        Checking for PyTango >=7.1.0... [←[0;32mOK←[0m] (Found 8.1.6)
Checking required dependencies of taurus.qt...
        Checking for PyTango >=7.1.0... [←[0;32mOK←[0m] (Found 8.1.6)
        Checking for PyQt >=4.4.0... [←[0;32mOK←[0m] (Found 4.11.3)
        Checking for PyQwt >=5.2.0... [←[0;32mOK←[0m] (Found 5.2.3)
Checking OPTIONAL dependencies of taurus.qt...
        Checking for Qub >=1.0.0... [←[0;33mWARNING←[0m] (Not found])
        Checking for spyder >=3.0.0... [←[0;33mWARNING←[0m] (Not found])
        Checking for qtcontrols >=1.0.0... [←[0;33mWARNING←[0m] (Not found])

I tried with Taurus 4.0.1 and 4.0.3 and I have the same issue. But I tried taurus 4.0.1 on Linux and I don't have any problem.

Mickael

**Comment by cpascual** [comment]
Hi, thanks for the report. 
`lostFocus` is a [deprecated signal](http://www.qtcentre.org/threads/8785-QLineEdit-lostFocus-signal-problem?s=f2c6cc0ff023082a7d7c64fb02effcb9&p=46906#post46906). The PR #418 should fix this

**Comment by cpascual** [comment]
@pinam  could you please test with with the changes in #418 and confirm that it fixes your issue?

**Comment by pinam** [comment]
@cpascual Great! Thanks for this fix. I have just one question about git. I didn't manage to update my repo to this fix. I thought a git pull was sufficient, but not, because the develop branche is up to date. So copied manually the 3 lines and modified qwheel.py.
For the future corrections, could you tell me how to do?
Thanks

**Comment by cmft** [comment]
Hi @pinan, 
@cpascual fixed the bug in a branch of his taurus fork (cpascual:bug-417) and with this branch he created the pool request).  The imformation is showed at the top of the PR (under the title), for this case:

> cpascual wants to merge 1 commit into taurus-org:develop from cpascual:bug-417 

You can get the branch adding his fork as new remote repository in your local repository (`git remote add cpascual https://github.com/cpascual/taurus.git`),  and  then after `git remote update` you could checkout his branch `git checkout cpascual/bug-417`  .

**Comment by cpascual** [comment]
> You can get the branch adding his fork as new remote (...)

Or , if you do not want to have my remote there "forever", you can simply use:

```
git checkout -b cpascual-bug-417 develop
git pull https://github.com/cpascual/taurus.git bug-417
```

**Comment by cpascual** [comment]
@pinam : I understand that the fix works for you, right?

**Comment by pinam** [comment]
@cpascual : Yes it works. Thanks
