### ISSUE TITLE
TarurusTrend does no work with boolean_scalar

### ISSUE THREAD

**Issue by cmft** [taurus-org/taurus#421]
taurustrend can not plot the values cause the events are been dropped, due to its rvalue has not .magnitude (it is due to booleans not being quantities)

> TaurusTrendsSet.sys/tg_test/1/boolean_scalar: Droping event. Reason rvalue has no .magnitude

**Comment by cpascual** [comment]
Confirmed.

There is an easy workaround, though: use eval to cast the model to an integer, e.g., if you want to do a trend of `sys/tg_test/1/boolean_scalar`, do:

```
taurustrend 'eval:int({sys/tg_test/1/boolean_scalar})'
```
