### ISSUE TITLE
tauruslabel model name modificator #rvalue.units doesn't work anymore

### ISSUE THREAD

**Issue by sergirubio** [taurus-org/taurus#435]
Has it been deprecated?

**Comment by cmft** [comment]
I set units in the `sys/tg_test/1/float_scalar` tango attribute and it works to me:
`python -m taurus.qt.qtgui.display.tauruslabel "sys/tg_test/1/float_scalar#rvalue.units"`

**Comment by sergirubio** [comment]
Ok, your sample works.
