### ISSUE TITLE
TaurusPlot: unable to show custom tick labels

### ISSUE THREAD

**Issue by sergirubio** [taurus-org/taurus#438]
Problem seems caused by latest PyQt4; the following call fails to set custom tick labels on X axxis:

               plot.setAxisCustomLabels(Qwt5.QwtPlot.xBottom,
                                         zip(self._positions, self._labels), 60)

**Comment by cmft** [comment]
Hi @sergirubio ,
I could not reproduce the error. It works for me.

```
import sys
import taurus.qt.qtgui.application
from taurus.qt.qtgui.plot import TaurusPlot

from taurus.external.qt import Qwt5

app = taurus.qt.qtgui.application.TaurusApplication()
w = TaurusPlot()
model = "eval:rand(2)"
w.setModel(model)

positions = [0, 1]
labels = ["a", "b"]

w.setAxisCustomLabels(Qwt5.QwtPlot.xBottom,
                         zip(positions, labels), 60)

w.show()
sys.exit(app.exec_())
```

**Comment by cmft** [comment]
Hi @sergirubio,
Did you test it?

**Comment by sergirubio** [comment]
Yes, with latest versions it now works again.
