### ISSUE TITLE
Are QThreads allowed in Taurus widgets?

### ISSUE THREAD

**Issue by jkotan** [taurus-org/taurus#439]
Hi,

Are there any problems with qthreads in Taurus?  

When I add to my taurus widget one simple qthead and run it together with TaurusForms (with heartbeets) and MacroGui after some time it freezes. Without those TaurusForms it works OK. 
I use to communicate with threads only variable  `with Qt.QMutexLocker(mutex)` access or signals with `Qt.Qt.DirectConnection`. Are there any restriction?

I use taurus 3.7.3 with Tango 9.

Cheers,
Jan

**Comment by cpascual** [comment]
No limitations that I am aware of... but also I do not know of any application doing heavy use of QThreads with Taurus (apart from some use of QTimer), so there may be something that we are not aware of

**Comment by jkotan** [comment]
Hi Carlos,

Thanks for your answer. 

PS: I have removed creation of DeviceProxy from my QThread.run() and GUI stop to freezes. I thought that creation of DeviceProxy  is thread safe but maybe not with respect to QThreads.

Cheers,
Jan
