### ISSUE TITLE
TaurusDeisgner won't launch on Windows

### ISSUE THREAD

**Issue by sf-migrator-bot** [taurus-org/taurus#44]
On a fresh windows platform with:
Tango 8.1.2b
PyTango 8.1.1
PythonXY 2.7.5.2
lxml 3.3.1
Taurus 3.2.0

On a command Dos window, I have some DEBUG information, but nothing really important.

If I launch a TaurForm or TaurusDevicePanel, there is no problem.

Reported by: NexeyaSGara ( http://sf.net/u/nexeya )

**Comment by cpascual** [comment]
With Taurus4 and Win7 cannot be reproduced. Closing
