### ISSUE TITLE
Taurus device proxy is not created for remote host 

### ISSUE THREAD

**Issue by tcsgmrt** [taurus-org/taurus#455]
Dear All,

I am getting following error while generating taurus device or attribute proxy **( Taurus Version : 4.0.4-alpha)**  

```python
>>> import taurus
>>> attr_proxy = taurus.Attribute('01hw255506:10000/Machine01/lmcmode')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/tangoworkspace/CentralNode/GUI/cmcGuiLib/cmcGUI/taurus/core/taurushelper.py", line 541, in Attribute
    return Factory(scheme=getSchemeFromName(dev_or_attr_name)).getAttribute(dev_or_attr_name)
  File "/opt/tangoworkspace/CentralNode/GUI/cmcGuiLib/cmcGUI/taurus/core/taurushelper.py", line 487, in Factory
    raise TaurusException('Cannot create Factory for %s' % scheme)
taurus.core.taurusexception.TaurusException: Cannot create Factory for '01hw255506'
```
Here **01hw255506** is hostname for remote machine and that is mapped in **/etc/hosts** files.

Can you assist me in above case because I am able to create Tango DeviceProxy and AttributeProxy for same as.

For Tango device it's working as expected for remote server but failed for taurus.

```python
  >>> proxy = PyTango.DeviceProxy("01hw255506:10000/Machine01")
  >>> proxy = PyTango.AttributeProxy("01hw255506:10000/Machine01/lmcmode")****
```

Note : for local server I am able to create taurus device proxy.

Thanks,
Hitesh patel
Tcs,Pune

**Comment by cpascual** [comment]
The model name that you are using is wrong.

If you specify the host (what in Taurus4 is called *authority*, you need to prepend it with '//'.

So, instead of `'01hw255506:10000/Machine01/lmcmode'`, try:

`'//01hw255506:10000/Machine01/lmcmode'` 

or, to be more explicit, 

 'tango://01hw255506:10000/Machine01/lmcmode'

**Comment by cpascual** [comment]
For more details about model names, see this:

 http://www.taurus-scada.org/en/latest/devel/core_tutorial.html
