### ISSUE TITLE
How to read Quality from TaurusLabel?

### ISSUE THREAD

**Issue by tcsgmrt** [taurus-org/taurus#459]
Dear All,

I have created tauruslabel for tango attribute as follow:
Tlabel = TaurusLabel()
Tlabel.model = 'tango://01hw341654:10000/Pune/Lab/Machine01/mncStatus'

I want to read quality of this **mncStatus** attribute so I have used **Tlabel.model.getShowQuality()** which return true every time.

I know that according to PyTango.AttrQuality value TaurusLabel change it's background color but I don't know how to get Attribute Quality using TaurusLabel.

I want quality value as return by  PyTango.AttrQuality.ATTR_VALID,PyTango.AttrQuality.ATTR_ALARM etc. In my code I want to compare TaurusLabel attribute quality with  PyTango.AttrQuality. to implement some logic.

Thanks,
Hitesh Patel

**Comment by cpascual** [comment]
I am not sure of understanding your requirement. The quality is not a property of a TaurusLabel, but of the model (the TaurusAttribute) represented by that TaurusLabel. Or, more strictly, of the value that you read from such model.

YTherefore, you can access the model and then interrogate it about the quality as follows:

```python
In [21]: w = TaurusLabel()

In [22]: w.model = 'sys/tg_test/1/short_scalar'

In [24]: attr = w.getModelObj()

In [25]: v = attr.read()

In [26]: v.quality
Out[26]: <AttrQuality.ATTR_ALARM: 2>
```

Is this what you need?

**Comment by cmft** [comment]
Hi @tcsgmrt ,
if you are using taurus v4, and you only are interesting to show  the attribute quality, you can get it using the fragment (**#quality**) in the model. 

For your example : 

`Tlabel.setModel('tango://01hw341654:10000/Pune/Lab/Machine01/mncStatus#quality'`

If you are interested to use the quality value in the Widget logic,
I see two options:

As @cpascual  said (for taurus 3 and 4) or for taurus 4 
```
quality = w.getModelFragmentObj("quality")
```

Hope this help you!

**Comment by tcsgmrt** [comment]
Dear Carlos,

Thanks for your help.

I have created TaurusLabel and use getModelObj method as follow. 
 w = TaurusLabel()
 w.model = 'sys/tg_test/1/short_scalar'
 attr = w.getModelObj()
DisplayAtproperty = attr.get_property('DisplayAt')

Here getModelObj provide the TangoAttribute proxy object for **short_scalar** attribute of **sys/tg_test/1** .
My Issue is when I use get_property('DisplayAt') on TangoAttribute it throw error as below

Error Log :
**Traceback (most recent call last):
  File "R1.py", line 85, in <module>
    R1obj = R1(mainwindow,None)
  File "R1.py", line 50, in __init__
    print "attr.DisplayAt attribute", attr.get_property('DisplayAt')
  File "/opt/tangoworkspace/CentralNode/GUI/cmcGuiLib/cmcGUI/taurus/core/tango/tangoattribute.py", line 77, in __getattr__
    return getattr(self._getRealConfig(), name)
  File "/opt/tangoworkspace/CentralNode/GUI/cmcGuiLib/cmcGUI/taurus/core/tango/tangoconfiguration.py", line 75, in __getattr__
    raise AttributeError
AttributeError**

Please let me know how can I use TangoAttribute Proxy method from  Attribute object which I extracted using getModelObj method on taurus label.

Thanks,
Hitesh Patel

**Comment by cpascual** [comment]
getModelObject gives you a TangoAttribute object. Please do not confuse this with the PyTango.AttributeProxy object (please carefully re-read my replies from #457 because I think they already address your issue).

Also: is the original problem that started this question solved? (if so, we can close this issue)

**Comment by tcsgmrt** [comment]
Dear Carlos,
Thanks for Help.

Yes, You can close this issue.


Thanks,
Hitesh Patel
