### ISSUE TITLE
Can't start taurusdesigner

### ISSUE THREAD

**Issue by rile993** [taurus-org/taurus#460]
When I want to start taurusdesigner I get following message:

`MainThread     INFO     2017-05-31 10:55:52,710 TaurusRootLogger: Using "PyQt4" for Qt`
`/usr/lib/x86_64-linux-gnu/qt4/bin/designer: symbol lookup error: /usr/lib/x86_64-linux-gnu/qt4/plugins/designer/libpyqt4.so: undefined symbol: Py_IsInitialized`

I tried with reinstalling Ubuntu and installing Taurus again, but I'm still getting the same message when I try to run taurusdesigner. Does anyone have any idea how to solve this?

**Comment by cmft** [comment]
Hi @rile993,
it seems Qt Designer problems.
Which ubuntu are you using?
How do you install taurus? and its dependencies?
Can you launch the  qt `designer`?

Best,
Carlos

**Comment by rile993** [comment]
I am using Ubuntu 16.04. I installed PyQt and SIP from source code. Other dependencies and taurus were installed from Ubuntu repositories or by using pip.

No, I can't launch Qt designer, even though I am able to run taurusform and taurusdemo.

What does this error mean, what library libpzqt4.so is used for?

**Comment by cpascual** [comment]
Hi @rile993 
As @cmft says, it seems to be a problem in the dependencies.
Unless there is some strong reason for installing PyQt ans SIP from source, I would advise to use the standard packages from the official repos.

**Comment by cpascual** [comment]
Hi @rile993, is the problem solved?

**Comment by cpascual** [comment]
no answer. Closing.
