### ISSUE TITLE
extra_guiqwt errors with guiqwt 3

### ISSUE THREAD

**Issue by cpascual** [taurus-org/taurus#464]
Older versions of guiqwt (<=2.3.1) relied on the PyQwt5 module. This changed in newer versions, where the pure-python [PythonQwt](https://pypi.python.org/pypi/PythonQwt) module is used instead.

Unfortunately, the PythonQwt implementation does not support some features that are used in taurus.qt.qtgui.extra_guiqwt <s>(notably, QwtScaleDiv and similar classes). </s> **UPDATE:** actually, the `QwtScale**` classes **are** supported. It just happens that they cannot be mixed. See [my comment below](https://github.com/taurus-org/taurus/issues/464#issuecomment-308698156)) 
This makes some features from extra_pyqwt to fail (e.g. the TaurusTrend2D  and TaurusTRend1D widget, or the TimeAxisTool). See, e.g.:

```
cpascual@pc218:~$ devenv taurustrend2d --demo
Running in Dev Environment
taurustrend2d --demo
MainThread     INFO     2017-06-15 11:52:11,961 TaurusRootLogger: Using "PyQt4" for Qt
MainThread     INFO     2017-06-15 11:52:14,273 taurus.qt.qtgui.icon.icon: Setting Tango icon theme (from /nfs/home/cpascual/src/taurus/lib/taurus/qt/qtgui/icon/)
Traceback (most recent call last):
  File "/home/cpascual/.local/devenv/bin/taurustrend2d", line 11, in <module>
    load_entry_point('taurus', 'gui_scripts', 'taurustrend2d')()
  File "/nfs/home/cpascual/src/taurus/lib/taurus/qt/qtgui/extra_guiqwt/taurustrend2d.py", line 279, in taurusTrend2DMain
    buffersize=int(options.max_buffer_size))
  File "/nfs/home/cpascual/src/taurus/lib/taurus/qt/qtgui/extra_guiqwt/taurustrend2d.py", line 65, in __init__
    self.setStackMode(stackMode)
  File "/nfs/home/cpascual/src/taurus/lib/taurus/qt/qtgui/extra_guiqwt/taurustrend2d.py", line 99, in setStackMode
    DeltaTimeScaleEngine.enableInAxis(plot, plot.xBottom, rotation=-45)
  File "/nfs/home/cpascual/src/taurus/lib/taurus/qt/qtgui/plot/scales.py", line 395, in enableInAxis
    plot.setAxisScaleDraw(axis, scaleDraw)
  File "/usr/lib/python2.7/dist-packages/qwt/plot.py", line 746, in setAxisScaleDraw
    self.axisWidget(axisId).setScaleDraw(scaleDraw)
  File "/usr/lib/python2.7/dist-packages/qwt/scale_widget.py", line 332, in setScaleDraw
    scaleDraw.setScaleDiv(sd.scaleDiv())
TypeError: QwtAbstractScaleDraw.setScaleDiv(): argument 1 has unexpected type 'QwtScaleDiv'

```

Properly fixing this may be too much work considering that a replacement for the extra_guiqwt submodule is being cooked in TEP17 (see #452), but at least we should provide some workaround and/or a more informative way of failing.

For example, I propose to detect the guiqwt version in the places were PythonQwt-unsupported features are used and fall back to a supported behaviour and/or inform the user that she can use guiqwt v2.3.1

**Comment by teresanunez** [comment]
@cpascual, I agree with you. As you propose, I would inform the user and would try to fall back
 to a supported behaviour.

**Comment by cpascual** [comment]
I just realised that the problems with scales are not strictly due to `QwtScale*`classes not being supported in PythonQwt, but rather because in extra_guiqwt we are attempting to reuse code from the `taurus.qt.qtgui.plot.scales` submodule which imports from PyQwt5 which results in **mixing** implementations (which obviously does not work).

I will do an attempt to duplicate the code from `taurus.qt.qtgui.plot.scales` in `taurus.qt.qtgui.extra_guiqwt` and adapt it to PythonQwt. If this works, we will have some of this issue properly fixed.

**Comment by cpascual** [comment]
It [works](#465)!!  :-D

PS: sad reflection...this is a trivial solution to a long-standing issue. If we had realized before, it may have changed our decisions regarding TEP17
