### ISSUE TITLE
Taurus GUI exception panel doesn't provide model/widget information

### ISSUE THREAD

**Issue by sergirubio** [taurus-org/taurus#474]
I got the following error message (attached). That message warns about an object being discarded by device polling, but it doesn't tell neither which object nor which device nor which widget triggered the exception.

![image](https://user-images.githubusercontent.com/18418345/27375949-f307fc8a-5670-11e7-9bd9-40327fcd02b3.png)

**Comment by cmft** [comment]
Hi @sergirubio ,
I added more verbosity in the TangoAttribute.read method.

**Comment by cpascual** [comment]
Closed from #478
