### ISSUE TITLE
errors reported by lintian4py for taurus

### ISSUE THREAD

**Issue by sf-migrator-bot** [taurus-org/taurus#48]
Hello,

during the packaging process I run the lintian4py program.

I put here the error messages reported by this tool

e: python-taurus: string-exception usr/share/pyshared/taurus/console/table.py:95
w: python-taurus: inconsistent-use-of-tabs-and-spaces-in-indentation usr/share/pyshared/taurus/qt/qtgui/panel/taurusconfigurationpanel.py:55
e: python-taurus: syntax-error usr/share/pyshared/taurus/qt/qtgui/util/tauruswidget_template:9: invalid syntax
e: python-taurus: pyflakes-undefined-name usr/share/pyshared/taurus/core/evaluation/evalfactory.py:807: DoubleRegistration
e: python-taurus: pyflakes-undefined-name usr/share/pyshared/taurus/core/evaluation/evalfactory.py:810: DoubleRegistration
e: python-taurus: pyflakes-undefined-name usr/share/pyshared/taurus/core/evaluation/evalfactory.py:819: DoubleRegistration
e: python-taurus: pyflakes-undefined-name usr/share/pyshared/taurus/core/evaluation/evalfactory.py:822: DoubleRegistration
e: python-taurus: pyflakes-undefined-name usr/share/pyshared/taurus/core/evaluation/evalfactory.py:832: DoubleRegistration
e: python-taurus: pyflakes-undefined-name usr/share/pyshared/taurus/core/evaluation/evalfactory.py:835: DoubleRegistration
e: python-taurus: pyflakes-undefined-name usr/share/pyshared/taurus/core/simulation/simfactory.py:374: taurus
e: python-taurus: pyflakes-undefined-name usr/share/pyshared/taurus/core/tango/sardana/motion.py:155: self
e: python-taurus: pyflakes-undefined-name usr/share/pyshared/taurus/core/tango/sardana/motion.py:344: self
e: python-taurus: pyflakes-undefined-name usr/share/pyshared/taurus/core/taurusbasetypes.py:268: self
e: python-taurus: pyflakes-undefined-name usr/share/pyshared/taurus/core/util/codecs.py:408: bson
e: python-taurus: pyflakes-undefined-name usr/share/pyshared/taurus/core/util/codecs.py:410: decode
e: python-taurus: pyflakes-undefined-name usr/share/pyshared/taurus/core/util/codecs.py:470: ccdName
e: python-taurus: pyflakes-undefined-name usr/share/pyshared/taurus/core/util/singleton.py:48: MyManager
e: python-taurus: pyflakes-undefined-name usr/share/pyshared/taurus/core/util/singleton.py:51: MyManager
e: python-taurus: pyflakes-undefined-name usr/share/pyshared/taurus/qt/qtcore/util/emitter.py:177: self
e: python-taurus: pyflakes-undefined-name usr/share/pyshared/taurus/qt/qtcore/util/emitter.py:178: self
e: python-taurus: pyflakes-undefined-name usr/share/pyshared/taurus/qt/qtcore/util/emitter.py:181: self
e: python-taurus: pyflakes-undefined-name usr/share/pyshared/taurus/qt/qtcore/util/emitter.py:182: self
e: python-taurus: pyflakes-undefined-name usr/share/pyshared/taurus/qt/qtcore/util/emitter.py:186: self
e: python-taurus: pyflakes-undefined-name usr/share/pyshared/taurus/qt/qtcore/util/emitter.py:187: self
e: python-taurus: pyflakes-undefined-name usr/share/pyshared/taurus/qt/qtcore/util/emitter.py:337: self
e: python-taurus: pyflakes-undefined-name usr/share/pyshared/taurus/qt/qtcore/util/emitter.py:338: self
e: python-taurus: pyflakes-undefined-name usr/share/pyshared/taurus/qt/qtcore/util/emitter.py:342: self
e: python-taurus: pyflakes-undefined-name usr/share/pyshared/taurus/qt/qtgui/button/qbuttonbox.py:96: TaurusButtonBox
e: python-taurus: pyflakes-undefined-name usr/share/pyshared/taurus/qt/qtgui/display/qsevensegment.py:501: digitWidget
e: python-taurus: pyflakes-undefined-name usr/share/pyshared/taurus/qt/qtgui/display/qsevensegment.py:507: digitWidget
e: python-taurus: pyflakes-undefined-name usr/share/pyshared/taurus/qt/qtgui/display/qsevensegment.py:513: digitWidget
e: python-taurus: pyflakes-undefined-name usr/share/pyshared/taurus/qt/qtgui/display/qsevensegment.py:519: digitWidget
e: python-taurus: pyflakes-undefined-name usr/share/pyshared/taurus/qt/qtgui/display/qsevensegment.py:525: digitWidget
e: python-taurus: pyflakes-undefined-name usr/share/pyshared/taurus/qt/qtgui/display/taurusboolled.py:147: BoolIndex
e: python-taurus: pyflakes-undefined-name usr/share/pyshared/taurus/qt/qtgui/editor/tauruseditor.py:106: is_file_opened
e: python-taurus: pyflakes-undefined-name usr/share/pyshared/taurus/qt/qtgui/editor/tauruseditor.py:233: TaurusEditor
e: python-taurus: pyflakes-undefined-name usr/share/pyshared/taurus/qt/qtgui/extra_macroexecutor/macroparameterseditor/customeditors/senv.py:370: MacroNode
w: python-taurus: pyflakes-undefined-export usr/share/pyshared/taurus/qt/qtgui/extra_nexus/taurusnexuswidget.py:30: TaurusNexusBrowser
e: python-taurus: pyflakes-undefined-name usr/share/pyshared/taurus/qt/qtgui/extra_nexus/taurusnexuswidget.py:48: HDF5GeneralInfoWidget
e: python-taurus: pyflakes-undefined-name usr/share/pyshared/taurus/qt/qtgui/extra_nexus/taurusnexuswidget.py:49: HDF5AttributesInfoWidget
e: python-taurus: pyflakes-undefined-name usr/share/pyshared/taurus/qt/qtgui/extra_nexus/taurusnexuswidget.py:55: NeXusPreviewWidgetFactory
e: python-taurus: pyflakes-undefined-name usr/share/pyshared/taurus/qt/qtgui/extra_sardana/sardanabasewizard.py:73: QtGui
e: python-taurus: pyflakes-undefined-name usr/share/pyshared/taurus/qt/qtgui/extra_sardana/sardanabasewizard.py:77: QtGui
e: python-taurus: pyflakes-undefined-name usr/share/pyshared/taurus/qt/qtgui/graphic/taurusgraphic.py:83: item_rects
e: python-taurus: pyflakes-undefined-name usr/share/pyshared/taurus/qt/qtgui/image/taurusqub.py:136: numpy
e: python-taurus: pyflakes-undefined-name usr/share/pyshared/taurus/qt/qtgui/panel/qdataexportdialog.py:167: t
e: python-taurus: pyflakes-undefined-name usr/share/pyshared/taurus/qt/qtgui/panel/qrawdatachooser.py:79: QApplication
e: python-taurus: pyflakes-undefined-name usr/share/pyshared/taurus/qt/qtgui/panel/ui/ui_TaurusConfigurationPanel.py:203: Ui_Form
e: python-taurus: pyflakes-undefined-name usr/share/pyshared/taurus/qt/qtgui/table/qdictionary.py:144: self
e: python-taurus: pyflakes-undefined-name usr/share/pyshared/taurus/qt/qtgui/table/taurusvaluestable.py:304: val
e: python-taurus: pyflakes-undefined-name usr/share/pyshared/taurus/qt/qtgui/table/taurusvaluestable_ro.py:154: TaurusValuesTable
e: python-taurus: pyflakes-undefined-name usr/share/pyshared/taurus/qt/uic/pyuic4/taurus.py:28: CW_FILTER
e: python-taurus: pyflakes-undefined-name usr/share/pyshared/taurus/qt/uic/pyuic4/taurus.py:52: MATCH
e: python-taurus: pyflakes-undefined-name usr/share/pyshared/taurus/qt/uic/pyuic4/taurus.py:54: NO_MATCH
w: python-taurus: pyflakes-undefined-export usr/share/pyshared/taurus/qt/uic/tau2taurus_map.py:28:

I hope that they speaks enought by themself.

Cheers

Fred

Reported by: picca ( http://sf.net/u/piccaf )

**Comment by cpascual** [comment]
I close this as it is outdated
