### ISSUE TITLE
TaurusJDrawSynopticView sometimes does not start drawing

### ISSUE THREAD

**Issue by cpascual** [taurus-org/taurus#484]
This is similar to #360 (already fixed), but not quite the same...

To reproduce, download the [syntest.txt](https://github.com/taurus-org/taurus/files/1109437/syntest.txt) file and run:
`python -m taurus.qt.qtgui.graphic.jdraw.jdraw_view syntest.txt`

Most of the times (although not always) I get an empty white synoptic:

![fail](https://user-images.githubusercontent.com/4115224/27649046-db6707fe-5c30-11e7-8fc6-13d245130bb5.png)

If I resize the window, a value appears and from that moment it correctly updates every 3s (without requiring further interaction):

![afterresizing](https://user-images.githubusercontent.com/4115224/27649053-e05734be-5c30-11e7-9849-5bcabaf6843d.png)

Sometimes the value is shown from the beginning and it updates ok, so it may be a race condition with events or signals...

**Comment by cpascual** [comment]
@sergirubio may know what's going on...

**Comment by cmft** [comment]
The error is in TaurusJDrawSynopticsView.fitting method when ADJUST_FRAME is True (Called in setMolde).

This resize call causes the trouble, I don't understand the use of it, but I see two possible solutions:
1) (As a workaround) avoid to do it.
2) Replace this call by a `scale` call
```
        if ADJUST_FRAME:  # This additional resizing adjust the "white" frame around the synoptic
            self.debug(
                '\tResizing: size(%s,%s),hint(%s,%s),srect(%s,%s),parent(%s,%s)' % self.get_sizes())
            self.resize(self.sizeHint() + Qt.QSize(5, 5))
```

What do you think @sergirubio ?

**Comment by sergirubio** [comment]
Tested with vacca and esrf linac synoptic, the fix works
