### ISSUE TITLE
How to check if a device has a given attribute

### ISSUE THREAD

**Issue by reszelaz** [taurus-org/taurus#492]
I would like to check if a given attribute exists in a device.
I know how to do it in PyTango using `DeviceProxy.get_attribute_list`. How can I do it with Taurus?
When I create a taurus Device and get an attribute from it, it always returns a taurus Attribute even if the attribute does not exist.

**Comment by cmft** [comment]
Hi @reszelaz,
The PyTango API is exposed in a taurus (tango) device.

```
In [1]: import  taurus
In [2]: d = taurus.Device("sys/tg_test/1")
In [3]: d.get_attribute_list()
Out[3]: ['ampli', 'boolean_scalar', 'double_scalar', 'double_scalar_rww', 'double_scalar_w', 'float_scalar', 'long64_scalar', 'long_scalar', 'long_scalar_rww', 'long_scalar_w', 'no_value', 'short_scalar', 'short_scalar_ro', 'short_scalar_rww', 'short_scalar_w', 'string_scalar', 'throw_exception', 'uchar_scalar', 'ulong64_scalar', 'ushort_scalar', 'ulong_scalar', 'boolean_spectrum', 'boolean_spectrum_ro', 'double_spectrum', 'double_spectrum_ro', 'float_spectrum', 'float_spectrum_ro', 'long64_spectrum_ro', 'long_spectrum', 'long_spectrum_ro', 'short_spectrum', 'short_spectrum_ro', 'string_spectrum', 'string_spectrum_ro', 'uchar_spectrum', 'uchar_spectrum_ro', 'ulong64_spectrum_ro', 'ulong_spectrum_ro', 'ushort_spectrum', 'ushort_spectrum_ro', 'wave', 'boolean_image', 'boolean_image_ro', 'double_image', 'double_image_ro', 'float_image', 'float_image_ro', 'long64_image_ro', 'long_image', 'long_image_ro', 'short_image', 'short_image_ro', 'string_image', 'string_image_ro', 'uchar_image', 'uchar_image_ro', 'ulong64_image_ro', 'ulong_image_ro', 'ushort_image', 'ushort_image_ro', 'State', 'Status']

```

Is it enough for you?

**Comment by reszelaz** [comment]
Thanks! But I was looking for a pure Taurus solution. Does it exist?

**Comment by cmft** [comment]
No, it does not. As you have explained `getAttribute` method returns always a TaurusAttribute (that could not exist).

**Comment by reszelaz** [comment]
Ok. Thanks anyway!

**Comment by cpascual** [comment]
In general we have not forced Taurus devices to necessarily keep track of "their" attributes. Think for example in the eval scheme, where attributes are created dynamically and destroyed as soon as they are not referenced.

In fact, I am not sure that all schemes must follow a hierarchy where every attribute belongs to a device. For example, in EPICS we only implement  attributes (which map the PVs), and the devices are currently dummy. But imagine that we eventually mapped the EPICS device concept to a TaurusDevice. In that case, an attribute could belong to more than one device... or to none (EPICS devices are just arbitrary collections of PVs). 

And I think that other schemes may pose similar difficulties if we try to generalize the Tango Device-Attribute relationship...

But we could consider some solution.

**Comment by reszelaz** [comment]
It is not necessary to keep a track of all the attributes. It would be enough by interrogating a TaurusAttribute object, for example, if it exists or if it is ready. Something similar `TaurusDevState`. In this way, if a scheme has this information, it can give it to the user.

**Comment by cpascual** [comment]
>  It would be enough by interrogating a TaurusAttribute object, for example, if it exists or if it is ready

...but, how to do it without actually creating the attribute?

Maybe we could interrogate *the `Factory`* instead ...

**Comment by reszelaz** [comment]
What I do now is:
```
ioreg_dev = taurus.Device("myioreg")
attr_names = [attr.lower() for attr in ioreg_dev.get_attribute_list()]
if "labels" in attr_names:
    # labels attribute exists...
```
This could be substituted by (I use device state analogy on purpose here, but at the end we could think of making an abstract state applicable to any type of taurus model):
```
ioreg_dev = taurus.Device("myioreg")
labels = ioreg_dev.getAttribute("Labels")
if labels.state() == TaurusDevState.Ready:
    # labels attribute exists...
```

**Comment by cpascual** [comment]
But even before considering the issue of defining a "state" for an attribute, we should decide what to do with the Device<-->Attribute relationship. In you example, you are assuming that a Device knows "its" attributes (you are using the `getAttribute` method, which is Tango-centric), but the word "its" may not make sense in other schemes.

**Comment by reszelaz** [comment]
You are right. If we get rid of the `TaurusDevice.getAttribute` I would need to change my approach. But I think it would still work for me creating directly a `TaurusAttribute`.

I see your point breaking the Device<-->Attribute relation, and I consider your examples as valid.
