### ISSUE TITLE
UI colors not printed in the pdf

### ISSUE THREAD

**Issue by PhilLAL** [taurus-org/taurus#498]
Hi there,
I am not sure this is desired effect but in the source/users/ui/ui_colors.rst, the ".. raw:: html" command before each color tab make it printed only in html doc.
For an offline reading of the doc, a similar view would be useful.

edit : colors can be found int the html doc at page http://taurus-scada.org/en/latest/users/ui/ui_colors.html

**Comment by cmft** [comment]
Hi @PhilLAL ,
You are right. Could you create a PR?

Many thanks for reporting it.

**Comment by PhilLAL** [comment]
I am not sure how to organize same data in a PDF but I'll see when I get some time.

**Comment by PhilLAL** [comment]
I checked sphinx but I am not familiar enough to help for this, sorry.

**Comment by cpascual** [comment]
Just as we did for #549 & #585, I am closing this since it relates to PDF generation and we don't do that anymore
