### ISSUE TITLE
taurusplot : getting point information start a zoom

### ISSUE THREAD

**Issue by PhilLAL** [taurus-org/taurus#500]
When I click on a point, I get coordinate informations but I start a zoom selection area which result in a zoom.
I need to click again exactly on the same point to avoid this behaviour.

It is not really a problem but it should be probably documented in source/users/ui/plot.rst if this is the normal behaviour.

**Comment by cpascual** [comment]
You are right. I think this is a bug. The zoom should only start when dragging, not when just clicking.
However, unless someone is very interested in having this fixed, I propose to concentrate the efforts in the new plot widgets ( see #452 ), since the PyQwt5-based ones will eventually be dropped.

**Comment by PhilLAL** [comment]
Yes of course, I just put it in the case it has not been seen.
However, as you said, it is not critical so it can be let unsolved.

**Comment by cpascual** [comment]
Ok, so I am closing this as rejected.
Thanks for reporting.
