### ISSUE TITLE
Plotting Trends example does not work

### ISSUE THREAD

**Issue by PhilLAL** [taurus-org/taurus#504]
While trying to execute http://taurus-scada.org/en/latest/devel/examples.html#plotting-trends example, It crashed at line 2 
> panel = TaurusTrend()

Here is the output of dependencies checking, it seems OK with http://www.taurus-scada.org/en/latest/users/getting_started.html#dependencies : 

>   import taurus
>    taurus.check_dependencies()
>    Checking required dependencies of taurus.core...
>    	Checking for Python >=2.6.0... [OK] (Found 2.7.9)
>    Checking OPTIONAL dependencies of taurus.core...
>    	Checking for PyTango >=7.1.0... [OK] (Found 8.1.5)
>    Checking required dependencies of taurus.qt...
>    	Checking for PyTango >=7.1.0... [OK] (Found 8.1.5)
>    	Checking for PyQt >=4.4.0... [OK] (Found 4.11.2)
>    	Checking for PyQwt >=5.2.0... [OK] (Found 5.2.3)
>    Checking OPTIONAL dependencies of taurus.qt...
>    	Checking for Qub >=1.0.0... [WARNING] (Not found])
>    	Checking for spyder >=3.0.0... [WARNING] (Not found])
>    	Checking for qtcontrols >=1.0.0... [WARNING] (Not found])

**Comment by cmft** [comment]
Did you add the [common part](http://taurus-scada.org/en/latest/devel/examples.html#common)?

It works for me.

```
import sys
from taurus.external.qt import Qt
from taurus.qt.qtgui.application import TaurusApplication

app = TaurusApplication(sys.argv)
panel = Qt.QWidget()
layout = Qt.QHBoxLayout()
panel.setLayout(layout)

##
from taurus.qt.qtgui.plot import TaurusTrend
panel = TaurusTrend()
model = ['sys/tg_test/1/float_scalar']
panel.setXIsTime(True) #to show the x values as time
panel.setModel(model)
##

panel.show()
sys.exit(app.exec_())
```

**Comment by PhilLAL** [comment]
Of course, that's our fault, thank you for pointing this out.
