### ISSUE TITLE
(doc) PDF table of contents nearly empty

### ISSUE THREAD

**Issue by PhilLAL** [taurus-org/taurus#507]
The PDF toc is nearly empty, it just contains : 

>1    Projects related to Taurus    3
>1.1 Taurus 4.0 documentation    3
>Python Module Index               579

**Comment by cpascual** [comment]
I confirm it. But I have no idea on how to fix it (this is sphinx-magic done at readthedocs). Help would be appreciated.
As a workaround, if you want to have a "printer-friendly" doc you could use the Epub file (the TOCs are well generated for the epub and it is also not affected by #498 )

**Comment by PhilLAL** [comment]
I checked sphinx but I am not familiar enough to help for this, sorry.
Perhaps the ":hidden:" just after the ".. toctree::" is linked to this issue...

**Comment by cpascual** [comment]
Fixed by #548
