### ISSUE TITLE
taurustrend Clear Buffers options changes the curve configuration

### ISSUE THREAD

**Issue by mrosanes** [taurus-org/taurus#516]
When using the menu option "Clear Buffers" from taurustrend, the curve configuration is changed.

After clearing the buffer, when the new points appears, the curve width, the color and the line style are not restored. They are changed to different colors, width and line style.

**Comment by cpascual** [comment]
Confirmed.
But we won't put much effort now in the PyQwt5-based plots/trends. We will instead work on replacing them by pyqtgraph ones (see TEP17: #452 )
