### ISSUE TITLE
Connecting to Tango7 DB with Taurus4 makes images and spectrums disappear

### ISSUE THREAD

**Issue by mrosanes** [taurus-org/taurus#521]
Connecting to Tango7 DB with Taurus4 makes images and spectrums disappear on a taurusform.

We have encountered this problem working in taurus-test docker and also working in a machine with a firewall activated. 

How to reproduce:
Export a Tango7 DB
```
export TANGO_HOST=controls02:10000
taurusform sys/tg_test/1/boolean_image
```

After 10 seconds, the  "show" and "edit" buttons, change, and report dashes: "------".

**Comment by mrosanes** [comment]
This is a problem in the network. If a firewall is used, or if using a docker, this problem exist; but if the firewall is deactivated; and if no docker is used, the problem is no present.

The problem is not a problem from Taurus. It is related with the infrastructure and Tango events, that are not communicated correctly within docker or with a firewall activated. Thus, we reject this ticket.

**Comment by mrosanes** [comment]
It also happens in windows (when connecting to a Tango7 DB).

**Comment by cpascual** [comment]
> It also happens in windows (when connecting to a Tango7 DB).

It will happen in any situation where the machine does allow connections to all the ports that tango requires. 
You see it in a Win7 **virtual machine** were the needed ports are not mapped (just as it happened with the docker). But it is very likely that if you configure the ports adequately, you would not see the issue.
