### ISSUE TITLE
zoom in taurustrend by selecting a ROI does not always work

### ISSUE THREAD

**Issue by mrosanes** [taurus-org/taurus#523]
zoom in taurustrend by selecting a ROI does not always work.

If playing with different zooms some time the zoom by selecting a ROI in the taurustrend does not work.

Beginning to select the ROI, then using the wheel of the mouse, and finishing to select the ROI. After this and playing more with the zooms, sometimes the ROI selection does not work. The square for the ROI selection appears, but no zoom is applied. This is difficult to reproduce, but it happens often.

**Comment by cpascual** [comment]
Confirmed.
But we wont put much effort now in the PyQwt5-based plots/trends. We will instead work on replacing them by pyqtgraph ones (see #tep17)
