### ISSUE TITLE
 Taurus 4.0.3 in Windows7: if TANGO_HOST not defined, the launchers does not work

### ISSUE THREAD

**Issue by mrosanes** [taurus-org/taurus#529]
Taurus 4 in Windows7: if TANGO_HOST not defined, the launchers does not work.

When trying to execute 'taurustrend' from the command line, the taurustrend reports a lot of error messages and closes really fast. The error messages cannot be seen because it happens too fast.
However by doing a printscreen the message catched is:
![error_tango_host_not_defined](https://user-images.githubusercontent.com/1327426/28417497-a31b001a-6d58-11e7-90b1-fa29dfeef8c5.jpg)

--

It would be interesting to report to the user (or taurus developer) that the TANGO_HOST is not defined.

--

**Comment by cpascual** [comment]
Closed via bc114cf
