### ISSUE TITLE
Error when loading synoptic on example01 under Windows

### ISSUE THREAD

**Issue by mrosanes** [taurus-org/taurus#533]
Windows 7 (64bits) - taurus 4.1.0 (32 bits) -

Error when loading synoptic on 'taurusgui example01'  under Windows
![synoptic](https://user-images.githubusercontent.com/1327426/28454098-44e529a6-6dfa-11e7-9863-e2b6d296b996.jpg)

**Comment by cpascual** [comment]
Closed via #538
