### ISSUE TITLE
Bug with Panel Nexus Browser on windows7, taurusgui example01 

### ISSUE THREAD

**Issue by mrosanes** [taurus-org/taurus#534]
Win7 (64bits) - taurus4.1.0 (32 bits)

When launching taurusgui example01 a bug with Panel Nexus Browser is present on windows7.
![nexus_win7_example01](https://user-images.githubusercontent.com/1327426/28454297-f6922686-6dfa-11e7-9f72-75ee900c719b.jpg)

**Comment by cpascual** [comment]
This is due to a missing dependency (PyMca5)

**Comment by mrosanes** [comment]
Installation of PyMca5 in Windows7 works if installed from pip:
pip install PyMca5

By doing so, TaurusNexusBrowser works (for Taurus4.3).

--
Note: for completion, I have performed some tests installing PyMca5 from the .exe binaries (at different versions) and including PyMca module in PythonPath, and this does not work correctly.
Conclusion is, that on Windows7, it seems to be required to install PyMca5 from pip (at least, it is preferred for the moment).
