### ISSUE TITLE
Windows and Taurus4: taurusconfigbrowser cannot open ini files

### ISSUE THREAD

**Issue by mrosanes** [taurus-org/taurus#543]
Windows and Taurus4: taurusconfigbrowser cannot open ini files.

When trying to open an ini file in windows, it gives errors because of permits.
![taurusconfigbrowser](https://user-images.githubusercontent.com/1327426/28614330-b94fd4ea-71f5-11e7-8e22-b2b558d8a628.jpg)

**Comment by mrosanes** [comment]
This happens as well in Jan18 Release (Taurus 4.3)

**Comment by tiagocoutinho** [comment]
Reproduced with windows 10 using vagrant.
conda environment using:

* python 3.6
* pyqt 5.6
* qt 5.6.2
* taurus 4.5.1
* pytango 9.3.1 rc1 from tiagocoutinho conda channel
