### ISSUE TITLE
[doc] users/ui misplaced paragraph

### ISSUE THREAD

**Issue by PhilLAL** [taurus-org/taurus#544]
Hello, 
into doc/source/users/ui/index.rst (at the end of the page) appears the following sentences:
"This section explains some features that are common to most applications built with taurus. This is done from the GUI user point of view (not for developers).
For a detailed list of features of each widget, please refer to the Developer’s Guide"

However, it seems to me this sentences would be more understandable if it appears at the beginning of the users/ui chapter to explain what it contains. 
Perhaps is it due to the fact that toctree sphinx instruction add file contents where each part is listed.

**Comment by cpascual** [comment]
Closed via #546
