### ISSUE TITLE
[doc] misplaced figures in the pdf

### ISSUE THREAD

**Issue by PhilLAL** [taurus-org/taurus#545]
Hi,
I noticed that some figures  of the PDF doc are misplaced outside from their chapter. For example,taurus configuration browser figure (http://taurus-scada.org/en/latest/users/ui/configurations.html) and  screenshots figures (http://taurus-scada.org/en/latest/users/screenshots.html) are placed into developer guide section into the PDF doc.

Perhaps some anchors to figures could help (I think to something like https://stackoverflow.com/questions/13706250/linking-to-figures-in-sphinx or https://stackoverflow.com/questions/2686310/referencing-figures-with-numbers-in-sphinx-and-restructuredtext)
Also, some new pages (https://stackoverflow.com/questions/26120570/sphinx-add-a-page-break-in-my-pdf-with-latexpdf) could help also. However in this case, it will probably move taurus config browser figure to screenshots section (except if a newpage is set at the end of every section, but I do not think it is not a good choice).

**Comment by cpascual** [comment]
Thanks for reporting!
If you can test some of the proposed solutions and make a PR, we would really appreciate it!

**Comment by PhilLAL** [comment]
I would need to get into the doc building to check it works, but the only try I have done was not conclusive.
I can suggest a PR without build if someone can check...

**Comment by cpascual** [comment]
> I can suggest a PR but without building it, it will need someone who can check... Does it sound possible?

Definitely. That would be great!

(Only one thing: I will be out of office next 2 weeks, so I won't be able to look into it until I come back)

**Comment by PhilLAL** [comment]
Ok (I will be back at the same time, note sure I will have time to do this before).

To help (me) doing tests, here are some informations:

- concerned instructions: ".. figure" or ".. image" (not sure why there is two different instructions used)
- figures which are misplaced into the pdf:

  * figure /_static/taurusmodelchooser01.png appears into the toc of "TaurusPlot User’s Interface" section instead of "TaurusModelChooser User’s Interface" section
  * figure /_static/taurusconfigbrowser.png appears into "Developer's Guide" section instead of "Taurus Configuration Browser User’s Interface" section
  * figure /_static/taurusdemo.png appears into "Taurus Configuration Browser User’s Interface" section instead of "Taurus Configuration Browser User’s Interface" section
  * figures /_static/taurusgui-newpanel01.png and /_static/taurusgui-permanentpanels01.png appear into "Perspectives" subsection instead of "Creating custom panels" subsection
  * figure /_static/taurusgui-extapp.png is misplaced int he same subsection (not essential)
  * figure /_static/macrogui01.png is misplaced int he same subsection (not essential)
  * figure /_static/taurusarrayeditor01.png appears into Synoptic section instead of "Array Editor" section
  * every figures from doc/source/users/screenshots.rst appears into "Developer's Guide" section instead of "Screenshots" section

- figures which are **not** misplaced into the pdf: 

  * all the ones from doc/source/users/ui/trend.rst
  * all the ones from doc/source/users/ui/plot.rst 
  * all the ones from doc/source/users/ui/forms.rst 
  * the one from doc/source/users/introduction.rst

**Comment by PhilLAL** [comment]
It seems to me Sphinx attempts to use all the space it can while filling empty space with paragraph and sending figures to the next section. 
This behavior does not seems bad since it avoids to let half-empty pages because a figure should precisely be put after a paragraph. Then, several solutions can be combined:

- give the name of figures into the text if needed or an attached legend to clarify the context of the image
- add some newpage at the end of a section to avoid a new section begins with an inconsistent image. I will focus on this solution since I do not know what is the will for the doc.

**Comment by PhilLAL** [comment]
Good news is this new doc seems to solve a lot of misplaced figures.

The only part which does not solve is into doc/source/users/screenshots.rst appears, where several figures  still appears at the beginnin of "Developer's Guide" section instead of "Screenshots" section.

Also a lot of figures which were not misplaced are now.
It seems the best to do would be to add legend to figures (see http://docutils.sourceforge.net/docs/ref/rst/directives.html#figure).

**Comment by cpascual** [comment]
👍  I agree with the solution of adding a legend. 
@PhilLAL , are you willing to do it?

**Comment by PhilLAL** [comment]
Hmm, sorry, not sure I will have time in a short term.

**Comment by cpascual** [comment]
> Hmm, sorry, not sure I will have time in a short term.

@PhilLAL : do not worry, it is totally understandable.
Since it is not critical, we will leave the issue open with the Help Wanted label and see if someone jumps into it. ;)

**Comment by cpascual** [comment]
Just as we did for #549 & #585, I am closing this since it relates to PDF generation and we don't do that anymore
