### ISSUE TITLE
subscribe to the same event multiple times

### ISSUE THREAD

**Issue by PhilLAL** [taurus-org/taurus#551]
Hi,
into http://taurus-scada.org/en/latest/devel/core_tutorial.html#advantages-of-accessing-tango-via-taurus-over-pytango in the section tango event abstraction, it written "subscribe to the same event multiple times".

What is the taurus behaviour in this case?
Thank you.

**Comment by cpascual** [comment]
In Taurus adding the same listener to an attribute more than once has no effect, as you can see with the following snippet:

```python
import taurus
import time

a = taurus.Attribute('sys/tg_test/1/ampli')

def f(*args):
    print args

a.addListener(f)
a.addListener(f)
a.addListener(f)
a.addListener(f)
a.addListener(f)
a.addListener(f)
a.addListener(f)
a.addListener(f)

time.sleep(4)
```

**Comment by PhilLAL** [comment]
Thank you, that is indeed the most logical behaviour.
