### ISSUE TITLE
Sardana polling issues

### ISSUE THREAD

**Issue by johanfforsberg** [taurus-org/taurus#555]
Hi all,

At MAX IV we're trying to move to HDB++ for archiving. Sardana is in use both in the machine and at beamlines, and we want to archive things like motor positions.

However (as also noted in sardana ticket #435) to do this we currently need to enable polling on the motors, in order to get archive events. For now we're not polling very fast, perhaps 1-3 s. This appears to work OK from the HDB++ point of view, but it creates some issue with Taurus.

The problem is that when device polling is enabled on a motor position, e.g. a Taurus form showing this motor will exhibit unexpected behavior if the motor is moved. The position "flips" back and forth in a confusing way. 

As far as I can tell, the problem arises from the way Taurus stays up to date with Sardana motors. It seems that it's both subscribed to change events, and also doing its own internal polling, which reads from CACHE_DEVICE. I suppose this is done because Sardana does not push change events unless a motor is actually being moved. Since the polling thread fills the cache, the read value will typically be fairly old compared to the last change event, which causes the displayed value to "jump" back a bit.

Now this is mostly a "cosmetic" GUI problem, we haven't really tested properly yet but I'm assuming that this will not affect Sardana operations like scans. It's probably something we can live with in the short term, but I'm wondering if there exists a solution for this already? Maybe either disabling the Taurus polling (at least for polled attributes, or while they are moving), or always reading from DEVICE directly would solve the problem. I suppose doing very fast polling would hide the issue, but then we might run into other problems like the infamous "polling too slow" errors.

Thanks!

Taurus version 3.6.0, Sardana 1.4 and 2.3.2, TANGO 9.2.5

**Comment by cpascual** [comment]
I seem to remember that we already noticed something similar using TaurusTrend, but I do not remember if we solved it there of if we worked around it somehow...

I think there was some talk with @reszelaz  on dealing with this by distinguishing between change and periodical events...

**Comment by reszelaz** [comment]
@johanfforsberg please take a look on these tickets:

https://github.com/sardana-org/sardana/issues/326
https://github.com/taurus-org/taurus/issues/216

I think they talk about the same issue. 

I could come back to this discussion when I'm back at work in September.

**Comment by cpascual** [comment]
@reszelaz is right. I am closing this one as a dup of #216.
