### ISSUE TITLE
Possibility to disable "Unknown unit" warning.

### ISSUE THREAD

**Issue by mbroseta** [taurus-org/taurus#561]
Hi all,

We are experiencing slow boot problems in our GUI's and one of the reasons could be the huge quantity of WARNING messages we have due to "unknown unit" in tango attributes.

It will be useful to have the possibility to disable this warning and avoid the checking at boot up. Actually, the only way we have seen to avoid this warning is not declaring the attribute as "no unit" because this also reports the same warning, but with an empty space " ".

Thanks
Manolo

**Comment by cpascual** [comment]
> It will be useful to have the possibility to disable this warning and avoid the checking at boot up.

Currently the "unknown unit" messages in TangoAttributes are logged with WARNING level. I propose to make this level configurable via tauruscustomsettings. In this way the level could be set to DEBUG (either globally by editing tauruscustomsettings.py or on a per-application basis by modifying the value at run-time)

> Actually, the only way we have seen to avoid this warning is not declaring the attribute as "no unit" because this also reports the same warning, but with an empty space " ".

Note that setting the unit to " " is a valid way of declaring the quantity to be "unitless"

**Comment by sergirubio** [comment]
I think that in any case it should be studied why the loading of tauruslabels became slower in later versions.

**Comment by cpascual** [comment]
I think this got solved with #662
