### ISSUE TITLE
taurus.external.qt  can not import QtWebKit

### ISSUE THREAD

**Issue by cmft** [taurus-org/taurus#568]
On debian 9 with python-pyqt5.qtwebkit package installed
this fails: `from taurus.external.qt.QtWebKit import QWebView`
but this work `from PyQt5.QtWebKitWidgets import QWebView`

If I run both imports in the same console:
`RuntimeError: the PyQt5.QtCore and PyQt4.QtCore modules both wrap the QObject class`

I tried with `from taurus.external.qt.QtWebKitWidgets import QWebView` but it fails

**Comment by cpascual** [comment]
This is probably related with the [removal of QtWebkit support for PyQt4 in debian9](https://lists.debian.org/debian-devel-announce/2015/05/msg00001.html)

Note that for now Taurus only really supports PyQt4. Note that importing from PyQt5 is not a valid solution until we support PyQt5.

There is no much we can do except supporting PyQt5 (see #203 )

**Comment by cpascual** [comment]
I am closing this as a dup of #203
