### ISSUE TITLE
ExternalApp(...) creates zombie processes of exit

### ISSUE THREAD

**Issue by jkotan** [taurus-org/taurus#576]
Hi,

our users complain that `ExternalApp(...)` , e.g. `xterm spock` or `pymca`, when you open it and close it many time produces a lot of zombie processes ( i.e. `<defunct>`). If the  user GUI is running for longer time it can be even 100  or more zombies which is annoying.
 A possible fix would be from time to time to remove zombies, e.g.

    diff --git a/lib/taurus/qt/qtgui/util/taurusaction.py b/lib/taurus/qt/qtgui/util/taurusaction.py
    index 1c46911..b01d836 100644
    --- a/lib/taurus/qt/qtgui/util/taurusaction.py
    +++ b/lib/taurus/qt/qtgui/util/taurusaction.py
    @@ -109,6 +109,7 @@ class ExternalAppAction(Qt.QAction, BaseConfigurableClass):
		 if any(args):
		     #Qt.QMessageBox.warning(self.parentWidget(),'Warning','In ExternalAppAction(%s)'%args)
		     self._process.append(subprocess.Popen(args))
    +                self._process = [p for p in self._process if p.poll() is None]
		     return True
		 else:
		     return False

What do you think?

Best regards,
Jan

**Comment by cpascual** [comment]
Hi Jan,
The proposed solution seems reasonable (but I haven't tested it)
Would you care to create a PR?

**Comment by cpascual** [comment]
Fixed by #577
