### ISSUE TITLE
taurustrend: unable to plot archiving on Taurus 4

### ISSUE THREAD

**Issue by sergirubio** [taurus-org/taurus#582]
Whenever Taurus 4 tries to show the "Archiving warning" dialog, this exception appears:
```

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/taurus/qt/qtgui/plot/taurustrend.py", line 1601, in _scaleChangeWarning
    self.showArchivingWarning()
  File "/usr/lib/python2.7/dist-packages/taurus/qt/qtgui/plot/taurustrend.py", line 1611, in showArchivingWarning
    self.axisWidget(self.xBottom).scaleDivChanged.disconnect(self._scaleChangeWarning)
TypeError: disconnect() failed between 'scaleDivChanged' and 'unislot'

```

**Comment by cpascual** [comment]
Seems like an attempt to disconnect a non-connected signal (I think this was allowed with old-style signals but it is not with the new ones). So the disconnect needs to be protected.
@sergirubio : Since this is your own code, could you make a PR correcting it?

**Comment by MikeFalowski** [comment]
Does it mean it's not possible to plot archived values?

**Comment by sergirubio** [comment]
Hi Mike,
This bug was already corrected last november, so plotting data from MySQL archivings works again
For Cassandra archiving, I'll need some time to update the branch, patience
Sergi

**Comment by sergirubio** [comment]
This issue can be closed
