### ISSUE TITLE
taurus.core.tango: "No unit" to be considered unitless

### ISSUE THREAD

**Issue by sergirubio** [taurus-org/taurus#584]
The solution to set unit = " " is not practical as any dynamic attribute created or renamed will loose this config on change. It also creates unnecessary entries into the database that will slow down all queries done to attribute properties values (e.g. to load memorized values from sardana).

To solve that, the taurus.core.tango module should be aware the already known Tango defines for those properties that are "not initialized":

"no unit"
"not defined"
"not specified"
"nada"

This already known defines should be understood by the taurus.core.tango module; for example to recognize a "no unit" attribute as unitless.

**Comment by cpascual** [comment]
It seems reasonable to me, but I would like to be sure to interprete things right (e.g. for Tango, "no unit" means "this is unitless" or "I didn't define this unit"?). 
So, @sergirubio do you know if there is some place where these defines are documented?
(or, if not, at least where in the Tango code can we find those defines?)

**Comment by cmft** [comment]
I  tested it  and  tango treated all of these definition as "Not unit" as @sergirubio said. But the tango official [documentation](http://tango-controls.readthedocs.io/en/latest/development/advanced/reference.html?highlight=unit%20attribute#setting-modifiable-attribute-parameters) and it says it returns an empty string if it  "value" is set.

Taurus use a `PyTango` constant to evaluate the unit `PyTango.constants.UnitNotSpec` that returns "" instead of "No unit" 

So, something is incoherence.  I think it is a bug in PyTango, and in Tango documentation.

**Comment by cpascual** [comment]
After looking at the docs mentioned by @cmft , I agree with him in that there seems to be an inconsistency between Tango docs and PyTango implementation (on which we depend).

For Tango, the default value for `unit` is an empty string. And according to [this](http://tango-controls.readthedocs.io/en/latest/development/advanced/reference.html#resetting-modifiable-attribute-parameters) its meaning is the same as "Not Specified".

**Comment by sergirubio** [comment]
So, this means that we should patch PyTango to return "" instead of "no unit" and patch taurus to consider "" as unitless. Isn't it?

I've found that this change has been done in tango_const.h in the transition from Tango 8  to Tango 9. It means that we may need to upgrade all databases to Tango 9 to have a uniform behavior.

**Comment by cmft** [comment]
PyTango should return `PyTango.constants.UnitNotSpec` instead of "No unit". The Taurus behaviour must be disused with the community.

**Comment by cpascual** [comment]
> So, this means that we should patch PyTango to return "" instead of "no unit" 

More or less... as @cfalcon points out, the actual return value should be PyTango.constants.UnitNotSpec (which is currently "")

> and patch taurus to consider "" as unitless. Isn't it?

Nope. "" would mean "not specified", which is not the same as unitless

**Comment by cpascual** [comment]
I opened a thread related to this in the Tango Forum: 
http://www.tango-controls.org/community/forum/post/2856/

**Comment by cpascual** [comment]
Created an issue in Tango:
https://github.com/tango-controls/TangoTickets/issues/8

**Comment by cpascual** [comment]
We decided that while waiting for Tango to decide if they clarify the unitless VS unit-not-defined issue, we will treat "No unit" the same as `PyTango.constants.UnitNotSpec` to avoid the warnings.

See #662
