### ISSUE TITLE
[doc] missing chapter into PDF

### ISSUE THREAD

**Issue by PhilLAL** [taurus-org/taurus#585]
I do not have time to push a PR now so I make a list of things to correct : it seems to be same HTML/PDF bugs as in #507 

Reading the doc, I noticed that chapter taurus page 67 of the PDF contains only the first phrase.
The content of HTML is more complete : http://taurus-scada.org/en/latest/devel/api/taurus.html

Same for taurus.console.util at same PDF page, even if HTML just contains a link to util (http://taurus-scada.org/en/latest/devel/api/taurus/console.html).

Same for taurus.core at same PDF page (http://taurus-scada.org/en/latest/devel/api/taurus/core.html).

At end of PDF page 71, classes do not appear (http://taurus-scada.org/en/latest/devel/api/taurus/core/evaluation.html).

At end of PDF page 78, classes and functions do not appear (http://taurus-scada.org/en/latest/devel/api/taurus/core/resource.html).

At end of PDF page 90, that is the **opposite** : details of unregisteredDeviceClass appear into PDF (without title) as Functions but they do not in HTML (http://taurus-scada.org/en/latest/devel/api/taurus/core/resource/_TaurusFactory.html).

At end of PDF page 91, Modules and Classes do not appear as in HTML (http://www.taurus-scada.org/en/latest/devel/api/taurus/core/tango.html).

At PDF page 92, Classes and functions do not appear as in HTML (http://www.taurus-scada.org/en/latest/devel/api/taurus/core/tango/img.html).

At PDF page 100, that is the **opposite** again : under PyImageViewer details do appear, and Functions appear in PDF but not in HTML (http://www.taurus-scada.org/en/latest/devel/api/taurus/core/tango/img/_PyImageViewer.html).

Same at PDF page 124 which make details of state() appear, they do not appeat in HTML (http://www.taurus-scada.org/en/latest/devel/api/taurus/core/tango/_TangoServInfo.html).

At PDF page 124, Modules, Classes and Functions do not appear, they do in HTML (http://www.taurus-scada.org/en/latest/devel/api/taurus/core/util.html).

At PDF page 127, Classes do not appear as in HTML (http://www.taurus-scada.org/en/latest/devel/api/taurus/core/util/report.html).

At PDF page 127, this is the **opposite**, Classes appear in PDF but not in HTML (http://www.taurus-scada.org/en/latest/devel/api/taurus/core/util/report/_TaurusMessageReportHandler.html).

...

**Comment by cpascual** [comment]
Just as we did for #549, I am closing this since it relates to PDF generation and we don't do that anymore
