### ISSUE TITLE
Strange behavior of Tango validator with strict=False

### ISSUE THREAD

**Issue by reszelaz** [taurus-org/taurus#586]
I observe a strange behavior of the new Tango validators, well actually just tested on the device validator, but it could affect others as well.

With taurus/support-3.x the validator behaves as following:

```
In [1]: from taurus.core.taurusvalidator import DeviceNameValidator

In [2]: v = DeviceNameValidator()

In [3]: v.getNames("controls01:10000/a/b/c")
Out[3]: ('a/b/c', 'a/b/c', '')
```

With taurus/develop the validator behaves as following:

```
In [1]: from taurus.core.tango.tangovalidator import TangoDeviceNameValidator

In [2]: v = TangoDeviceNameValidator()

In [3]: v.getNames("controls01:10000/a/b/c")

In [4]: v.getUriGroups("controls01:10000/a/b/c")

In [5]: v.getUriGroups("controls01:10000/a/b/c", strict=False)
```

So in all these cases, the validator returns nothing. Shouldn't in in case of strict flag set to False return something?

**Comment by cpascual** [comment]
I think this is a bug. 
In theory 
```python
v = TangoDeviceNameValidator() 
v.getUriGroups("controls01:10000/a/b/c", strict=False)
``` 
should return a groups dict in that case (not None)

**Comment by cmft** [comment]
I confirm the bug. The back. comp. URI is buggy, and  it is even worst. It returns a  group.

```
v.getUriGroups("\\\\controls01:10000/a/b/c", strict=False)
```
