### ISSUE TITLE
use taurus for developping with a distant device 

### ISSUE THREAD

**Issue by PhilLAL** [taurus-org/taurus#600]
Hello,
I ran some tests a few months ago bby developping some widget on the computer where the tango-db was launched and TangoTest device ran.
Now, I would like to use TangoTest running launched on a distant computer with a tango-db running on a distant server.
I defined TANGO_HOST value to "server:port", and I would like to know what else should be defined to access to attributes of the distant TangoTest.
Currently, launching `doc/source/devel/examples/label01.py` only prints a window without any value.

Thank you.

**Comment by PhilLAL** [comment]
By the way, I checked that the TangoTest DS is registered on the DB and is running (it runs on the tango server).

For the test you suggest with DataBaseds, launching `taurusform sys/database/2` on the client displays the following windows:
![1st window](https://owncloud.lal.in2p3.fr/index.php/s/7efsPGGY6xkBYSb)
and when clicking Ok
![2d window](https://owncloud.lal.in2p3.fr/index.php/s/iDnvuHKKoHCaK8Z)

If I try to launch atkpanel, I got the following error:
```
Cannot connect to the device.
Check the device name you entered; Application will abort ...
Connection Exception : Severity: PANIC
Origin: Connection.dev_import(sys/database/2)
Description: Cannot import sys/database/2 : 
org.omg.CORBA.TRANSIENT: Retries exceeded, couldn't reconnect to [192.168.PRIVATE_IP]:20000 vmcid: 0x0 minor code: 0 completed: No
Reason: TangoApi_CANNOT_IMPORT_DEVICE
Severity: ERROR
Origin: Connection.build_connection(sys/database/2)
Reason: TangoApi_CANNOT_IMPORT_DEVICE
```
I understand this is more a network issue related to the fact that this server has 2 IP and [192.168.PRIVATE_IP] is the one not accessible from the client.

**Comment by cpascual** [comment]
Can't see the images, but yes, I think that this is probably not a taurus-related issue, but a Tango one. Maybe you could ask in the tango-controls forum

**Comment by PhilLAL** [comment]
For information, the subject has been created here: http://www.tango-controls.org/community/forum/c/general/installation/accessing-devices-running-on-a-two-server-interfaces/?page=1#post-2874
