### ISSUE TITLE
API 'QString' has already been set to version 1

### ISSUE THREAD

**Issue by Aratar93** [taurus-org/taurus#613]
Hi all,

When I want to run python file, which was created from ui file, I get next message:

`Traceback (most recent call last):`
`  File "GalenikaGUI.py", line 3, in <module>`
`    import GUI`
`  File "/home/rile/TaurusProjects/GUI.py", line 816, in <module>`
`    from taurus.qt.qtgui.button import TaurusLauncherButton`
`  File "/usr/local/lib/python2.7/dist-packages/taurus/qt/__init__.py", line 30, in <module>`
`    from taurus.external import qt as __qt`
`  File "/usr/local/lib/python2.7/dist-packages/taurus/external/qt/__init__.py", line 102, in <module>`
`    sip.setapi('QString', 2)`
`ValueError: API 'QString' has already been set to version 1`

How can I solve this problem? I've never had this kind of problem before.

P.S. I've got python file from ui file using command
`pyuic4 -o DHTSensor.py DHTSensor.ui`

**Comment by almarass** [comment]
I got the same problem after having upgraded taurus version to 4.1.1
