### ISSUE TITLE
Problem with % sign

### ISSUE THREAD

**Issue by Aratar93** [taurus-org/taurus#614]
Hi all,

I am measuring humidity, which is represented with %.  
But when I run GUI created by taurus designer, this is what I get as warning:
`MainThread     WARNING  2017-11-13 16:10:56,271 dusanDell:10000.tango/dht/1.Humidity: Unknown` `unit "% (will be treated as unitless)"`
and % is not shown. So, instead of getting something like 47.5%, I get 47.5.
Is there anything I could do, so that % would become visible?

Best regard

**Comment by cpascual** [comment]
I am rejecting this issue as a duplicate of #596 
@Aratar93 , please refer to info in #596, and post there if you need any further help/clarification.
