### ISSUE TITLE
Add text to TaurusLabel

### ISSUE THREAD

**Issue by hayg25** [taurus-org/taurus#619]
Hello, 
We encounter an issue concerning TaurusLabel. the methods setText seems to have no effect on TaurusLabel and setPermanentText seems to be unknown ... 
Is there a way to make the text visible somewhere ? 

Cheers

**Comment by cpascual** [comment]
Hi @hayg25 : Can you explain what are you trying to achieve exactly?

In principle the text of a TaurusLabel is expected to be dynamic and controlled by its model...

**Comment by hayg25** [comment]
Hi @cpascual thanks for your answer I was just exploring the different classes and was wondering what should that setText was suppose to do for TaurusLabel. I was expecting something like if the model does not provide its dynamic text (like tango server not accessible), it puts a replacement text like (tango off).

**Comment by cpascual** [comment]
Ok. Then the answer is that the setText  method in TaurusLabel is inherited from its base Qt class (QLabel). In the case of TaurusLabel, it is internally called when a Taurus event from the model is handled, and therefore is not meant to be used directly.

**Comment by cpascual** [comment]
I am closing the question. Feel free to reopen if you need further info

Cheers.
