### ISSUE TITLE
loadUi with taurus

### ISSUE THREAD

**Issue by PhilLAL** [taurus-org/taurus#622]
I tried to create a TaurusWidget with taurusdesigner and it is not clear how to load the ui file.

Once saved into a .ui (into ui subdirectory), I try to load it in a .py following steps described into https://github.com/cpascual/pythoncourse-intermediate/tree/master/exercises but it does not seems to work.
Since it does not work, I tried to check with a valid example found into https://github.com/cpascual/pythoncourse-intermediate/blob/master/exercises/cheat/taurusexercise1.py and https://github.com/cpascual/pythoncourse-intermediate/blob/master/exercises/cheat/ui/TaurusExercise1Widget.ui
It works.

When I go back to my personnal ui, one difference is I did not set again setModel into .py since I set all of them into taurusdesigner.
Do I still need to set them into onShow() in file .py? ie.e is it needed to set them into taurusdesigner? 
(It seems working defining setModel into taurusdesigner since Ctrl-R allow to see a demo of the ui which works)

Do I need to define signals in the .py (`self.pushButton.clicked.connect(self.onShow)`) if I did not define signals into taurusdesigner?

**Comment by PhilLAL** [comment]
Ok, we found how to do this. I give a few tips for readers for which it could be helpful:
- setModel can be done in the .ui (perhaps it not good practice)
- some modifications are needed in the example https://github.com/cpascual/pythoncourse-intermediate/blob/master/exercises/cheat/taurusexercise1.py : 
  * `from taurus.qt.qtgui.container import TaurusWidget` sjould be added in header 
  * `class TaurusExercise1Widget(QtGui.QWidget):` should be replaced by class TaurusExercise1Widget(TaurusWidget):`

**Comment by cpascual** [comment]
> setModel can be done in the .ui (perhaps it not good practice)

You are right: in principle it is allowed, but I usually recommend *not* to do it. The reasons are:
- It may be dangerous if you connect to some critical equipment and you change settings while designing
- We have seen some stability issues in some widgets when working in the designer and receiving events (these are bugs)

**Comment by PhilLAL** [comment]
Thank you for these precisions. :)

**Comment by cpascual** [comment]
> - `from taurus.qt.qtgui.container import TaurusWidget` should be added in header
> - `class TaurusExercise1Widget(QtGui.QWidget):` should be replaced by class 

I do not see why those changes are needed. The example works fine for me as it is

**Comment by cpascual** [comment]
Since the original question seems solved, I am closing this. Feel free to reopen if you need further discussion.

**Comment by PhilLAL** [comment]
Sorry, you're right, getting back to the code, it seems to work now. :)
I probably used a bad version.
