### ISSUE TITLE
"attribute not found" when modifying attribute name of model into taurusdesigner

### ISSUE THREAD

**Issue by PhilLAL** [taurus-org/taurus#625]
Hi,
I found I can set model into taurusdesigner, but I think remembering reading somewhere to set model in a python file.
Perhaps it is the reason taurusdesigner froze when I tried to change an attribute into model of a Taurus element using taurisdesigner by deleting characters and then adding new ones:
```
TaurusTP.W004  DEBUG    2017-11-17 18:00:08,250 tango-util:20000.sys/tg_test/1.double_scalar_: [Tango] read failed (API_AttrNotFound): double_scalar_ attribute not found
TaurusTP.W004  DEBUG    2017-11-17 18:00:08,250 tango-util:20000.sys/tg_test/1.double_scalar_: Error polling: double_scalar_ attribute not found
TaurusTP.W005  DEBUG    2017-11-17 18:00:08,594 tango-util:20000.sys/tg_test/1.double_scalar_r: [Tango] read failed (API_AttrNotFound): double_scalar_r attribute not found
TaurusTP.W005  DEBUG    2017-11-17 18:00:08,594 tango-util:20000.sys/tg_test/1.double_scalar_r: Error polling: double_scalar_r attribute not found
TaurusTP.W001  DEBUG    2017-11-17 18:00:08,870 tango-util:20000.sys/tg_test/1.double_scalar_rw: [Tango] read failed (API_AttrNotFound): double_scalar_rw attribute not found
TaurusTP.W001  DEBUG    2017-11-17 18:00:08,870 tango-util:20000.sys/tg_test/1.double_scalar_rw: Error polling: double_scalar_rw attribute not found
```
Then taurusdesigner froze without letting me adding the last w to get the correct `sys/tg_test/1.double_scalar_rw` attribute.
It seems the value into model textbox into taurusdesigner is evaluated at each change and so one should replace by a valid attribute instead of erasing characters and then adding characters to get the new attribute.
Do you confirm there is no other way to avoid the bug?

**Comment by cpascual** [comment]
I think that what you describe is *the way to trigger* the bug, but not the bug itself. IMHO all taurus widgets should support to fail nicely when it is given a wrong model name (and therefore the messages you see **should** be harmless).

Unfortunately this is not always the case. Some widgets behave badly (some are even seen to segfault) when given a problematic model name. IMHO *that* is the actual root of the problem.

We have seen also stability issues when a widget is handling taurus events within TaurusDesigner.

For all this I usually recommend *not* to set models in the designer, and do it programmatically instead.

I am closing this as an answered question, and opening a more explicit bug: #630

**Comment by PhilLAL** [comment]
Ok, that is what I suspected in https://github.com/taurus-org/taurus/issues/622#issuecomment-345300548
Thank you for this explanation.
