### ISSUE TITLE
TaurusLabel: allow to represent *tango* states as background

### ISSUE THREAD

**Issue by srgblnch** [taurus-org/taurus#626]
Setting the model of a TaurusLabel to a DevState attribute of a tango device, with the bgRole configured to represent the state, it doesn't change to blue in case of a running state. But very worst case when the state is fault, because then it shows a text "FAULT" in a green background.

If I understood correctly, it seems taurus4 is only supporting 3 TaurusDevState (Ready, NotReady and Unknown). Like there is a TangoAttribute that inherits from TaurusAttribute and give the details when it point to a tango attribute, there have to be a TangoDevState that inherits from TaurusDevState and encapsulates this behaviour.

**Comment by srgblnch** [comment]
Ok, that's an step. But what about the other states? Why fault is mapped and not the others?

I've tried a bypass using a TaurusLed because there is still a LedMap in the "taurusled.py". But it is affected also, in taurus4 is shown a black led when the state is running.

I would desire the same behaviour that taurus3 while the model is a tango attribute, but I can live with an alternative recipe. With what I cannot live is without any way to report the user with some coloured codification.

**Comment by cpascual** [comment]
Hi @srgblnch ,

We just proposed a PR (#629) that solves your need. When it is integrated you will be able  to emulate the behaviour of Taurus3 state labels,  by setting the model to a state and the bgRole to `rvalue` (see example in #629)

**Comment by cpascual** [comment]
And just for the record:

setting  bgRole='state' dispplays *Taurus* device states: Ready (green) , NotReady (red), Unknown (gray)

The *Tango* device states are only supported for backwards compatibility, and only if Tango is installed.

**Comment by cpascual** [comment]
Update: I just realised that you do not need #629 for this to work.
It is already possible (even in the stable release) to set the bgRole to `"value"` and get the same effect.
I actually recommend this since I marked the new API from #629 as experimental

**Comment by cpascual** [comment]
Given that the requirement is already fulfilled, I tag this as "question", I rephrase the title and I close it as solved.

**Comment by cpascual** [comment]
Note, just for completion: the above recipe of setting `value` as the bgRole for showing the tango state background,  works only if the attribute being shown is the `state`. But with the experimental API from #629 , one can show the tango state in the background **even if the model of the label is not state**. This is done by using `label.setBgRole('parentObj.stateObj.rvalue')`
