### ISSUE TITLE
Avoid triggering TaurusConsole deprecation Warning internally

### ISSUE THREAD

**Issue by PhilLAL** [taurus-org/taurus#637]
Hello, 
when using taurusgui, I noticed that an exception appears when adding every panel.

```
$> taurusgui --new-gui
MainThread     INFO     2017-12-06 13:07:16,079 TaurusRootLogger: Using "PyQt4" for Qt
MainThread     INFO     2017-12-06 13:07:16,169 taurus.qt.qtgui.icon.icon: Setting Tango icon theme (from /home/gauron/.local/lib/python2.7/site-packages/taurus/qt/qtgui/icon/)
MainThread     INFO     2017-12-06 13:07:16,191 TaurusRootLogger: Starting execution of TaurusGui
MainThread     WARNING  2017-12-06 13:07:41,761 TaurusRootLogger: /home/gauron/.local/lib/python2.7/site-packages/taurus/qt/qtgui/util/tauruswidgetfactory.py:111: DeprecationWarning: TaurusConsole is deprecated since 4.0.4. Use silx.gui.console.IPythonWidget instead
  m = __import__(module_name, fromlist=['*'], level=0)

Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
```

This output was after 1st panel adding.
This is nothing serious since it seems to work apart of this message.

**Comment by cpascual** [comment]
Hi, I could not reproduce it. Does it happen when adding some specific panel?

I tried adding a TaurusForm and a synoptics view and did not get the `Error in sys.excepthook:`.

Can you please provide more detailed step-by-step way of reproducing?

**Comment by cpascual** [comment]
Also, please try to see if there are more verbose messages in the console when adding the `--taurus-log-level=trace` argument to the `taurusgui` command

**Comment by PhilLAL** [comment]
Hello Carlos, I encounter this behaviour on a GNU/Linux configuration each time I click on "Add Panel" button, before choosing the type of Panel.

For precision, here are the steps I followed:
- put python modules into DIRECTORY
- check that `taurusgui` is into $PATH and DIRECTORY is into $PYTHONPATH
- launch `taurusgui --new-gui`
- select the directory where I want to store my GUI
- name my GUI and my Organization
- choose a logo
- continue until `Add panel` button
    * enter a name for `Panel name`
    * ented the name of the python file (without `.py`)
    * select the module class I want to use into Taurus GUI
    * click on `Finish`
    * begin again for every module I want to use
- once every modules added into the GUI, select "next" until "finish"
- install with `pip install --user`
- launch with the name given into `wizard.log`

When launched with `--taurus-log-level=trace` option, I got the following output:
```
taurusgui --new-gui --taurus-log-level=trace
MainThread     INFO     2017-12-11 17:37:18,781 TaurusRootLogger: Using "PyQt4" for Qt
MainThread     INFO     2017-12-11 17:37:18,869 taurus.qt.qtgui.icon.icon: Setting Tango icon theme (from /home/gauron/.local/lib/python2.7/site-packages/taurus/qt/qtgui/icon/)
MainThread     INFO     2017-12-11 17:37:18,892 TaurusRootLogger: Starting execution of TaurusGui
MainThread     TRACE    2017-12-11 17:37:18,966 TaurusManager: reInit()
MainThread     DEBUG    2017-12-11 17:37:18,966 TaurusManager.TaurusTP: Starting TaurusTP.W001
MainThread     DEBUG    2017-12-11 17:37:18,966 TaurusManager.TaurusTP: Starting TaurusTP.W002
MainThread     DEBUG    2017-12-11 17:37:18,966 TaurusManager.TaurusTP: Starting TaurusTP.W003
MainThread     DEBUG    2017-12-11 17:37:18,967 TaurusManager.TaurusTP: Starting TaurusTP.W004
MainThread     DEBUG    2017-12-11 17:37:18,967 TaurusManager.TaurusTP: Starting TaurusTP.W005
MainThread     DEBUG    2017-12-11 17:37:18,968 TaurusApplication: Failed to load sardana extensions
Traceback (most recent call last):
  File "/home/gauron/.local/lib/python2.7/site-packages/taurus/qt/qtgui/application/taurusapplication.py", line 263, in __registerExtensions
    import sardana.taurus.qt.qtcore.tango.sardana
ImportError: No module named sardana.taurus.qt.qtcore.tango.sardana
MainThread     DEBUG    2017-12-11 17:37:18,970 TaurusManager: Found plugin EvaluationFactory
MainThread     DEBUG    2017-12-11 17:37:18,971 TaurusManager: Found plugin ResourcesFactory
MainThread     DEBUG    2017-12-11 17:37:18,971 TaurusRootLogger: cannot import epics module. Taurus will not support the "epics" scheme
MainThread     DEBUG    2017-12-11 17:37:18,971 TaurusRootLogger: cannot import epics module. Taurus will not support the "epics" scheme
MainThread     DEBUG    2017-12-11 17:37:18,971 TaurusManager: Failed to inspect taurus.core.epics
MainThread     DEBUG    2017-12-11 17:37:18,971 TaurusManager: Details:
Traceback (most recent call last):
  File "/home/gauron/.local/lib/python2.7/site-packages/taurus/core/taurusmanager.py", line 343, in _get_plugin_classes
    globals(), locals(), ['*'])
  File "/home/gauron/.local/lib/python2.7/site-packages/taurus/core/epics/__init__.py", line 70, in <module>
    from epicsfactory import *
  File "/home/gauron/.local/lib/python2.7/site-packages/taurus/core/epics/epicsfactory.py", line 34, in <module>
    import epics
ImportError: No module named epics
MainThread     DEBUG    2017-12-11 17:37:18,972 TaurusManager: Found plugin TangoFactory
```
and when I click on "Add Panel" button, I got 
```
MainThread     WARNING  2017-12-11 17:37:55,447 TaurusRootLogger: /home/gauron/.local/lib/python2.7/site-packages/taurus/qt/qtgui/util/tauruswidgetfactory.py:111: DeprecationWarning: TaurusConsole is deprecated since 4.0.4. Use silx.gui.console.IPythonWidget instead
  m = __import__(module_name, fromlist=['*'], level=0)
```

**Comment by cpascual** [comment]
OPh, my fault, I think I misunderstood the original report.

I understand now that you refer to **this** message, right?:

`MainThread     WARNING  2017-12-11 17:37:55,447 TaurusRootLogger: /home/gauron/.local/lib/python2.7/site-packages/taurus/qt/qtgui/util/tauruswidgetfactory.py:111: DeprecationWarning: TaurusConsole is deprecated since 4.0.4. Use silx.gui.console.IPythonWidget instead
  m = __import__(module_name, fromlist=['*'], level=0)`

If it is so, do not worry. It is not an exception, but just a *deprecation warning*. 

In principle the warning should be there just to alert any *external* users trying to use the TaurusConsole that they should change it, but we are *internally* triggering it in, at least, the factory.

It is not serious but IMHO we should try to avoid triggering the warning *internally* in Taurus, to avoid confusion, so I am going to leave this issue open (with edited title) as a reminder.

**Comment by PhilLAL** [comment]
Sorry, I did not succeed into making appear again `Error in sys.excepthook:`
For the warning, indeed, this is not a problem.

**Comment by cpascual** [comment]
I am reopening in order to remind about avoiding to trigger the warning internally

**Comment by cpascual** [comment]
#782 fixes this
