### ISSUE TITLE
checking dependencies under Windows

### ISSUE THREAD

**Issue by PhilLAL** [taurus-org/taurus#639]
Hello,
I tried to install taurus under windows with a colleague today, and here are some issues I encountered : 
 - numpy version too old 
```RuntimeError: module compiled against API version 0xa but this version of numpy is 0x9```
This issue was due to a too old version of numpy and has been easlily solved by a `python install --upgrade numpy`
- numpy dependencies 
```
python -c "import taurus; taurus.check_dependencies()"
Dependencies for taurus 4.1.1:
        [*] numpy>=1.1

Extras:
Dependencies for taurus[taurus_epics]:
        [*] numpy>=1.1
Dependencies for taurus[taurus_h5file]:
        [*] numpy>=1.1
Dependencies for taurus[taurus_qt]:
        [*] numpy>=1.1
Dependencies for taurus[taurus_tango]:
        [*] numpy>=1.1
```

These dependencies all cites module `numpy>=1.1` instead of the real module name.
I suppose there is an issue with windows taurus version, I can give more tests results tomorrow.

**Comment by PhilLAL** [comment]
I add that it seems a bit strange since the output is shorter than under GNU/Linux which is on my laptop:
```
python -c 'import taurus; taurus.check_dependencies()'
Dependencies for taurus 4.1.1:
	[*] numpy>=1.1

Extras:
Dependencies for taurus[taurus-epics]:
	[*] numpy>=1.1
	[*] pyepics>=3.2.4; extra == "taurus-epics"
Dependencies for taurus[taurus-h5file]:
	[*] numpy>=1.1
	[*] h5file; extra == "taurus-h5file"
Dependencies for taurus[taurus-qt]:
	[*] numpy>=1.1
	[*] guiqwt>=3; extra == "taurus-qt"
	[*] spyder>=3.0; extra == "taurus-qt"
	[*] qtpy>=1.2.1; extra == "taurus-qt"
	[*] lxml>=2.1; extra == "taurus-qt"
	[*] ply>=2.3; extra == "taurus-qt"
	[*] PyQt4>=4.8 (not in PyPI)
	[*] PyQt4.Qwt5>=5.2 (not in PyPI)
Dependencies for taurus[taurus-tango]:
	[*] numpy>=1.1
	[*] PyTango>=7.1; extra == "taurus-tango"
```

**Comment by cpascual** [comment]
> numpy version too old

I think that this is a specific installation issue, not directly Taurus-related

> numpy dependencies (...) These dependencies all cites module numpy>=1.1 instead of the real module name.

What do you mean? 
"numpy" is the real module name. And the ">=1.1" is the actual required minimum version (i.e. the check just means that you have numpy and that its version is above 1.1

Unless I am missing the point, I think it is all ok.

**BUT**, as a related note, keep in mind that Taurus version 4.1.1 (the one that you are using) is likely affected by the bug #612 (which was fixed by the PR #615 for Taurus version 4.1.2a0). Please try again with the latest version in the develop branch.

**Comment by PhilLAL** [comment]
Ok, I was misleaded by the on-line output for each dependency (taurus_epics, taurus_h5file, taurus_qt, taurus_tango) and I forgot that the PR was not included into the stable version.
We'll try this, thank you for these details!

**Comment by PhilLAL** [comment]
Hi again,
we just installed last dev version under Windows 10. 

As a reminder, we initially had some dependencies not installed after installing python(x,y) and taurus.

Installation of last dev version allowed us to check missing dependencies with `taurus.check_dependencies()`.
Perhaps I missed some information but as a first analysis, windows installation with last python(x,y) (v2.7.10.0) still needs some installation.
Here are the steps we followed to make taurus work: 
- pip install qtpy
- pip install PythonQwt
- pip install --upgrade guiqwt spyder

**Comment by cpascual** [comment]
> windows installation with last python(x,y) (v2.7.10.0) still needs some installation.

Yes, you are right. I think the "installation" docs need updating.

If you have a fresh windows machine at hand, it would be very helpful if you confirm that the following instructions are ok in that system:

- install python(x,y)
- pip install taurus[taurus-qt]

**Comment by PhilLAL** [comment]
We did not start again from scratch but if the goal is to confirm this command works, we launched it once all steps formerly described already followed.
Here is the output: 
```
$> pip install taurus[taurus-qt]
Requirement already satisfied: taurus[taurus-qt] in c:\users\dalifard\documents\taurus\dev\taurus-develop\lib
Requirement already satisfied: numpy>=1.1 in c:\python27\lib\site-packages (from taurus[taurus-qt])
Requirement already satisfied: qtpy>=1.2.1 in c:\python27\lib\site-packages (from taurus[taurus-qt])
Requirement already satisfied: ply>=2.3 in c:\python27\lib\site-packages (from taurus[taurus-qt])
Requirement already satisfied: lxml>=2.1 in c:\python27\lib\site-packages (from taurus[taurus-qt])
Requirement already satisfied: guiqwt>=3 in c:\python27\lib\site-packages (from taurus[taurus-qt])
Requirement already satisfied: Pillow in c:\python27\lib\site-packages (from guiqwt>=3->taurus[taurus-qt])
Requirement already satisfied: guidata>=1.7.0 in c:\python27\lib\site-packages (from guiqwt>=3->taurus[taurus-qt])
Requirement already satisfied: SciPy>=0.7 in c:\python27\lib\site-packages (from guiqwt>=3->taurus[taurus-qt])
Requirement already satisfied: PythonQwt>=0.5.0 in c:\python27\lib\site-packages (from guiqwt>=3->taurus[taurus-qt])
Requirement already satisfied: olefile in c:\python27\lib\site-packages (from Pillow->guiqwt>=3->taurus[taurus-qt])
```

**Comment by cpascual** [comment]
Thanks, but I want to test from scratch. If no one tests it before, we will try this as part of the release tests for the Jan18 milestone

**Comment by cpascual** [comment]
I just tried on a fresh win7 virtual machine and it seems to be ok:

![image](https://user-images.githubusercontent.com/4115224/33934416-1fd6ea20-dff9-11e7-90fd-5271a5a16bc1.png)
