### ISSUE TITLE
Units shown everywhere

### ISSUE THREAD

**Issue by mkomel** [taurus-org/taurus#652]
I was trying out the code from "_Display attribute value with label and separate units_" from the _Examples_ part of the documentation. It shows how a label, a value and a unit can be neatly displayed in three separate horizontally laid TaurusLabels:
![screenshot_2](https://user-images.githubusercontent.com/34713171/34210316-bcf4f864-e595-11e7-8329-5684c16d1d16.png)

Unfortunately, this does not work in TaurusQT 4.1.1. The result is as can be seen in this screenshot:
![screenshot](https://user-images.githubusercontent.com/34713171/34210114-fdb555d4-e594-11e7-9d15-ed95afc82613.png)

It seems that TaurusQT completely ignores model notations, such as #label, #rvalue.magnited, #rvalue.units, as in:
 ```
      w1.model, w1.bgRole = 'sys/taurustest/1/position#label', ''
      w2.model = 'sys/taurustest/1/position#rvalue.magnitude'
      w3.model, w3.bgRole = 'sys/taurustest/1/position#rvalue.units', ''
```

**Comment by cpascual** [comment]
I just tested and  the example works well for me. More explicitly, when I run the following snippet:

```python
import sys
from taurus.external.qt import Qt
from taurus.qt.qtgui.application import TaurusApplication
from taurus.qt.qtgui.display import TaurusLabel

app = TaurusApplication(sys.argv)
panel = Qt.QWidget()
layout = Qt.QHBoxLayout()
panel.setLayout(layout)

w1, w2, w3 = TaurusLabel(), TaurusLabel(), TaurusLabel()
layout.addWidget(w1)
layout.addWidget(w2)
layout.addWidget(w3)
w1.model, w1.bgRole = 'sys/taurustest/1/position#label', ''
w2.model = 'sys/taurustest/1/position#rvalue.magnitude'
w3.model, w3.bgRole = 'sys/taurustest/1/position#rvalue.units', ''

panel.show()
sys.exit(app.exec_())
```

I get the following:
![image](https://user-images.githubusercontent.com/4115224/34211683-2920555c-e59a-11e7-9676-8b2064e73ee9.png)


Note: I checked both with taurus 4.1.1 and the current develop version

**Comment by mkomel** [comment]
Ok, I tried this again, now using the newer (release candidate) TangoBox 9.2, and it works fine there.

Previously I was using TangoBox 9.1 (with TaurusQt upgraded to 4.1.1 by: pip install --upgrade taurus)
Not sure what is the reason for odd behaviour in TangoBox 9.1, one possibilty is due to different PyTango versions (TangoBox 9.1 has PyTango 8.1.2, while TangoBox 9.2 uses a newer version).

Thanks for trying to reproduce this!

**Comment by cpascual** [comment]
Glad to know it works .

Note: regarding the cause for the odd behaviour, I would not blame PyTango... it should work well with old PyTango (>= 7.1). It rather looks to me as if you were inadvertently using an old version of taurus (<4).
