### ISSUE TITLE
TaurusValueComboBox does not change color

### ISSUE THREAD

**Issue by mkomel** [taurus-org/taurus#660]
TaurusValueComboBox does not change color when displayed value differs from applied value.

Other widgets, for example TaurusValueLineEdit, have this nice feature that the foreground color in such cases changes to blue, like this:
<img width="107" alt="screenshot" src="https://user-images.githubusercontent.com/34713171/34302361-bdf474d2-e730-11e7-9b69-0dacffc927b7.png">

Is there any simple trick to make this happen on TaurusValueComboBox or is this feature missing there?

I'm using TaurusQt 4.1.1

**Comment by cpascual** [comment]
I thought that the taurusvaluecombobox changed to bold blue text when there are pending operations... but maybe it was never implemented... in any case, I think that it would be nice and not too hard to implement.

**Comment by mkomel** [comment]
It seems that setting the foreground color via setStyleSheet (as is currently done in tauruscombobox.py, line 127) does not work correctly, probably due to some bug in Qt.
The (somewhat awkard) workaround seems to be to also set the padding property, as mentioned here in the accepted answer:
https://stackoverflow.com/questions/24447276/qcombobox-text-colour-wont-change-with-style-sheet

By doing this in tauruscombobox.py it actually works. Line 127, instead of:
    self.setStyleSheet('TaurusValueComboBox {color: blue; }')
do this:
    self.setStyleSheet('TaurusValueComboBox {color: blue; padding: 2px 4px }')

Padding values can be any values. Values 2px and 4px are just the ones that work nice in my environment. Obviously this is not a good overall solution, since in other environments it might look different.


But at least what can be done here is to treat font-weight the same as other widgets, like TaurusValueLineEdit, do. There font-weight is set to bold (in addition to setting the color to blue) when displayed value differs from applied value. This then means changing tauruscombobox.py, line 127, to:
    self.setStyleSheet('TaurusValueComboBox {color: blue; font-weight: bold; }')

**Comment by cpascual** [comment]
Nice find @mkomel !
Would you mind creating a Pull Request with the required change (I would say that using bold is the way to go)?
If you are not familiar with PRs, do not worry, I can do it myself.

**Comment by mkomel** [comment]
I have created a PR #661 , I hope it is fine..

**Comment by cpascual** [comment]
Fixed by #661
