### ISSUE TITLE
TaurusValueLineEdit does not allow to delete value

### ISSUE THREAD

**Issue by mbroseta** [taurus-org/taurus#667]
The way to reproduce is simple:
1- open a taurus form with a Read/write attribute with units
2- Put the cursor at the end of the write widget and try to delete the units.

It is not possible to delete the units.

3. Selecting all the value+units and pressing "SUPR" has no effect

Moreover

4- Pressing twice "DEL" the current value is restored

Taurus version: 4.3.0-alpha

Manolo

**Comment by cpascual** [comment]
I confirm the issue, but with the following precisions:
- It has nothing to do with units. The same behaviour can be observed with an attribute without units.
- It can be reproduced with a stand-alone TaurusValueLineEdit: 

```python
from taurus.qt.qtgui.application import TaurusApplication
from taurus.qt.qtgui.input import TaurusValueLineEdit

if __name__ == '__main__':
    import sys
    app = TaurusApplication()

    w = TaurusValueLineEdit()

    model = 'sys/tg_test/1/short_scalar_w'
    w.setModel(model)

    w.show()
    sys.exit(app.exec_())
```

**Comment by cpascual** [comment]
The problem was introduced with the merge of #650.
