### ISSUE TITLE
Model Chooser does not respect Case sensitivity of models when editing the list (double-click)

### ISSUE THREAD

**Issue by guifrecuni** [taurus-org/taurus#668]
Hi, I found an issue when trying to change models using Model Chooser (both in TaurusForm and TaurusTrend applications).

You can reproduce it by:
1) Run TaurusForm with models that contain upper- and lower-case letters like:
taurusform 'eval:"AbCd"' sys/database/2/StoredProcedureRelease

2) right-click to open context menu, and select the "Modify Contents" option to open the Model Chooser

3) doubleclick on any model in the list to modify it

**Comment by cpascual** [comment]
Confirmed

**Comment by cpascual** [comment]
The problem is caused by the following line in `TaurusForm.chooseModels()`:

```python
models = [m.lower() for m in self.getModel()]
```

This is done in order to ensure a unique ID in the case of case-insensitive models.
A better solution could be implemented if #779 is implemented

**Comment by cpascual** [comment]
PR #780 has been done to fix this issue (independently of #779)
