### ISSUE TITLE
taurusdesigner does not change text of TaurusCommandButton correctly

### ISSUE THREAD

**Issue by CorF4** [taurus-org/taurus#670]
Hello,
I noticed that using the taurusdesigner doesn't change the text on the TaurusCommandButton. The user can enter a text below the panel named QAbstractButton. The produced .ui-file  uses a field with 
<property name="text">
<string>Some text <\string>
<\property>

It should rather produce a property with name="customText".
Since I couldn't find where the ui-file is built I was not able to detect the bug inside the code...
Thanks for any hints/help.

**Comment by cpascual** [comment]
Hi @CorF4 ,

Note that the property "text" that you are changing corresponds to the setText method of the base class QAbstractButton.
If you want to access the TaurusButton.setCustomText method instead, you should modify the "customText" property under the  TaurusCommandButton property list (near the bottom in the property editor of designer when you select the command button).

Also note that the TaurusCommandButton will automatically use the command name (defined in the "Command" property) as its text if customText is not defined.

Does this solve your issue?

**Comment by CorF4** [comment]
Hi, yes thanks! I missed that option!
Than this is fine now.
