### ISSUE TITLE
tangogui add custom panel 

### ISSUE THREAD

**Issue by pierreH23** [taurus-org/taurus#671]
Hello !
I'm a Tango Controls newbie and I'm trying to write some simple control panels with Taurus. 
Precisely, I aim to extend 'taurusgui' by adding my own panel.
When I choose 'New Panel, Other' I'd like to have the opportunity to select my own simple solo widget (wrote from scratch in Python or in Python+Designer) as module. 
For instance, how a Taurus example (http://taurus-scada.org/en/latest/devel/examples.html) can become a module listed in 'taurusgui' ?
Many thanks
Pierre Héricourt
CELIA/CNRS
Université Bordeaux / France

**Comment by cpascual** [comment]
Hi @pierreH23, and welcome!
Please have a look at #634, since I think that your question is more or less the same.

**Comment by pierreH23** [comment]
Hi,
I just found this doc 
http://www.taurus-scada.org/en/latest/devel/api/taurus/qt/qtgui/taurusgui/_TaurusGui.html#taurus.qt.qtgui.taurusgui.TaurusGui
With your post I have now all the tools
Thanks
Pierre
