### ISSUE TITLE
TaurusGrid seems to be broken

### ISSUE THREAD

**Issue by mkomel** [taurus-org/taurus#675]
When I try to use the TaurusGrid (TaurusQT 4.1.1) I get the following error:

> File "/usr/local/lib/python2.7/dist-packages/taurus/qt/qtgui/table/taurusgrid.py", line 886, in build_widgets
>     synoptic_value.itemClicked.connect(self.itemClicked)
> AttributeError: 'TaurusValue' object has no attribute 'itemClicked'

Even if I run the "unit test" of the taurusgrid.py itself:
`python taurusgrid.py "model=lt.*/VC.*/.*/((C*)|(P*)|(I*))" cols=IP,CCG,PNV rows=LT01,LT02 others=False rowframe=True colframe=False`
I get a little different, but similar error:

> Traceback (most recent call last):
>   File "taurusgrid.py", line 1015, in <module>
>     gui.setModel(args['model'])
>   File "taurusgrid.py", line 439, in setModel
>     self.create_widgets_table(self._modelNames)
>   File "taurusgrid.py", line 704, in create_widgets_table
>     self.table = self.build_table(values)
>   File "taurusgrid.py", line 845, in build_table
>     widgets_matrix = self.build_widgets(values, self.showLabels)
>   File "taurusgrid.py", line 907, in build_widgets
>     cell_frame.itemClicked.connect(self.itemClicked)
> AttributeError: 'QFrame' object has no attribute 'itemClicked'

**Comment by cmft** [comment]
Hi @mkomel , 
I confirm the bug,
Thanks to report it

**Comment by dvucko** [comment]
TaurusGrid starts to work if you comment out two problematic lines in `taurusgrid.py`:
- line 886: `synoptic_value.itemClicked.connect(self.itemClicked)`
- line 907: `cell_frame.itemClicked.connect(self.itemClicked)`

The following test works normally as well after this: `python taurusgrid.py "model=lt.*/VC.*/.*/((C*)|(P*)|(I*))" cols=IP,CCG,PNV rows=LT01,LT02 others=False rowframe=True colframe=False`

Can someone confirm if these changes could cause some unforeseen side effects?

**Comment by dvucko** [comment]
This bug has been resolved in taurus 4.3.0. I think this can be closed.

**Comment by cpascual** [comment]
Thanks for the info!
