### ISSUE TITLE
Win7: taurusplot and taurustrend: zoom back is applied when doing right click

### ISSUE THREAD

**Issue by mrosanes** [taurus-org/taurus#710]
Win7: taurusplot and taurustrend -> zoom back is applied when doing right click.

Right click should be used to find the contextual menu and no zoom should be applied, however a zoom back is applied when doing right click, and sometimes is reducing the curves to much, lowering the quality of the user experience.

**Comment by cpascual** [comment]
This affects to the qwt5-based widgets which are now deprecated, so I am closing as "wontfix"
