### ISSUE TITLE
Win7 Taurus4.3: check_dependencies does not detect spyder >3 in some occasions

### ISSUE THREAD

**Issue by mrosanes** [taurus-org/taurus#711]
Testing in Win7 with Taurus4.3, with pythonxy installed, and with a subsequent installation of spyder done with:
pip install --upgrade --no-deps spyder,

The version of the installed spyder without dependencies being, 3.2.7 (the import is done correctly from ipython)

The installation is not detected correctly by taurus.check_dependencies()
[ ] spyder>=3

--

Note: if installing with dependencies (again spyder 3.2.7):
pip install --upgrade spyder
Then the installation is detected correctly by taurus.check_dependencies()
[*] spyder>=3

**Comment by tiagocoutinho** [comment]
I don't think this is a bug. Doing `pip install --no-deps spyder` is not the proper way to install spyder. I would say that after this command spyder should not be considered to be installed.

This behaviour seems to be consistent between linux and windows

**Comment by cpascual** [comment]
Agreed. I close as rejected.
