### ISSUE TITLE
TaurusDevicePanel doesn't show commands when device has FAULT state

### ISSUE THREAD

**Issue by MikeFalowski** [taurus-org/taurus#727]
When I want to open a `TaurusDevicePanel` and the device is in FAULT state, the commands don't show up. 
![taurusdevicepanel-fault](https://user-images.githubusercontent.com/25459174/37781984-1f630eb0-2df2-11e8-97fa-a5df60474478.png)

**Comment by cpascual** [comment]
Confirmed. It can be reproduced with TangoTest by using the switch states command to put the Device in fault State and then launching `taurusdevicepanel sys/tg_test/1`  (note that you need to call the init command afterwards to return to the default "running" state).

A little investigation shows that this behaviour seems to have been added **intentionally** in `TaurusCommandsForm`. In its `_updateCommandWidgets` we find:

```python
        if dev is None or dev.state != TaurusDevState.Ready:
            self.debug('Cannot connect to device')
            self._clearFrame()
            return
```

I created a PR #728 with a possible solution, but I would like it to be tested with other devices (not just TangoTest) to check if the proposed solution is safe enough. Please @MikeFalowski try it and comment there.
