### ISSUE TITLE
segmentation fault : “Source file is more recent than executable”

### ISSUE THREAD

**Issue by tcsgmrt** [taurus-org/taurus#730]
Hello all,

I am using PyTango 9.2.2 and taurus 3.7.  I have observed segmentation fault with below logs with GDB python:

**Thread 14 "python" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffa37fe700 (LWP 30705)]
std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::assign (__s=0x7fff98061880 "Not specified", this=0x0)
at /usr/include/c++/5/bits/basic_string.h:1167
warning: Source file is more recent than executable.
1167 traits_type::length(__s));

(gdb) py-bt
Traceback (most recent call first):
(gdb)
Traceback (most recent call first):

(gdb) bt
#0 std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::assign (__s=0x7fff98061880 "Not specified", this=0x0)
at /usr/include/c++/5/bits/basic_string.h:1167
#1 std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::operator= (__s=<optimized out>, this=<optimized out>)
at /usr/include/c++/5/bits/basic_string.h:559
#2 Tango::_AttributeInfoEx::operator= (this=this@entry=0x7fff98061a20, att_5=att_5@entry=0x21ae8f0) at api_util.cpp:1852
#3 0x00007ffff2131a56 in Tango::ZmqEventConsumer::push_zmq_event (this=this@entry=0x21ae0b0,
ev_name="tango://cmsserver1:10000/mnc/cmc/agn6/agnmncstatus.idl5_attr_conf", endian=endian@entry=0 '\000', event_data=…, error=<optimized out>,
ds_ctr=@0x7fff9805f854: 0) at zmqeventconsumer.cpp:2287
#4 0x00007ffff2132c63 in Tango::ZmqEventConsumer::process_event (this=this@entry=0x21ae0b0, received_event_name=…, received_endian=…,
received_call=…, event_data=…) at zmqeventconsumer.cpp:589
#5 0x00007ffff2133f12 in Tango::ZmqEventConsumer::run_undetached (this=0x21ae0b0, arg=<optimized out>) at zmqeventconsumer.cpp:320
#6 0x00007ffff11637e1 in omni_thread_wrapper () from /usr/local/lib/libomnithread.so.4
#7 0x00007ffff7bc16ba in start_thread (arg=0x7fffa37fe700) at pthread_create.c:333
#8 0x00007ffff78f741d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109**

Does this issue is with bits/basic_string.h:1167 version or anything with c library version? 

Thanks,
Hitesh Patel

**Comment by cpascual** [comment]
Hi, it looks like this is a problem with Tango (or one of its dependencies) I would try to contact the Tango issue tracker instead.

Still, if the problem can be consistently triggered with Taurus, please provide more details on how to do it and we can reopen this.

Also: please note that the 3.x branch of taurus is only temporally supported, and mostly for legacy applications. I recommend to switch to taurus >=4

**Comment by tcsgmrt** [comment]
Hi 
For the same query we have created one thread on TANGO control forum, Below is the link for same
http://www.tango-controls.org/community/forum/c/development/python/segmentation-fault-source-file-is-more-recent-than-executable/?page=1#post-3184

Please add your comments on that thread.
Thanks,
TCS, GMRT

**Comment by shysky** [comment]
I have the same problem whit you int QT Creator 5.6.1  ,"Source file is more recent than executable" ; do you fix it?
