### ISSUE TITLE
taurusLabel doen't display the model value if a setText has been done before the setModel

### ISSUE THREAD

**Issue by mbroseta** [taurus-org/taurus#735]
Hi taurus team,

When we use a taurusLabel to display the value of an attribute, first we assign a default text before setting the model. That worked well, but we have observed that in the latest version of taurus 4.3.1-alpha, this is not working and the values of the models are not applied, only the test defined in the setText function.
This can be easily reproduced with this sequence:

import sys
from taurus.qt.qtgui.application import TaurusApplication
from taurus.qt.qtgui.display import TaurusLed, TaurusLabel

app = TaurusApplication(sys.argv)
w = TaurusLabel()
w.setText("99.99")
model = 'sys/tg_test/1/string_scalar'
w.setModel(model)
w.show()
app.exec_()

The value observed after executing, is always "99.99"

BR
Manolo

**Comment by cmft** [comment]
Hola Manolo,
Thanks to report it. I confirm the bug and I created a PR #736 to fix it.
