### ISSUE TITLE
does deleting of Taurus Label remove listener object for that model? 

### ISSUE THREAD

**Issue by tcsgmrt** [taurus-org/taurus#740]
Hi All,

I have create TaurusLabel for dynamic attribute named 'XYZ' and after some time I have deleted that Taurus Label  because scope of that dynamic attribute goes away. The issue I am facing is when I create TaurusLabel for dynamic attribute with  same name (ex - 'XYZ')  which is recreated by server during same instance of GUI application, that label is showing me value of older dynamic attribute instead if new dynamic attribute value because of same name.

As per my knowledge when we create TaurusLabel it call 'addListener' method for that attribute model and if it is already subscribed then nothing will happen. This issue is due to same name of dynamic attribute because when we open new instance of Application the taurus label show updated value as expected.

Can you please tell me how to remove listener attached to TaurusLabel ?

Please let me know if my understanding is wrong.  

Regards,
Hitesh Patel

**Comment by cpascual** [comment]
The **theory** is as follows: the first time a model is needed, the factory creates it (as a singleton) and keeps it alive as long as someone is referencing it (e.g. by listening to it), and it deletes it when nobody is referencing it. 
This means that if you call setModel('a/b/c/d') on a TaurusLabel, a TangoAttribute('a/b/c/d) object will be kept alive for as long as the TaurusLabel exists or until setModel is called on that label with a different model name). But then if you delete the TaurusLabel (or, e.g., if you call  e.g. setModel(None) on it), the TangoAttribute object **should** be automatically destroyed and garbage-collected (assuming that you did not reference the same model on any other widget!).

**But** precisely in the last release (4.3.1), we fixed a long-standing bug (see #511 and #512) which was preventing this automatic destruction. 

So, can you confirm if you are using the latest release?

**Comment by tcsgmrt** [comment]
Thanks for details response.

Currently we are using Taurus 3.7 and we are in progress to switch Taurus 4.3.1 and tango 9.2.5a. I can confirm you after we switch to 4.3.1.

Thanks,
Hitesh Patel

**Comment by cpascual** [comment]
Hi @tcsgmrt I am assuming this is fixed for you. If not, feel free to reopen the issue
