### ISSUE TITLE
taurusdesigner generated UI: ValueError: API 'QString' has already been set to version 1

### ISSUE THREAD

**Issue by almarass** [taurus-org/taurus#743]
Hi,
I tried to build a very simple UI (showing state and 3 float attributes) using taurusdesigner and the command: pyuic4 -x -o tdDS_ui.py tdDS.ui.

Such UI interfaces itself with a device server running locally.

It works perfectly using Taurus 3.7.0, while using Taurus 4.3.1 it does not run and generates the following messages:
Traceback (most recent call last):
  File "tdDS_ui.py", line 62, in <module>
    from taurus.qt.qtgui.display import TaurusLabel, TaurusLed
  File "/usr/local/lib/python2.7/dist-packages/taurus/qt/__init__.py", line 30, in <module>
    from taurus.external import qt as __qt
  File "/usr/local/lib/python2.7/dist-packages/taurus/external/qt/__init__.py", line 102, in <module>
    sip.setapi('QString', 2)
ValueError: API 'QString' has already been set to version 1

I gave a look in the files:
/usr/local/lib/python2.7/dist-packages/taurus/qt/__init__.py
/home/tango-cs/.local/lib/python2.7/site-packages/qtpy/__init__.py
and modified them commenting the sip.setapi() instructions, as follows:

if API in PYQT4_API:
    try:
        import sip
        try:
            #sip.setapi('QString', 2)
            #sip.setapi('QVariant', 2)
            #sip.setapi('QDate', 2)
            #sip.setapi('QDateTime', 2)
            #sip.setapi('QTextStream', 2)
            #sip.setapi('QTime', 2)
            #sip.setapi('QUrl', 2)
            pass

Now the UI starts and works.
I am wondering if there is some installation/dependency problem (I upgraded Taurus using pip).

Any idea?

Thanks

**Comment by cmft** [comment]
Hi @almarass ,
See [this answer](https://github.com/cpascual), you don't have to change any external library. 
It is possible that tdDS_ui.py or any file that is called by it, is importing `PyQt` before `Taurus`. This seems the problem. Switching the importing order should solve the problem

**Comment by almarass** [comment]
tdDS_ui.py has been generated form the file tdDS.ui (both attached in pdf format)
[tdDS.ui.pdf](https://github.com/taurus-org/taurus/files/1929059/tdDS.ui.pdf)
[tdDS_ui.py.pdf](https://github.com/taurus-org/taurus/files/1929060/tdDS_ui.py.pdf)

via the command:
pyuic4 -x -o tdDS_ui.py tdDS.ui

**Comment by cmft** [comment]
pyuic4 generated a non sported file for Taurus. 
Replace this line: 
```from PyQt4 import QtCore, QtGui```
For this and the  problem will be solved
```from taurus.external.qt import QtCore, QtGui``` 


> /home/tango-cs/.local/lib/python2.7/site-packages/qtpy/init.py
> and modified them commenting the sip.setapi() instructions, as follows:

Do not forget to restore the original configuration of this file

**Comment by cpascual** [comment]
Hi @almarass avoid using pyuic-compiled files, and compile them on-the-fly.
