### ISSUE TITLE
GUI button to execute arbitrary python script

### ISSUE THREAD

**Issue by almarass** [taurus-org/taurus#760]
Hi,
is it possible to launch the execution of an arbitrary python script via a Taurus button or some other Taurus widget?

thanks,
Alex

**Comment by mrosanes** [comment]
Hi Alex,
I would say that you could use a QPushButton. It is not specific to Taurus, it is the generic qt button.

**Comment by cpascual** [comment]
Hi, If you are using TaurusGui, then maybe your  use case can be solved with adding an "External Application" . It can be accessed from a TaurusGui 's `Tool Menu--> External Application --> Add External Application launcher`, or programmatically with  `TaurusGui.createExternalApp()`.

Another way to add external apps to a TaurusGui, it is to do it directly in the config.py of the GUI as is done in [example01](https://github.com/taurus-org/taurus/blob/3536364243c3e3c37d37da4438b6397f4a0c97d5/lib/taurus/qt/qtgui/taurusgui/conf/tgconf_example01/config.py#L140)

**Comment by cpascual** [comment]
Otherwise, you can do as @mrosanes suggested: just using a QPushButton and connecting it to a method that uses  subprocess (to launch the script)
