### ISSUE TITLE
TaurusTrend problem with updating the value afrer restart qtimer

### ISSUE THREAD

**Issue by KrystianKedron** [taurus-org/taurus#773]
The TaurusTrend has got implemented qtimer to update the value when is need. For big time interval there is a  problem with updating the value and UX. This problem is connected to stoping the updating taurustrend value (stopping the timer). I saw this situation on CentosOS 7. First is when you minialize the window, second after switching the desktop workspace. For big time interval on the x axis the plot refresh is very big in same case is 1-2 minutes. So when user get back and showEvent restart the timer, user must wait 1-2minutes to see the missing plot. This cause the feeling that TaurusTrend don't updating the value. I analized this problem and there are two possible solutions. The easy solution is add the self.replot after restarting the timer in showEvent. But I don't know how this would impacat on the other things in the Taurus. The second one is to add posibility to run TaurusTrend forever without stoping and starting the timer in situation when we change the desktop workspace (for example property in the Taurus configuration).

**Comment by cpascual** [comment]
Hi @KrystianKedron , thanks for reporting, but I am not sure of understanding the issue. I cannot reproduce the behaviour that you mention (my trnds seem to be updated also when they are minimized and I maximize them again after some time)
Is this related to the "forced read" feature in TaurusTrend or with the general "taurus polling period"?

Could you please provide step-by-step instructions for reproducing the problem?

Also, which version of Taurus are you using?

**Comment by KrystianKedron** [comment]
Yes of course:
1. Run TaurusTrend with the example attribute.
2. Configure the long interval for the X axis, for example 20h
3. Minimize the window or switch the work area and wait 15 minutes.
4. Maximize the window or return to this workspace (do not click on the chart and do not change the size of the window because you force the reploting)

In this scenario, you do not see the last 15 minutes on the plot. To force a resizeEvent, you must force the reploting by clicking the graph (DataInspector np) or resize the window. You can wait 2 minutes until qtimier will update the values.

This is a problem when you have a lot of TaurusTrends with a long period in one workspace.

I see this problem on Taurus 4.1.3, but I will test it with 4.3 and 4.3 from the development branch. 

I dont use the  "forced read" feature. I simply start the TaurusTrend application in the debug mode.

**Comment by cpascual** [comment]
Ok, now I understand it. 
I've implemented a fix (see #775) following your first suggestion (I don't see any problem with it)
Can you please check if it works for you? (if you reply soon, the fix may be included in the coming Jul18 release)  ;)

**Comment by KrystianKedron** [comment]
I did quick tests and everything is fine. 

Thanks for the quick response! :)
