### ISSUE TITLE
Jul18 manual release tests: debian9

### ISSUE THREAD

**Issue by cpascual** [taurus-org/taurus#783]
This issue is created for reporting the results of the manual tests for Jul18 release on **debian-stretch**.

### Installation
- [x] **Installed with 'python setup.py install'** Install Taurus from the tar.gz : `pip install <tarball_artifact_URL>`

### Taurusdemo

- [x] Test all of the buttons of the taurusdemo. All demos should launch correctly and without raising exceptions -> **The buttom 'ok' from 'Panel' - > 'Message panel' does not close the window.** 
-> **That this is not a bug. It is just that the demo does not connect the OK button to anything. The behaviour is the same in 4.3.1**
- [x] For TaurusLabel, check foreground role, the background role, the prefix, the suffix, the formatter, etc. -> **One can choose 'value' as background ... but it gives errors.**  -> **That's normal and known. Setting the background to value only makes sense for 
attributes that return a value from the TaurusDevState or PyTango.DevState 
enums. One can test it with the following attribute:
eval:["FAULT","ON","OFF","ALARM"][randint(4)]**
- [x] For TaurusLabel, use a model with fragment (e.g., `sys/tg_test/1/ampli#rvalue.magnitude`, `eval:Q('1mm')#rvalue.unit"`, `eval:10*arange(9)#rvalue[3:4]`)
- [x] For LCD: Test the foreground roles and the background role
- [x] For Led: Test the colors, ON color, Off color.

### taurusplot
(basically try all features described in the [user's guide](http://taurus-scada.org/en/latest/users/ui/index.html)

- [x] Execute: `taurusplot "eval:Q(rand(333),'mm')" sys/tg_test/1/wave`
- [x] Check region Zoom in and out with region zoom and go back stacked zoom levels with
- [x] Check mouse wheel Zoom
- [x] Test panning (dragging with CTRL pressed)
- [x] Test inspector mode
- [x] Test pause mode
- [x] Move curves between axes by clicking on legend (and test zoom on Y2)
- [x] Test plot configuration dialog
- [x] Test changing curve titles
- [x] Test Save & restore config (change curve properties, zoom, etc & check that everything is restored) -> **When restoring I get error messages and the second curve disapears, after some clicks appears again** -> **This is a known issue with case-sensitiveness in taurusplot/trend
It happens for models with upper case. See #522**
- [x] ... other features from [user's guide](http://taurus-scada.org/en/latest/users/ui/index.html)

### taurustrend
(basically try all features described in the [user's guide](http://taurus-scada.org/en/latest/users/ui/index.html)

- [x] Execute: `taurustrend "eval:Q(rand(),'mm')" sys/tg_test/1/ampli`
- [x] Execute: `taurustrend -xe "eval:Q(rand(),'mm')" sys/tg_test/1/ampli`
- [x] Check region Zoom in and out with region zoom and go back stacked zoom levels with
- [x] Check mouse wheel Zoom
- [x] Test panning (dragging with CTRL pressed)
- [x] Test inspector mode
- [x] Test pause mode
- [x] Move curves between axes by clicking on legend (and test zoom on Y2)
- [x] Test plot configuration dialog
- [x] Test Forced reading mode
- [x] Test Save & restore config (change curve properties, zoom, etc & check that everything is restored)
- [x] ... other features from [user's guide](http://taurus-scada.org/en/latest/users/ui/index.html)

### Test taurusimage

- [x] Execute `taurusimage --demo`
- [x] try to resize the image and move it using the mouse.

### taurustrend2d

- [x] Execute: `taurustrend2d --demo --taurus-polling-period 333`
- [ ] **FAIL** Execute: `taurustrend2d -xt --demo --taurus-polling-period 333`  **(known to fail in 4.1.0)**
- [x] Execute: `taurustrend2d -xe --demo --taurus-polling-period 333`
- [x] Test auto-scroll and auto-scale tools
- [ ] **NOT POSSIBLE TO BE TESTED** Test Save & restore config (change axes range, zoom, tool status colormap etc & check that everything is restored)

### Tauruscurve & taurustrend1d
(unused and to be deprecated, you may test but **do not worry too much if they fail**)

- [ ] **FAIL** Execute: `tauruscurve --demo`
- [ ] Change size
- [ ] Move curve with mouse
- [ ] Resize curve with mouse
- [ ] Test some option of the menu with mouse.
- [ ] Execute: `taurustrend1d "eval:Q(rand(),'mm')"` and test it in the same way

### taurusdesigner
- [x] Check that taurusdesigner is correctly opened and taurus widgets are present in the catalog -> **Errors are printed out (in DEBUG level) for not having epics installed. Deprecated warnings also printed out**
- [x] Create an empty widget and drag various taurus widgets to it (they should be correctly dropped)

### taurusdevicepanel
- [x] Execute: `taurusdevicepanel sys/tg_test/1`
- [x] Check that it opens correctly and that the attrs and commands are populated
- [x] Execute SwitchStates command (see that the state label changes to FAULT and its color to red)
      and then execute the Init command and the label returns to RUNNING (blue)

### tauruspanel
- [x] Execute: `tauruspanel`
- [x] Navigate in the tree and select the TangoTest device (the attr an command panels should be populated)

### taurusform
(basically try all features described in the [user's guide](http://taurus-scada.org/en/latest/users/ui/index.html)

- [x] Launch `taurusform sys/tg_test/1/short_scalar`
- [x] Test to drag and drop of this attribute onto the same form many times (4 times)
      (If it crashes, you are seeing bug #96) -> **It does not crash**
- [x] Open "Modify Contents" and add sys/tg_test/1 and all of its attributes. They should all show ok
- [x] Test the compact mode  (switch to compact, noncompact; edit when in compact mode, ...) for a single
      value (from the context menu of a value label)
- [x] Test compact mode for all values (from the context menu of the whole form)
- [x] Test changing labels -> **Fails in devices, already in previous releases. Issue #786 is being created**
- [x] Test changing the formatter for a single value (from the context menu of a value label) (use, e.g. `>>{}<<`) -> **Does not work in compact mode. #787 is being created**
- [x] Test changing the formatter for all values (from the context menu of the whole form)
- [x] Test re-order of values with "Modify contents"
- [x] Test the different "show" buttons (tables, images, spectra)
- [x] Change the write widget of double_scalar by a TaurusWheelEdit
- [x] Change other read and write widgets
- [x] ... other features from [user's guide](http://taurus-scada.org/en/latest/users/ui/index.html)

### taurusgui
(basically try all features described in the [user's guide](http://taurus-scada.org/en/latest/users/ui/index.html)

- [x] Launch `taurusgui example01`
- [x] Test (un)lock view
- [x] Create a new panel (a TaurusForm) and drag and drop several models from other forms
- [x] Move panels around (with view unlocked!) and hide ("close") and re-show them
- [x] Test saving and restoring perspectives
- [x] Test drag&drop from a form to a trend
- [x] Test clicking on "example01 synoptic" elements and check that the panels raised
- [x] Test that selecting a panel changes the selection on "example01 synoptic"
- [x] Test the actions in the menus
- [x] Create a new TaurusGui (call it `foogui`) with `taurusgui --new-gui` (follow the wizard)
- [x] Install `foogui` with pip (using a virtualenv may be a good idea) -> ** Note: I have also tried with 'python setup.py install' and this installation is not right.**
- [x] launch `foogui` using the script that has been installed
- [x] ... other features from [user's guide](http://taurus-scada.org/en/latest/users/ui/index.html)

### taurusconfigbrowser
- [ ] Open an ini file with taurusconfigbrowser and check that it is loaded correctly. -> **I can not open taurusconfigbrowser. I think because I have not done the installation with pip. I get the error:
kg_resources.DistributionNotFound: The 'taurus==4.4.0a0' distribution was not found and is required by the application**

### taurusiconcatalog
- [ ] Launch `taurusiconcatalog`. Several tabs with an array of icons [should be displayed](http://taurus-scada.org/en/latest/devel/icon_guide.html#taurus-icon-catalog) -> **Same problem as with taurusconfigbrowser**
- [ ] Check that tooltips give info on each icon
- [ ] Click on some icons and check that they give a bigger view of the icon and more info.

**Comment by teresanunez** [comment]
HI @cpascual, many thanks, I have found some small issues, I will check it now with your comments.

**Comment by cpascual** [comment]
Hi @teresa. Many thanks for the tests. I am closing the issue.
