### ISSUE TITLE
device model not set if GUI started before device server

### ISSUE THREAD

**Issue by CorF4** [taurus-org/taurus#791]
Hello,
I have updated to taurus4.4.0. Not sure if the observation was there before, but here we go:
I have two TaurusCommandButtons. I set the model on these and the command. If I start the gui now before the device server, I see that only the button I set the model on first is correctly connected and executes its command. The other button however has no model and can therefore not execute any command. When started normally, both buttons work. When during normal operation I stop the device server and restart it, I also cannot see a problem there.
You can reproduce this with the TangoTest device server.
First run the following script with argument `sys/tg_test/1`:

```
import sys

from taurus.external.qt import Qt
from taurus.qt.qtgui.application import TaurusApplication
from taurus.qt.qtgui.util.ui import UILoadable
from taurus.qt.qtgui.button import TaurusCommandButton
from taurus.qt.qtgui.base.taurusbase import TaurusBaseWidget, TaurusBaseWritableWidget

if __name__ == '__main__':

    instance = sys.argv[1]

    app = TaurusApplication(app_name='MyGui')
    
    panel = Qt.QWidget() 
    frame = Qt.QFrame(panel)
    frame.resize(200,200)
	
    button_1 = TaurusCommandButton(panel)
    button_1.setCommand("SwitchStates")
    button_1.setCustomText("Switch States")
    button_1.move(10,10)
    button_2 = TaurusCommandButton(panel)
    button_2.setCommand("DevBoolean")
    button_2.setParameters([1])
    button_2.setCustomText("DevBoolean")
    button_2.move(10,40)
    button_2.setModel(instance)
    button_1.setModel(instance)


    panel.show()
    app.exec_()
```

Then start the TangoTest device server. Push the 'Switch States' button and you should get an error message.
Thanks for your time and taking a look into this!

**Comment by cpascual** [comment]
Hi, after some investigation, I believe this is a more general issue. I can reproduce it with a simple TaurusWidget. for example if you run the following snippet, you will see that the model is only set for the first widget:

```python
from taurus.qt.qtgui.application import TaurusApplication
from taurus.qt.qtgui.container import TaurusWidget


if __name__ == '__main__':
    app = TaurusApplication()

    for i in range(5):
        w = TaurusWidget()
        w.setModel('non/exported/dev')
        m = w.getModelObj()
        print i, w.getModelObj()
        # UNCOMMENTING THE FOLLOWING 2 LINES, THE MODEL IS PROPERLY SET EVERYTIME!
        # w.setModel(None)
        # print i, w.getModelObj()
```

(I am editing the issue title accordingly)

**Comment by cpascual** [comment]
Notes: 
- This issue is also present in previous 4.x releases (tested on 4.1.1 and 4.3.1). On 3.7.5 it does **never** set the model (not even for the first widget)
- the issue does not happen if the model is a tango attribute (e.g. substituting the model of the snippet with `'non/exported/dev/attr'`)
- it also does not affect eval devices (e.g. substituting the model of the snippet with `'eval:/@foo'`)

**Comment by CorF4** [comment]
Hi, thanks for your answer. So, in case of a command-button the two last items on your list are not applicable. Is there some workaround or anything else we can do to make it work for this case if the gui is started before the device server?
Thanks!

**Comment by CorF4** [comment]
Hi Carlos. I tried it and seems to work. Thanks!
