### ISSUE TITLE
How to remove units from TaurusValueLineEdit?

### ISSUE THREAD

**Issue by CorF4** [taurus-org/taurus#796]
Hello,

quick question: I'd like taurus not to show any units in the TaurusValueLineEdit. When started with default write values units are shown. For taurusLabel I removed them by specifiying rvalue.magnitude for fgRole but I don't know how to do it for TaurusValueLineEdits.
Thanks in advance!

**Comment by cpascual** [comment]
You can use format.
For example, assuming that the sys/tg_test/1/short_scalar attribute has units, you could do:

```python
from taurus.qt.qtgui.application import TaurusApplication
from taurus.qt.qtgui.input import TaurusValueLineEdit

if __name__ == '__main__':
    import sys
    app = TaurusApplication()

    w = TaurusValueLineEdit()
    w.setFormat('{0.magnitude}')

    model = 'sys/tg_test/1/short_scalar'
    w.setModel(model)

    w.show()
    sys.exit(app.exec_())
```

But note that this only affects the initial value that is displayed. It does not prevent the user from typing in units when editing the value (and they will be properly taken into account). 

For example, if the wvalue of the attribute is `'3 m'`, with the above format the lineedit will initially display `3`. But now the user can still type "2cm" and when clicking ENTER "0.02 m" (2cm converted to the original units) will be written to the attribute's wvalue and the display will be "2cm" (respecting what the user wrote!)

**Comment by cpascual** [comment]
Note. Accomplishing a similar effect should be possible using the `#wvalue.magnitude` fragment in the model name (e.g. `sys/tg_test/1/short_scalar#wvalue.magnitude`) instead of using the format API... but it does not work now, so I areported it as #797
