### ISSUE TITLE
TaurusValueLineEdit ignores #wvalue.magnitude fragment

### ISSUE THREAD

**Issue by cpascual** [taurus-org/taurus#797]
There has been a regression and now the line edits are failing to act on `#wvalue.magnitude` fragments.

To reproduce:
- Configure sys/tg_test/1/short_scalar to have some units
- run:

```
python -m taurus.qt.qtgui.input.tauruslineedit --taurus-log-level=debug \
            'sys/tg_test/1/short_scalar#wvalue.magnitude' \
            'sys/tg_test/1/short_scalar'
```

This should show 2 lineedits, the first without units and the second with them.

The reason for the failure is an exception in `TaurusValueLineEdit.setValue`, as it can be seen in the debug message: 

`MainThread     DEBUG    2018-08-23 12:56:40,654 TaurusValueLineEdit.sys/tg_test/1/short_scalar#wvalue.magnitude: Cannot enforce fragment. Reason: AttributeError("'NoneType' object has no attribute 'units'",)
`

After some debugging, it seems that the validator is not initialized when setValue is called (which causes this exception).

**Comment by teresanunez** [comment]
Hi @cpascual , i have tried it with the taurus version in develop and I see the units in both lineedits.

**Comment by teresanunez** [comment]
I see the error message you say:

MainThread     DEBUG    2018-08-23 13:29:11,885 TaurusValueLineEdit.sys/tg_test/1/short_scalar#wvalue.magnitude: Invalid format '{:~.{bc.modelObj.precision}f}' for <Quantity(0, 'millimeter')>. Using '{0}'

but the unit is display in both.

**Comment by teresanunez** [comment]
Sorry, I copied the wrong line:

MainThread     DEBUG    2018-08-23 13:31:08,402 TaurusValueLineEdit.sys/tg_test/1/short_scalar#wvalue.magnitude: Cannot enforce fragment. Reason: AttributeError("'NoneType' object has no attribute 'units'",)

If I put any unit without sense, like fffff, then I do not see display in any of both lineedits.

**Comment by cpascual** [comment]
> Hi @cpascual , i have tried it with the taurus version in develop and I see the units in both lineedits.

Yes, that is the problem.

...and as I say in the initial message, I think that the solution will be related to ensuring that the validator is initialized before calling `setValue`
