### ISSUE TITLE
Taurus Form and DevicePanel shows devstate attribute as LED

### ISSUE THREAD

**Issue by MikeFalowski** [taurus-org/taurus#801]
Hello Everyone!
If I connect an attribute of type DevState to `taurusform` or `taurusdevicepanel` it is showed as LED. I would consider if label, showing the name of the state with respected background colour, wouldn't be better.

What do you think?

Mike

**Comment by cmft** [comment]
Hi @MikeFalowski ,
Do you mean something like this?
![taurusform_devstate](https://user-images.githubusercontent.com/6168722/44769176-05f7b800-ab64-11e8-9a97-67bd63ba1924.png)

The `taurusform` allows you to change the used Read/Write widget. You can do it in the contextual menu (right button over the attribute label) and select "Change Read Widget" option.

In taurus4 we changed the `taurusdevicepanel` to use a label (in some version combined with a led) (The image below is V4.4.0 ).
![taurusdevicepanel](https://user-images.githubusercontent.com/6168722/44769570-5c192b00-ab65-11e8-925f-080a6637cf68.png)

**Comment by MikeFalowski** [comment]
Hi @cmft 
Thanks for the trick with the `taurusform` but this is not everything what I exactly meant. I wasn't thinking about device attribute `state` but other attributes within single device which are `DevState` type.

![image](https://user-images.githubusercontent.com/25459174/45168456-99338c00-b1fb-11e8-898e-651bbb0f479e.png)

![image](https://user-images.githubusercontent.com/25459174/45168496-b49e9700-b1fb-11e8-9604-2311d79f249d.png)

![image](https://user-images.githubusercontent.com/25459174/45168711-3f7f9180-b1fc-11e8-8271-b6ce620ac579.png)

Anyway it would be good to have also a colour of the `DevState` type in taurusform.

Thanks!
Mike

**Comment by MikeFalowski** [comment]
Hi @cpascual @cmft 
Thanks for help! It does the job and solves my another question btw.

> Note that making this behaviour the default is possible but, being a matter of taste (more explicit VS more compact), I think it is better not to change it in order not to affect the layout of existing GUIs

Seems reasonable to me. I'm closing issue then.
