### ISSUE TITLE
Custom TaurusLabel [question]

### ISSUE THREAD

**Issue by cpt-majkel** [taurus-org/taurus#802]
Hello Everyone,

I'd like to use my custom version of TaurusLabel (I have to change text as well as background colour according to attribute's value). I inherited from TaurusLabel class and I am wondering what is the best way to implement my logic. Should I override PaintEvent() method, some other Taurus method or simply write my own one? 
Thanks in advance for any advice.

Mike

**Comment by cmft** [comment]
Hi @cpt-majkel , 
Could you be more specific? What behavior would like to have? Did you check if it is implemented? Did Taurus provides the `taurusdemo` widget (in a console launch a taurusdemo)  that shows all the the label modifier options.

**Comment by cpt-majkel** [comment]
Attribute has 5 possible values (integers from 0 - 4) and i have to interpret them in my GUI. "Names" of those values are specific to the device (it's monochromator's mirror mode like "PGM" etc.) and each number means one mirror mode. 
So according to the attribute I have to set text on the label (i.e "PGM") as well as change background colour. Therefore my idea was to override PaintEvent() method and add my logic - I suspect that there is no ready implementation like that. I am not sure, however, if overriding this method is the best solution.

**Comment by cmft** [comment]
Ok,
I will override the `displayValue` method of your custom TaurusLabel. Doing something like this:

```
from taurus.external.qt import Qt
from taurus.qt.qtgui.display import TaurusLabel
from taurus.qt.qtgui.base import TaurusBaseWidget


def displayValue(self, v):
    value2mirrormode = {0: "A",
                        1: "B",
                        2: "C",
                        3: "D",
                        4: "E"
                        }

    if self._permanentText is None:
        value = TaurusBaseWidget.displayValue(self, v)
    else:
        value = self._permanentText

    attr = self.getModelObj()
    dev = attr.getParent()

    try:
        v = value.format(dev=dev, attr=attr)
    except Exception as e:
        self.warning(
            "Error formatting display (%r). Reverting to raw string", e)
        v = value

    return value2mirrormode[int(v)]


def main():
    import sys
    import taurus.qt.qtgui.application
    app = taurus.qt.qtgui.application.TaurusApplication()

    model = "eval:randint(5)"
    w = Qt.QWidget()
    layout = Qt.QGridLayout()
    TaurusLabel.displayValue = displayValue

    l = TaurusLabel()
    l.setModel(model)
    w.setLayout(layout)

    layout.addWidget(l)
    w.show()


    sys.exit(app.exec_())


if __name__ == '__main__':
    main()
```

**Comment by cpt-majkel** [comment]
Thanks a lot for your help! It is exactly what i was looking for  :)
