### ISSUE TITLE
Tango Image Attribute

### ISSUE THREAD

**Issue by stanislaw55** [taurus-org/taurus#804]
Hello,
I would like to use Taurus to create a GUI which will display Tango Image Attribute. To be more specific, it would be image from camera, so I'm most interested in just pure view from camera. 
My question is: what widget would be the best to use in such scenario?

**Comment by cmft** [comment]
Hi @stanislaw55 ,
Up to now taurus has `taurusimage` widget but we are in the meddle of the migration to use PyQtGraph. See [TEP17](https://github.com/cpascual/taurus/blob/tep17/doc/source/tep/TEP17.md) but unfortunately the image widget is not ready yet. If you feel strong enough to collaborate in the develop of it, you are more than welcome (#452)

**Comment by stanislaw55** [comment]
Hi @cmft 
First of all, thank you for rapid response!
AFAICS, this `taurusimage` is accessible from `taurusdesigner` as a `TaurusImageDialog`?

**Comment by cmft** [comment]
> AFAICS, this taurusimage is accessible from taurusdesigner as a TaurusImageDialog?

Yes it is, you are right.
