### ISSUE TITLE
User requests for Sequencer: add command-line parser and duplicate macros

### ISSUE THREAD

**Issue by teresanunez** [taurus-org/taurus#810]
Hello,
              we have these requests from our users (related to the sequencer GUI):

"""
I found two features that I was missing and that may be easy to implement, but would be really great to have:

1. In the macro editor, there is a command-line parser, where I can type spock commands and this then populates the macro parameters. Is this possible to add also to the sequence editor? That makes the input much quicker.

2. Would it be possible to implement some copy / paste functionality, or a „duplicate marked sequence“ thing? Often we run macros that look like this:
ascan mot1 0 10 10 10
mvr mot 2 1
ascan mot1 0 10 10 10
mvr mot 3 1
ascan mot1 0 10 10 10
mvr mot2 1
ascan mot1 0 10 10 10
…
i.e. something that is too simple to write a special macro for, but something which is tedious to click together without copy / paste or duplicate…

"""

Would it be possible to have them implemented?. Many thanks.

**Comment by reszelaz** [comment]
Thanks for the feedback. This issue actually belongs to the Sardana project. 

Regargint the spock edit line (we call it "yellow line") in the MacroExecutor we need to make a decission on it. It is poorly implemented and recently, when implementing [sardana-org/sardana#876](https://github.com/sardana-org/sardana/pull/876), we said that we need to do something with it. Either remove it or refactor the code. So it is an open question still if we add the feature that you ask.

Regarding the duplicate option, it should be easy to implement. [sardana-org/sardana#429](https://github.com/sardana-org/sardana/pull/429) implemented something similar for repeat parameters nodes. @teresanunez do you feel like giving it a try?

Thanks!

**Comment by teresanunez** [comment]
HI @reszelaz, many thanks, and sorry for putting this in Taurus instead of in Sardana.
Yes, I can try to implement it.

**Comment by reszelaz** [comment]
Kamino closed and cloned this issue to [sardana-org/sardana](https://github.com/sardana-org/sardana/issues/939)
