### ISSUE TITLE
Second axis in TaurusTrend from code

### ISSUE THREAD

**Issue by stanislaw55** [taurus-org/taurus#815]
Hello
Another question from me. I'm wondering is there a way to configure TaurusTrend object to have second axis for specified attribute used in `setModel` method. Haven't found any relevant documentation, but frankly,  I've done only quick search.

**Comment by cpascual** [comment]
If you mean a second Y axis, have a look at the [`setCurvesYAxis()`](http://taurus-scada.org/devel/api/taurus/qt/qtgui/plot/_TaurusPlot.html#taurus.qt.qtgui.plot.TaurusPlot.setCurvesYAxis) method that `TaurusTrend` inherits from `TaurusPlot`.

If you mean a second X axis, that is not possible in TaurusTrend (neither programatically nor interactively)

**Comment by cpascual** [comment]
I assume the answer was ok.

Just for completitude, note that the answer referred to the old Qwt5-based TaurusTrend. The pyqtgraph-based TaurusTrend also allows to assign curves to a secondary Y axis (adding them to the Y2ViewBox)
