### ISSUE TITLE
Test 'support for python3' code in debian9 + python2 at ALBA 

### ISSUE THREAD

**Issue by cpascual** [taurus-org/taurus#816]
This issue is created for reporting the results of the manual tests for python 2 & 3 support PR  #703

Tested on Debian GNU/Linux 9 (stretch) with python2 using the checklist from

https://github.com/taurus-org/taurus/blob/develop/doc/how_to_release.md#manual-test-checklist

### Installation
- [x] Install Taurus from the tar.gz : `pip install <tarball_artifact_URL>`
    - I installed on a PRISTINE [taurus-test:debian-stretch](https://github.com/cpascual/taurus-test) DOCKER IMAGE and used the appveyor tarball:

<s>`pip install https://ci.appveyor.com/api/buildjobs/3kt2he6dq96t4fvw/artifacts/dist%2Ftaurus-4.4.1a0.tar.gz`</s> 

<s>`pip install https://ci.appveyor.com/api/buildjobs/3espsq058vso149q/artifacts/dist%2Ftaurus-4.4.1a0.tar.gz`</s>

<s>`pip install https://ci.appveyor.com/api/buildjobs/vtagrjlwrnlyeltl/artifacts/dist%2Ftaurus-4.4.1a0.tar.gz`</s>

<s>`pip install https://ci.appveyor.com/api/buildjobs/24op01lxvitvsj58/artifacts/dist%2Ftaurus-4.4.1a0.tar.gz`</s>

`pip install https://ci.appveyor.com/api/buildjobs/eyc0uubsvqy7ivfe/artifacts/dist%2Ftaurus-4.4.1a0.tar.gz`

### Taurusdemo

- [x] Test all of the buttons of the taurusdemo. All demos should launch correctly and without raising exceptions
    - <s>**Problems** found with taurusmessagebox and taurusmessagepanel: https://github.com/piertoni/taurus/issues/12 </s> FIXED
    - <s>**Problems found** with label, lcd and led demos: https://github.com/piertoni/taurus/issues/13</s> FIXED
- [x] For TaurusLabel, check foreground role, the background role, the prefix, the suffix, the formatter, etc.
- [x] For TaurusLabel, in order to test the background role=value, you can use the following attribute: `eval:["FAULT","ON","OFF","ALARM"][randint(4)]`
- [x] For TaurusLabel, use a model with fragment (e.g., `sys/tg_test/1/ampli#rvalue.magnitude`, `eval:Q('1mm')#rvalue.units"`, `eval:10*arange(9)#rvalue[3:4]`)
- [x] For LCD: Test the foreground roles and the background role
- [x] For Led: Test the colors, ON color, Off color. (hint: you can use `eval:False` as a model for testing)

### taurusplot
(basically try all features described in the [user's guide](http://taurus-scada.org/en/latest/users/ui/index.html)

- [x] Execute: `taurusplot "eval:Q(rand(333),'mm')" sys/tg_test/1/wave`
- [x] Check region Zoom in and out with region zoom and go back stacked zoom levels with the mouse middle button
- [x] Check mouse wheel Zoom
- [x] Test panning (dragging with CTRL pressed)
- [x] Test inspector mode
- [x] Test pause mode
- [x] Move curves between axes by clicking on legend (and test zoom on Y2)
- [x] Test plot configuration dialog
- [x] Test changing curve titles
- [x] Test Save & restore config (change curve properties, zoom, etc & check that everything is restored)
- [x] Open the "Input data selection" dialog and add/remove/reorder /edit models
    - hit **known bug** #522 (other than that, all ok)
- [x] export one curve data to ASCII and then load it using "Input data selection"  -> raw data -> open file
- [ ] ... other features from [user's guide](http://taurus-scada.org/en/latest/users/ui/index.html)

### taurustrend
(basically try all features described in the [user's guide](http://taurus-scada.org/en/latest/users/ui/index.html)

- [x] Execute: `taurustrend "eval:Q(rand(),'mm')" sys/tg_test/1/ampli`
- [x] Execute: `taurustrend -xe "eval:Q(rand(),'mm')" sys/tg_test/1/ampli`
- [x] Check region Zoom in and out with region zoom and go back stacked zoom levels with the mouse middle button
- [x] Check mouse wheel Zoom
- [x] Test panning (dragging with CTRL pressed)
- [x] Test inspector mode
- [x] Test pause mode
- [x] Move curves between axes by clicking on legend (and test zoom on Y2)
- [x] Test plot configuration dialog
- [x] Test Forced reading mode
- [x] Test autopanning mode
- [x] Test autoscale x mode
- [ ] Test Save & restore config (change curve properties, zoom, etc & check that everything is restored)
- [x] ... other features from [user's guide](http://taurus-scada.org/users/ui/index.html)

### Test taurusimage

- [x] Execute `taurusimage --demo`
- [x] try to resize the image and move it using the mouse.

### taurustrend2d

- [x] Execute: `taurustrend2d --demo --taurus-polling-period 333`
- [x] Execute: `taurustrend2d -xt --demo --taurus-polling-period 333`  **(known to fail in 4.1.0)**
- [x] Execute: `taurustrend2d -xe --demo --taurus-polling-period 333`
- [x] Test auto-scroll and auto-scale tools
- [ ] Test Save & restore config (change axes range, zoom, tool status colormap etc & check that everything is restored)

### taurusdesigner
- [x] Check that taurusdesigner is correctly opened and taurus widgets are present in the catalog
- [x] Create an empty widget and drag various taurus widgets to it (they should be correctly dropped)

### taurusdevicepanel
- [x] Execute: `taurusdevicepanel sys/tg_test/1`
- [x] Check that it opens correctly and that the attrs and commands are populated
- [x] Execute SwitchStates command (see that the state label changes to FAULT and its color to red)
      and then execute the Init command and the label returns to RUNNING (blue)

### tauruspanel
- [x] Execute: `tauruspanel`
- [x] Navigate in the tree and select the TangoTest device (the attr an command panels should be populated)

### taurusform
(basically try all features described in the [user's guide](http://taurus-scada.org/users/ui/index.html)

- [x] Launch `taurusform sys/tg_test/1/short_scalar`
- [x] go to label context menu, change the configuration and set range to (-1000, 1000), alarm to (-500, 500) and unit to `mm`. Close the form and relaunch. The new units should be used. Change the the write value and check that the orange color is used when in warning values, and that the write widget does not allow to write values out of range.
- [x] Test to drag and drop of this attribute onto the same form many times (4 times)
      (If it crashes, you are seeing bug #96)
- [x] Open "Modify Contents" and add sys/tg_test/1 and all of its attributes. They should all show ok
- [x] Test the compact mode  (switch to compact, noncompact; edit when in compact mode, ...) for a single
      value (from the context menu of a value label)
- [x] Test compact mode for all values (from the context menu of the whole form)
- [x] Test changing labels
- [x] Test changing the formatter for a single value (from the context menu of a value label) (use, e.g. `>>{}<<`). Do this in compact and non compact modes.
- [x] Test changing the formatter for all values (from the context menu of the whole form)
- [x] Test re-order of values with "Modify contents"
- [x] Test the different "show" buttons (tables, images, spectra)
- [x] Change the write widget of double_scalar by a TaurusWheelEdit
- [x] Change other read and write widgets
- [ ] ... other features from [user's guide](http://taurus-scada.org/users/ui/index.html)

### taurusgui
(basically try all features described in the [user's guide](http://taurus-scada.org/users/ui/index.html)

- [x] Launch `taurusgui example01`
    - **Problem** loading the nexus browser widget: https://github.com/piertoni/taurus/issues/15
- [x] Test (un)lock view
- [x] Create a new panel (a TaurusForm) and drag and drop several models from other forms
- [x] Move panels around (with view unlocked!) and hide ("close") and re-show them
- [x] Test saving and restoring perspectives
- [x] Test drag&drop from a form to a trend
- [x] Test clicking on "example01 synoptic" elements and check that the panels raised
- [x] Test that selecting a panel changes the selection on "example01 synoptic"
- [x] Test the actions in the menus
- [x] Create a new TaurusGui (call it `foogui`) with `taurusgui --new-gui` (follow the wizard)
- [x] Install `foogui` with pip (using a virtualenv may be a good idea)
- [x] launch `foogui` using the script that has been installed
- [ ] ... other features from [user's guide](http://taurus-scada.org/users/ui/index.html)

### taurusconfigbrowser
- [x] Open an ini file with taurusconfigbrowser and check that it is loaded correctly.
    - **Known Problem (segfault on closing)** (it affects also the develop branch. see #818 )

### taurusiconcatalog
- [x] Launch `taurusiconcatalog`. Several tabs with an array of icons [should be displayed](http://taurus-scada.org/en/latest/devel/icon_guide.html#taurus-icon-catalog)
- [x] Check that tooltips give info on each icon
- [x] Click on some icons and check that they give a bigger view of the icon and more info.

### sardana
- [x] install latest sardana release () `pip install sardana`
- [x] on another console, run `Sardana demo1`
- [x] launch spock and run sar_demo
- [x] in spock, run a couple of macros `lsm`, `ascan mot01 1 10 9 .1`
- [x] launch `sardanatestsuite`  **(I had to install a patched `libtango9 9.2.5a+dfsg1-2+patch3~bpo9+0~alba+1` to avoid the bug from https://github.com/tango-controls/cppTango/pull/445)**: Results: `Ran 184 tests in 625.824s OK (skipped=7, expected failures=1)`

- [x] create a gui with `taurusgui --new-gui` that connects to demo1 , install it and check that the macroexecutor and the other macro-related panels work
    - <s>**I got a problem** https://github.com/piertoni/taurus/issues/16 </s> FIXED

**Comment by cpascual** [comment]
While doing the tests I've found some issues that are not specific to #703 and which I reported directly to the taurus issue tracker:

**Comment by cmft** [comment]
I found troubles with `taurusdesigner` if you starting to create a GUI and you decided do not save it the designer does not died

**Comment by cpascual** [comment]
All tests ok. Closing
