### ISSUE TITLE
checking GUI is still working

### ISSUE THREAD

**Issue by PhilLAL** [taurus-org/taurus#823]
Hi guys, 
some users asked how to check that GUI is still working.
They do not experienced failure with taurus but with other GUI softwares. One suggestion is to integrate a clockwork to the GUI. Then, if GUI fails, clockwork should stop and show the time at which GUI failed.

Did you already have this kind of request and do you have any other solution?
Regards.

**Comment by reszelaz** [comment]
There is a heartbeat led in the `TaurusMainWindow` for the same purposes. It is located in the right down corner. When it blinks it means that the GUI is fine.

@guifrecuni developed an APM widget for similar purposes (or even more). It is planned to be integrated in Taurus soon.

**Comment by PhilLAL** [comment]
Oh, I followed examples given in http://taurus-scada.org/devel/examples.html and never though using TaurusMainWindow, I will take a look, thank you for the keyword.

**Comment by cpascual** [comment]
Note that if you do not wish to use `TaurusMainWindow` for some reason, you can add the heartbeat LED just as any other widget. Just instantiate a `QLed` (it is in `taurus.qt.qtgui.display.QLed`)
Just insert it and call `.setBlinkingInterval(mseconds)`

**Comment by PhilLAL** [comment]
Thank you Carlos.
I added a TaurusMainWindow in which I set my TaurusWidget with setCentralWidget and it seems to work. It was just I never used TaurusMainWindow apart of testing.

I do not know if several people use TaurusMainWindow but perhaps it would be helpful to add some examples using this in documentation.

**Comment by cpascual** [comment]
> I do not know if several people use TaurusMainWindow but perhaps it would be helpful to add some examples using this in documentation.

Good point. I created issue #824 so that it is not forgotten ... of course feel free to contribute ;)
