### ISSUE TITLE
Manual testing taurus for TEP18 (python2 + PyQt5) in debian9

### ISSUE THREAD

**Issue by mrosanes** [taurus-org/taurus#830]
Manual testing taurus for TEP18 in debian9 using Conda environment with Python2 and PyQt5
PR for TEP18: https://github.com/taurus-org/taurus/pull/814

Most of dependencies installed with conda from inside the conda environment.

guiqwt installed with pip:
- pip install guidata
- pip install cython
- pip install guiqwt

Installing taurus from the tep18 branch checkout cpascual/tep18 
**pip install --no-deps -e .**

**Comment by mrosanes** [comment]
### Taurusdemo

- [ ] Test all of the buttons of the taurusdemo. All demos should launch correctly and without raising exceptions
- [ ] For TaurusLabel, check foreground role, the background role, the prefix, the suffix, the formatter, etc.
- [ ] For TaurusLabel, in order to test the background role=value, you can use the following attribute: `eval:["FAULT","ON","OFF","ALARM"][randint(4)]`
- [ ] For TaurusLabel, use a model with fragment (e.g., `sys/tg_test/1/ampli#rvalue.magnitude`, `eval:Q('1mm')#rvalue.unit"`, `eval:10*arange(9)#rvalue[3:4]`)
- [ ] For LCD: Test the foreground roles and the background role
- [ ] For Led: Test the colors, ON color, Off color. (hint: you can use `eval:False` as a model for testing)

### taurusplot
(basically try all features described in the [user's guide](http://taurus-scada.org/en/latest/users/ui/index.html)

- [ ] Execute: `taurusplot "eval:Q(rand(333),'mm')" sys/tg_test/1/wave`
- [ ] Check region Zoom in and out with region zoom and go back stacked zoom levels with the mouse middle button
- [ ] Check mouse wheel Zoom
- [ ] Test panning (dragging with CTRL pressed)
- [ ] Test inspector mode
- [ ] Test pause mode
- [ ] Move curves between axes by clicking on legend (and test zoom on Y2)
- [ ] Test plot configuration dialog
- [ ] Test changing curve titles
- [ ] Test Save & restore config (change curve properties, zoom, etc & check that everything is restored)
- [ ] Open the "Input data selection" dialog and add/remove/reorder /edit models
- [ ] export one curve data to ASCII and then load it using "Input data selection"  -> raw data -> open file
- [ ] ... other features from [user's guide](http://taurus-scada.org/en/latest/users/ui/index.html)

### taurustrend
(basically try all features described in the [user's guide](http://taurus-scada.org/en/latest/users/ui/index.html)

- [ ] Execute: `taurustrend "eval:Q(rand(),'mm')" sys/tg_test/1/ampli`
- [ ] Execute: `taurustrend -xe "eval:Q(rand(),'mm')" sys/tg_test/1/ampli`
- [ ] Check region Zoom in and out with region zoom and go back stacked zoom levels with the mouse middle button
- [ ] Check mouse wheel Zoom
- [ ] Test panning (dragging with CTRL pressed)
- [ ] Test inspector mode
- [ ] Test pause mode
- [ ] Move curves between axes by clicking on legend (and test zoom on Y2)
- [ ] Test plot configuration dialog
- [ ] Test Forced reading mode
- [ ] Test autopanning mode
- [ ] Test autoscale x mode
- [ ] Test Save & restore config (change curve properties, zoom, etc & check that everything is restored)
- [ ] ... other features from [user's guide](http://taurus-scada.org/users/ui/index.html)

### Test taurusimage

- [ ] Execute `taurusimage --demo`
- [ ] try to resize the image and move it using the mouse.

### taurustrend2d

- [ ] Execute: `taurustrend2d --demo --taurus-polling-period 333`
- [ ] Execute: `taurustrend2d -xt --demo --taurus-polling-period 333`  **(known to fail in 4.1.0)**
- [ ] Execute: `taurustrend2d -xe --demo --taurus-polling-period 333`
- [ ] Test auto-scroll and auto-scale tools
- [ ] Test Save & restore config (change axes range, zoom, tool status colormap etc & check that everything is restored)

### taurusdesigner
- [ ] Check that taurusdesigner is correctly opened and taurus widgets are present in the catalog
- [ ] Create an empty widget and drag various taurus widgets to it (they should be correctly dropped)

### taurusdevicepanel
- [ ] Execute: `taurusdevicepanel sys/tg_test/1`
- [ ] Check that it opens correctly and that the attrs and commands are populated
- [ ] Execute SwitchStates command (see that the state label changes to FAULT and its color to red)
      and then execute the Init command and the label returns to RUNNING (blue)

### tauruspanel
- [ ] Execute: `tauruspanel`
- [ ] Navigate in the tree and select the TangoTest device (the attr an command panels should be populated)

### taurusform
(basically try all features described in the [user's guide](http://taurus-scada.org/users/ui/index.html)

- [ ] Launch `taurusform sys/tg_test/1/short_scalar`
- [ ] go to label context menu, change the configuration and set range to (-1000, 1000), alarm to (-500, 500) and unit to `mm`. Close the form and relaunch. The new units should be used. Change the the write value and check that the orange color is used when in warning values, and that the write widget does not allow to write values out of range.
- [ ] Test to drag and drop of this attribute onto the same form many times (4 times)
      (If it crashes, you are seeing bug #96)
- [ ] Open "Modify Contents" and add sys/tg_test/1 and all of its attributes. They should all show ok
- [ ] Test the compact mode  (switch to compact, noncompact; edit when in compact mode, ...) for a single
      value (from the context menu of a value label)
- [ ] Test compact mode for all values (from the context menu of the whole form)
- [ ] Test changing labels
- [ ] Test changing the formatter for a single value (from the context menu of a value label) (use, e.g. `>>{}<<`). Do this in compact and non compact modes.
- [ ] Test changing the formatter for all values (from the context menu of the whole form)
- [ ] Test re-order of values with "Modify contents"
- [ ] Test the different "show" buttons (tables, images, spectra)
- [ ] Change the write widget of double_scalar by a TaurusWheelEdit
- [ ] Change other read and write widgets
- [ ] ... other features from [user's guide](http://taurus-scada.org/users/ui/index.html)

### taurusgui
(basically try all features described in the [user's guide](http://taurus-scada.org/users/ui/index.html)

- [ ] Launch `taurusgui example01`
- [ ] Test (un)lock view
- [ ] Create a new panel (a TaurusForm) and drag and drop several models from other forms
- [ ] Move panels around (with view unlocked!) and hide ("close") and re-show them
- [ ] Test saving and restoring perspectives
- [ ] Test drag&drop from a form to a trend
- [ ] Test clicking on "example01 synoptic" elements and check that the panels raised
- [ ] Test that selecting a panel changes the selection on "example01 synoptic"
- [ ] Test the actions in the menus
- [ ] Create a new TaurusGui (call it `foogui`) with `taurusgui --new-gui` (follow the wizard)
- [ ] Install `foogui` with pip (using a virtualenv may be a good idea)
- [ ] launch `foogui` using the script that has been installed
- [ ] ... other features from [user's guide](http://taurus-scada.org/users/ui/index.html)


### taurusconfigbrowser
- [ ] Open an ini file with taurusconfigbrowser and check that it is loaded correctly.

### taurusiconcatalog
- [ ] Launch `taurusiconcatalog`. Several tabs with an array of icons [should be displayed](http://taurus-scada.org/en/latest/devel/icon_guide.html#taurus-icon-catalog)
- [ ] Check that tooltips give info on each icon
- [ ] Click on some icons and check that they give a bigger view of the icon and more info.

**Comment by mrosanes** [comment]
**Using tep18 python2 qt4:**

Check if errors in tep18 python2 qt5 also exists when using qt4:

- [x] Open taurusdesigner 
**It does not open, even if an error is not displayed**
- [x] Open taurusplot
**Error**
**AttributeError: 'module' object has no attribute 'QwtScaleDraw'**
- [x] Open taurustrend
**Error**
**AttributeError: 'module' object has no attribute 'QwtScaleDraw'**

**Comment by mrosanes** [comment]
Using develop (375859513c017b) with python2 and qt4 (+ qtpy):


- [x] taurusdemo QPixmap 
**Same error than the one found using qt5**
- [x] Open taurusdesigner 
**It does not open, even if an error is not displayed**
- [x] Open taurusplot
**Error**
**AttributeError: 'module' object has no attribute 'QwtScaleDraw'**
- [x] Open taurustrend
**Error**
**AttributeError: 'module' object has no attribute 'QwtScaleDraw'**
- [x] **taurustrend2d**: Same errors with qt4 taurustrend2d than the reported for qt5
- [x] **tauruspanel**
    class FancyScaleDraw(Qwt5.QwtScaleDraw):
AttributeError: 'module' object has no attribute 'QwtScaleDraw'

- [x] **taurusiconcatalog:**
**Error**
TypeError: qtTaurusMessageHandler() takes exactly 3 arguments (2 given)
No icons are displayed

### TaurusForm

- [x] Launch taurusform: 
**Error 0:** : TypeError: qtTaurusMessageHandler() takes exactly 3 arguments (2 given)
**Error 1:** When selecting attributes (from tangotest DS) in the taurusform model chooser, the attributes added (using the plus icon) are not visible in the model chooser lower window.
**Error 2:** when selecting more than one attribute in the model chooser using the mouse:
    taurus.qt.qtcore.mimetypes.TAURUS_MODEL_MIME_TYPE, str(data[0]))
TypeError: setData(self, str, Union[QByteArray, bytes, bytearray]): argument 2 has unexpected type 'newstr'
 
- [x] go to label context menu, change the configuration and set range to (-1000, 1000), alarm to (-500, 500) and unit to `mm`. Close the form and relaunch. The new units should be used. Change the the write value and check that the orange color is used when in warning values, and that the write widget does not allow to write values out of range.
https://gist.github.com/mrosanes/b60606dfc268f81f81ef130ba89d0da0

- [x] Test to drag and drop of this attribute onto the same form many times (4 times)
    **Drag and drop crashes** (bug #96)
- [x] Open "Modify Contents" and add sys/tg_test/1 and all of its attributes. They should all show ok
Contents are not visible in taurus model chooser lower window

- [x] Test the different "show" buttons (tables, images, spectra)
**double_spectrum show button does not work:**
  File "/home/mrosanes/PycharmProjects/taurus/lib/taurus/qt/qtgui/util/tauruswidgetfactory.py", line 204, in getWidgetClass
    return self._qt_widgets[name][1]
KeyError: 'TaurusPlot'
- [x] Change the write widget of double_scalar by a TaurusWheelEdit
**Error with tauruswheeledit**
  File "/home/mrosanes/PycharmProjects/taurus/lib/taurus/qt/qtgui/input/qwheel.py", line 255, in _build
    l.setContentsMargin(0, 0, 0, 0)
AttributeError: 'QGridLayout' object has no attribute 'setContentsMargin'


### taurusgui
(basically try all features described in the [user's guide](http://taurus-scada.org/users/ui/index.html)

- [x] Launch `taurusgui example01`
**Error launching example01**
https://gist.github.com/mrosanes/877b7f1b63786984421121ea177393fe
The following eight points could not be tested as example01 was not launched correctly.

- [x] launch `foogui` using the script that has been installed
*It is correctly launched the first time; after it presents a problem and it is not launched anymore*
  File "/home/mrosanes/PycharmProjects/taurus/lib/taurus/qt/qtgui/container/taurusmainwindow.py", line 628, in loadSettings
    ba = Qt.from_qvariant(settings.value(
**AttributeError: 'module' object has no attribute 'from_qvariant'**




### taurusconfigbrowser
- [x] Open an ini file with taurusconfigbrowser and check that it is loaded correctly.
**Error when opening ini file using taurusconfigbrowser**
  File "/home/mrosanes/PycharmProjects/taurus/lib/taurus/qt/qtgui/panel/taurusconfigeditor.py", line 349, in getTaurusConfigFromSettings
    qstate = Qt.from_qvariant(self._settings.value(key), 'toByteArray')
AttributeError: 'module' object has no attribute 'from_qvariant'

**Comment by cpascual** [comment]
This is already done. Closing
