### ISSUE TITLE
TaurusPollingTimer[3000]

### ISSUE THREAD

**Issue by kklmn** [taurus-org/taurus#839]
Hi,

I've created a taurusgui and populated it with tauruspanels and taurusdevicepanels. It constantly gives a warning message in the terminal:

`TimerLoop 1    WARNING  2019-01-17 15:14:17,991 TaurusPollingTimer[3000].Timer on _pollAttributes: loop function took more than loop interval (3.0s)`.

Is there a way to know the problematic device? Or, differently, can you extend the warning message with some more diagnostics?

version 4.4.0

Thanks!

**Comment by cmft** [comment]
Hi @kklmn,
Looking at the code in this line there is not more info.
Did you try to run your GUI with `--taurus-log-level=debug` option? Maybe you can get any hint .

**Comment by kklmn** [comment]
Hi Carlos,

Indeed, one encoder cannot give Value, and in the debug mode I can see which one.

Thank you for the tip!
