### ISSUE TITLE
createConfig: LabelWidget not saved

### ISSUE THREAD

**Issue by kklmn** [taurus-org/taurus#840]
Hi,

When I close taurusgui with many motors or just do Save Perspective, I get:

`MainThread     INFO     2019-01-17 15:14:32,764 PoolMotorTV.tango://b-v-balder-csdb-0.maxiv.lu.se:10000/b308a-o05/opt/slit-01-vb: createConfig: LabelWidget not saved because it is not Pickable (<class 'sardana.taurus.qt.qtgui.extra_pool.poolmotor.PoolMotorTVLabelWidget'>)`
for each motor -- a very long output.

Can you please look at it?

Taurus 4.4.0, Sardana 2.5.0
 
Thanks!

**Comment by cmft** [comment]
Hi @kklmn ,
Thanks for reporting it.

The error can be reproduced with a taurusgui with just a panel and a motor

```
MainThread     INFO     2019-01-17 16:04:49,628 b'PoolMotorTV.tango://pc253.cells.es:10000/motor/motctrl02/1': createConfig: LabelWidget not saved because it is not Pickable (<class 'sardana.taurus.qt.qtgui.extra_pool.poolmotor.PoolMotorTVLabelWidget'>)
MainThread     INFO     2019-01-17 16:04:49,628 b'PoolMotorTV.tango://pc253.cells.es:10000/motor/motctrl02/1': createConfig: ReadWidget not saved because it is not Pickable (<class 'sardana.taurus.qt.qtgui.extra_pool.poolmotor.PoolMotorTVReadWidget'>)
MainThread     INFO     2019-01-17 16:04:49,628 b'PoolMotorTV.tango://pc253.cells.es:10000/motor/motctrl02/1': createConfig: WriteWidget not saved because it is not Pickable (<class 'sardana.taurus.qt.qtgui.extra_pool.poolmotor.PoolMotorTVWriteWidget'>)
MainThread     INFO     2019-01-17 16:04:49,628 b'PoolMotorTV.tango://pc253.cells.es:10000/motor/motctrl02/1': createConfig: UnitsWidget not saved because it is not Pickable (<class 'sardana.taurus.qt.qtgui.extra_pool.poolmotor.PoolMotorTVUnitsWidget'>)

```

**Comment by cpascual** [comment]
Hi, a couple of first thoughts about this:

- it looks like a problem in Sardana's `PoolMotor`. If we confirm it, we will have to move this issue to [the sardana's tracker](https://github.com/sardana-org/sardana/issues).
- The output that you report are just INFO log messages, not necessariliy errors. Are you experiencing any issue that may be related to them (e.g. the perspective not being correctly saved/restored)?

**Comment by cpascual** [comment]
Moved to sardana ( https://github.com/sardana-org/sardana/issues/1164 )
