### ISSUE TITLE
empty Trend1D

### ISSUE THREAD

**Issue by kklmn** [taurus-org/taurus#841]
Hi,
After upgrade to Taurus 4.4.0 and Sardana 2.5.0 we don't have Trend1D plots for Sardana scans.
In input data selection the default source now gets a prefix "scan://" and a warning sign, see the screenshot:
![screenshot from 2019-01-18 10-52-27](https://user-images.githubusercontent.com/17322580/51379591-18bd5a00-1b10-11e9-99f1-147bc5b8b336.png)

When I add door/01 manually, it adds (Empty), as on the screenshot (I remove the red row of course before I apply). I've tried to add some specific attributes, like 'Record Data', with no luck. I can edit the red row and remove the prefix or a whole part until 'balder', no effect.

This empty Trend1D you can get if you create a new taurusgui with a connection to a door. And then try to scan a dummy motor.

Please advise.
Konstantin

**Comment by kklmn** [comment]
This seems to be Sardana problem. Juliano has tried with an older Sardana but new Taurus, and old Taurus and new Sardana and with a new Sardana we have an empty "Trend 1D - <mov>".

**Comment by cpascual** [comment]
Hi @kklmn, since it looks like this is related to sardana, not taurus, could you please recreate it in [the sardana tracker](https://github.com/sardana-org/sardana/issues)?

**Comment by cpascual** [comment]
Anyway, just to give some tips:

- the `scan://` prefix is ok, and should be there
- the warning sign (and red color) is a known issue which should be completely harmless and unrelated to your problem.

**Comment by cpascual** [comment]
>  we have an empty "Trend 1D - ".

Have you tried to actually run a scan?

The dynamic trends created for the scans are actually suppossed to be empty until the moment that some scan data arrives

**Comment by kklmn** [comment]
We've just discovered, that re-creation of measurement groups anew solves the issue.
Is it known that Sardana upgrade requires this? If not, I can open a new issue there to report it to other users.
> Have you tried to actually run a scan?

Yes, certainly we have.

**Comment by cpascual** [comment]
> We've just discovered, that re-creation of measurement groups anew solves the issue.
Is it known that Sardana upgrade requires this? 

I am not sure, but it could be.

> If not, I can open a new issue there to report it to other users.

I think that that would be best since there will be people reading there with more insight into the sardana specificities. 

I close it here, then.

**Comment by cpascual** [comment]
See: https://github.com/sardana-org/sardana/issues/1017
