### ISSUE TITLE
Prompt is not returned when closing taurus applications in Win10 (taurus 4.5.1)

### ISSUE THREAD

**Issue by mrosanes** [taurus-org/taurus#866]
When launching taurus applications in most cases, prompt is not returned when closing taurusapplications for Win10. Tested with taurus 4.5.1. The problem is present for python2+pyqt4 and also for python3+pyqt5.

E.g: taurusform adding a model, and then closing the application.

**Comment by cpascual** [comment]
Confirmed also in win10 with py3 qt5

**Comment by cpascual** [comment]
I propose to adress this issue together with #856

**Comment by tiagocoutinho** [comment]
Tested on windows. I confirm it is fixed

**Comment by cpascual** [comment]
Ok, it looks like it had to do with the tango installation in our test environment. Since @tiagocoutinho 's recent tests with a more current conda environment do not show the problem, I am closing it.

**Comment by cpascual** [comment]
Ok, it looks like it had to do with the tango installation in our test environment. Since @tiagocoutinho 's recent tests with a more current conda environment do not show the problem, I am closing it.
