### ISSUE TITLE
taurusguis on Win10: Prompt does not report information (taurus 4.5.1) 

### ISSUE THREAD

**Issue by mrosanes** [taurus-org/taurus#868]
When launching a taurusgui on Win10 (using taurus 4.5.1), the taurusgui does not report any information on the prompt. 
The taurusgui is opened correctly but the prompt is returned as soon as the taurusgui is opened.

**Comment by cpascual** [comment]
I propose to adress this issue together with #856

**Comment by cpascual** [comment]
PR #935 should fix this: I changed the setup template so that the launcher is a console_script

**Comment by tiagocoutinho** [comment]
Tested on windows. I confirm it is fixed
