### ISSUE TITLE
taurusdesigner does not launch in windows10 with py3 and qt5

### ISSUE THREAD

**Issue by cpascual** [taurus-org/taurus#871]
launching `taurusdesigner on a windows 10 with py3 qt5 yields 
ModuleNotFound: no module named 'PyQt4'

Note that this does not happen with debian py3 qt5

**Comment by tiagocoutinho** [comment]
Seems to be code that is triggered on windows only

**Comment by tiagocoutinho** [comment]
Status report:
The proper way to find the designer binary seems to be:
`designer_bin = str(Qt.QLibraryInfo.location(Qt.QLibraryInfo.BinariesPath)`

This works on linux.

For Mac there is a special implementation which I have no way of testing and is outside the scope of this issue. 

For windows:
* with conda:
  * PyQt5 installed with `conda install pyqt=5`: running the above code reports the designer to be installed in what was probably the path that was used at pyqt5 conda package compile time (something like `C:/qt64/qt_1544645195969/_h_env/Library/bin`). IMHO, it seems to be a bug in the conda PyQt5 package.
The QtDesigner is located at `$CONDA_PREFIX\Library\bin\designer.exe`

* outside conda: the PyQt5 pypi package does not include qtdesigner. The official Qt package from https://www.qt.io does not seem to come with Qtdesigner anymore. Only QtCreator.

Conclusion: on windows, the only way to run taurusdesigner using qt5 is to use a conda environment. The pyqt5 conda package seems to have a bug and is not able to find the qtdesigner location using the official qt location API.
