### ISSUE TITLE
Wrong DevState management in TaurusDevPanel

### ISSUE THREAD

**Issue by sergirubio** [taurus-org/taurus#882]
<s>TaurusDevicePanel</s> TaurusDevPanel manages TaurusDevState as if it was related to Tango communication

TangoDevice instead is assigning TaurusDevState depending of Hardware state (independently if it communicates or not).

This discrepancy does not allow to display devices requiring user action (e.g. a Disabled device that needs to be re-enabled via Tango command).

**Comment by sergirubio** [comment]
Just pasting more details on the issue:

 devices with states in FAULT / DISABLE are now unaccessible from some GUI's; despite being completely operative from Jive or Taurusform

I think it all comes from several misunderstandings of States of Tango Devices:

 - https://sourceforge.net/p/tauruslib/tickets/236/

 - https://github.com/taurus-org/taurus/commit/f9abe7fa473ec3c1e5f3bcac9f03aafcda4f6684#diff-1271b37c316b41e2ad8370db94e1de3e


the definition of both states from the Tango Device Design Guidelines:

FAULT red The device has a major failure that prevents it to work. For instance, A powersupply has stopped due to over temperature A motor cannot move because it has fault conditions. Usually we cannot get out from this state without an intervention on the hardware or a reset command.

DISABLE magenta The device cannot be switched ON for an external reason. E.g. the powersupply has it’s door open, the safety conditions are not satisfactory to allow the device to operate

FAULT and DISABLE are related to HARDWARE State ... not Device State. It means that even if the device is in FAULT; we want to see which ErrorCode it has. Both states require access to the Device Server to diagnose the reason for this hardware state ... so the software device SHOULD be Ready and accessible.

The code setting (wrongly) the device to NotReady is in tangodevice.py:

        elif taurus_tango_state not in (TaurusTangoDevState.FAULT,
                                      TaurusTangoDevState.DISABLE,
                                      TaurusTangoDevState.INIT):
            self._deviceState = TaurusDevState.Ready

The code preventing to access the device is in taurusdevicepanel.py:

        if state == TaurusDevState.Ready:
            msg = 'Connected to "%s"' % devname
            self.statusBar().showMessage(msg)
            self._ui.attrDW.setWindowTitle('Attributes - %s' % devname)
            self._ui.commandsDW.setWindowTitle('Commands - %s' % devname)
        else:
            # reset the model if the connection failed
            msg = 'Connection to "%s" failed (state = %s)' % (devname,
state.name)
            self.statusBar().showMessage(msg)
            self.info(msg)
            Qt.QMessageBox.warning(self, "Device unreachable", msg)
            self.setModel('')

**Comment by cpascual** [comment]
Hi @sergirubio, I think that you analysis about the inconsistency is correct, but IMHO the problem is not the tango->taurus state mapping, but in the handling of states in `TaurusDevPanel`

In other words, I think that it is reasonable to map Tango's `FAULT`, `DISABLE` and `INIT` to Taurus' `NotReady`... but then instead of `TaurusDevPanel` using the condition `if state == TaurusDevState.Ready`, we could actually attempt to connect with the device.

What do you think?

Apart from that, in your comment, you mention "some GUIs" as being affected but later on just mention code affecting `TaurusDevPanel`. Are any other Taurus widgets/GUIs which you identified as being affected by a similar issue?
