### ISSUE TITLE
Spock window in TaurusGui

### ISSUE THREAD

**Issue by stanislaw55** [taurus-org/taurus#900]
<This question is both related to Sardana and Taurus but I decided to ask here, since it's more related to Taurus than Sardana IMO.>

Hello Taurus community,
I'm wondering what is the best way to embed Spock terminal window in Taurus GUI application? Shall I use `silx`, as mentioned in `TaurusGui.createConsole` method (I think this console can be used to launch customized IPython profile like Spock but I'm not sure)? Or is there better way?

**Comment by cpascual** [comment]
This is something which I am also interested in knowing (and probably many other people too)

Long time ago we have done it with a very ugly hack embedding an Xterm with Qt, but it was awful and never quite worked well. And since I think the only workaround that I've seen is to use an [external application launcher](http://taurus-scada.org/users/ui/taurusgui.html#external-application-launchers) from a TaurusGUI to launch system consoles.

As I said, I am very interested in knowing if your approach works.

**Comment by stanislaw55** [comment]
Thank you @cpascual for your answer.
After a little bit of struggling with that I decided to just use TaurusMacroExecutor since it provides some sort of Spock console. 

When I've been searching sardana docs, what struck me is that there had to be some widget in some point in time (or maybe I'm wrong). Precisely, [this](https://sardana-controls.org/_images/gallery02.png) image shows something interesting but I'm not sure if this is widget or just a console. Maybe someone from Taurus community knows something about this, or @reszelaz maybe?

**Comment by reszelaz** [comment]
> Precisely, this image shows something interesting but I'm not sure if this is widget or just a console.

Maybe it is the qtconse + spock?

In https://github.com/sardana-org/sardana/issues/1063#issue-412518532 @lorcat mentions that it was working at some point. Personally I have never used it. I will poll people on today's [follow-up meeting](https://sourceforge.net/p/sardana/mailman/message/36635923/) if someone knows it.

**Comment by stanislaw55** [comment]
Thanks @reszelaz 
I'm looking forward to hear any news about that from Sardana community

**Comment by teresanunez** [comment]
Hi, at one of the DESY beamlines spock is used with the qtconsole.I am trying to get some information
from them and report it in the sardana follow-up meeting today.

**Comment by teresanunez** [comment]
Hi, at one of the DESY beamlines spock is used with the qtconsole.I am trying to get some information
from them and report it in the sardana follow-up meeting today.

**Comment by stanislaw55** [comment]
QtConsole + Spock would be wonderful. Combined with `silx`, should be easy to embed such widget

**Comment by teresanunez** [comment]
I copy here the information from Tim Schoof (member of the DESY control group) about the use of 
Spock with qtconsole at the Petra beamlines:

----------------------------
the standard qtconsole works on my Debian 9 PC:

schooft@haso232s:~/git/qtspock$ ipython qtconsole
[TerminalIPythonApp] WARNING | Subcommand `ipython qtconsole` is deprecated and will be removed in future versions.
[TerminalIPythonApp] WARNING | You likely want to use `jupyter qtconsole` in the future

Unfortunately, it does not support a --profile flag to load a spock profile, but I found two workarounds:

1. Start a detached ipython kernel:

    ipython kernel --profile spockdoor

    It will print something like:

    To connect another client to this kernel, use:
    --existing kernel-8921.json

    You can then connect to this kernel via:

    ipython qtconsole --existing kernel-8921.json

2. I wrote a small script that starts a kernel with --profile spockdoor and a connected qtconsole directly:

    https://github.com/DESY-P02-1/qtspock

    It also shows how to send commands to the kernel fromother widgets, in this case a QLineEdit.

I tried to understand the spock code (https://github.com/sardana-org/sardana/blob/develop/src/sardana/spock/ipython_01_00/genutils.py) without success. Therefore, I don't know what is missing when only loading the spockdoor profile. Until now, I found two things that are not working:

1. The spock prompt is missing

2. There are a lot of warning that are normally suppressed and logged by the Taurus logger (I guess)
----------------------------------

I hope this is useful for you.

**Comment by stanislaw55** [comment]
Thank you thousand, @teresanunez 
I'll try to use in meantime and give feedback about the result

**Comment by cpascual** [comment]
I created an issue in qtspock proposing to merge it into sardana: https://github.com/DESY-P02-1/qtspock/issues/1

**Comment by stanislaw55** [comment]
I've played with qtspock and it works as expected

**Comment by cpascual** [comment]
The work is under way in sardana (https://github.com/sardana-org/sardana/pull/1109) , so I am closing this issue.
