### ISSUE TITLE
Model names as settings in TaurusGui

### ISSUE THREAD

**Issue by stanislaw55** [taurus-org/taurus#904]
Hello Taurus community

This question is more about good practises and conventions than technical details. 

After playing a bit with `ini` setting files generated by `TaurusGui`, I realized that the do not save widgets' models (or maybe I'm doing something wrong. I've been creating panel of standard Taurus widgets like Label or Trend with keyword argument `registerconfig` set to True). However, when playing with TaurusTrend only (the old `qwt` based one, haven't tested `taurus_pyqtgraph` yet), settings saved in `pck` file have models inside (but I'm not very familiar with Taurus settings system). Hence following questions:

Is saving models in setting files by TaurusGui possible? If not, what considerations were made to make it this way? If yes, how then? Why `pck` settings file behave differently? 
In general, is it good idea to store model names in Taurus `ini` setting file (should be possible via `registerConfigProperty`)? Or one should stick to using model names from some other configuration file (i. e. JSON, YAML). 

Personally, I load models from extra JSON file manually, but saving and loading it automatically from somewhere else by Taurus is tempting. But I'm not sure is it good idea or not.

**Comment by cpascual** [comment]
> Is saving models in setting files by TaurusGui possible? 

Yes 

> If yes, how then? 

All taurus widgets (actually the base class `TaurusBaseComponent `) have the [`modelInConfig` property](http://taurus-scada.org/devel/api/taurus/qt/qtgui/base/_TaurusBaseComponent.html?highlight=modelinconfig#taurus.qt.qtgui.base.TaurusBaseComponent.setModelInConfig) which can be set to True to allow model to be stored in the taurus settings

Most widgets have this set to False by default, but you can set it to True (with `.setModeInConfig(True)` on a specific instance or even make a widget class where it is True by default.

> Why pck settings file behave differently?

They don't. It is not a matter of pck vs init file. It is a difference between using the stand-alone application launcher or the widget: some **application launchers** such as `taurusform` or `taurustrend` explicitly set modelInConfig to True for that specific application (while this is not the case in the `TaurusForm` or `TaurusTrend` **widgets** by default)

> In general, is it good idea to store model names in Taurus ini setting file (should be possible via registerConfigProperty)? Or one should stick to using model names from some other configuration file (i. e. JSON, YAML).

It depends a lot on the application. That is why we have the modelInConfig property. 

> Personally, I load models from extra JSON file manually, but saving and loading it automatically from somewhere else by Taurus is tempting. But I'm not sure is it good idea or not.

I think this is in general a very good practice if the models are part of the application itself. Keep in mind that the taurus settings are not the right place for storing permanent "core" application data. They are stored in a user dir, and are not guaranteed to be portable across machines or even across versions of Taurus or of other application dependencies versions (e.g.  Qt). In other words: the taurus settings (either in .ini or in .pck files) offer a limited persistence for **non-critical**, **user-specific**, **machine-specific** customizations (e.g. appearance), but any permanent application logic should not depend on them.

So, only if the persistence of the models in your specific case falls into the categories above (non-critical, user-specific, machine-specific), you should store them in the settings

**Comment by stanislaw55** [comment]
Thank you, @cpascual  for comprehensive answer.  `modelInConfig` look very nice and I'll try to investigate it a little further.

Thanks for clarification about configuration. About model names being persistent and part of application, I've been thinking about `factorySettingsFileName` argument to [`loadSettings`](http://taurus-scada.org/devel/api/taurus/qt/qtgui/container/_TaurusMainWindow.html?highlight=loadsettings#taurus.qt.qtgui.container.TaurusMainWindow.loadSettings) method. It could provide sane default models. However, it not as readable as JSON and in case of changing model names it can be pretty nasty. 

Anyway, thanks for answer and have a nice weekend!
