### ISSUE TITLE
ImportError: No module named curvesAppearanceChooserDlg (when using old .pck or .ini files from v<4.5)

### ISSUE THREAD

**Issue by izadworny** [taurus-org/taurus#909]
After upgrading Taurus from 4.1.1 to 4.5.1 it is not possible to load "old" config file in taurustrend.

```
taurustrend --config=m1y.pck
MainThread     INFO     2019-05-02 17:31:27,696 TaurusRootLogger: Using PyQt4 (v4.10.1 , with Qt 4.8.5)
MainThread     INFO     2019-05-02 17:31:27,775 taurus.qt.qtgui.icon.icon: Setting Tango icon theme (from /usr/lib/python2.7/site-packages/taurus/qt/qtgui/icon/)
MainThread     WARNING  2019-05-02 17:31:27,779 TaurusRootLogger: /usr/lib/python2.7/site-packages/taurus/qt/qtgui/qwt5/qwtdialog.py:35: DeprecationWarning: taurus.external.qt.Qwt5 is deprecated since 4.5
  from taurus.external.qt import Qt, Qwt5

Traceback (most recent call last):
  File "/usr/bin/taurustrend", line 10, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/site-packages/taurus/qt/qtgui/qwt5/taurustrend.py", line 1931, in main
    w.loadConfig(options.config_file)
  File "/usr/lib/python2.7/site-packages/taurus/qt/qtgui/qwt5/taurusplot.py", line 2539, in loadConfig
    configdict = pickle.load(ifile)
  File "/usr/lib64/python2.7/pickle.py", line 1378, in load
    return Unpickler(file).load()
  File "/usr/lib64/python2.7/pickle.py", line 858, in load
    dispatch[key](self)
  File "/usr/lib64/python2.7/pickle.py", line 1090, in load_global
    klass = self.find_class(module, name)
  File "/usr/lib64/python2.7/pickle.py", line 1124, in find_class
    __import__(module)
ImportError: No module named curvesAppearanceChooserDlg
```

**Comment by cpascual** [comment]
Hi,
This is not too surprising. The pickle files are not guaranteed to work across versions (because they are dependent on internal implementation details).

Still, we may try to fix this precise error. Could you please attach the pck file to facilitate the debugging?

**Comment by cpascual** [comment]
I found the problem at ALBA, and as a workaround you can simply edit the file and replace all occurrences of `taurus.qt.qtgui.plot.` by `taurus.qt.qtgui.qwt5.`

**The same recipe can be applied to taurusplot `.pck` files and to TaurusGui's `.ini` files**

**Tip:**, on GNU/linux you can do the replacements with the following command for a file called `foo.pck`:

```console
sed -i'-orig' 's/taurus\.qt\.qtgui\.plot\./taurus.qt.qtgui.qwt5./' foo.pck
```

Or, if you want to replace many `.pck` files in the current dir and subdirs:

```console
find . -type f -name '*.pck' | xargs sed -i'-orig' 's/taurus\.qt\.qtgui\.plot\./taurus.qt.qtgui.qwt5./'
```

Or, for fixing all `.ini` files in the `.config` dir:

```console
find ~/.config/ -type f -name '*.ini' | xargs sed -i'-orig' 's/taurus\.qt\.qtgui\.plot\./taurus.qt.qtgui.qwt5./'
```

**Note: this makes sense only if you continue using the qwt5-based plots/trends (only available for python2 + Qt4)**

**Comment by cpascual** [comment]
Since there is an easy workaround and this bug only affects outdated versions, I am closing it as "won't-fix"

**Comment by cpascual** [comment]
On a second
