### ISSUE TITLE
Modular loadConfiguration method in TaurusGui

### ISSUE THREAD

**Issue by stanislaw55** [taurus-org/taurus#918]
Hello Taurus Community,

Right now, `TaurusGui.loadConfiguration` method is quite monolithic. Different elements are loaded in one go. It could be split into different methods (maybe private ones?). Thus would allow more flexibility with managing configuration options and adding new ones.
Another benefit is that it would be easier to get Sardana stuff from `TaurusGui`. Having Sardana options in different method(s) would allow to easily move them to Sardana version of TaurusGui (no need for `MacroBroker`, just inherit from `TaurusGui` and add new behaviour).

**Comment by cpascual** [comment]
I agree, this has been on the TODO list for a long time. 

A sligtly related issue that may also benefit from this is #62 

Is anyone up for the challenge? 
@stanislaw55 ?

**Comment by stanislaw55** [comment]
Hi @cpascual 
actually, I think I can do it. Shouldn't be too hard to do this.
