### ISSUE TITLE
update of Experiment Config after programmatic changes

### ISSUE THREAD

**Issue by kklmn** [taurus-org/taurus#930]
Hi!

We 
1) change the storage path from an external application for each user and 
2) select a measurement group (we use several) from a script.

We do it through environ vars:
`self.setEnv('ActiveMntGrp', bla)`

These changes are not reflected in Taurus but we certainly want it. What would be a proper solution? Enabling polling? Invoking a widget update method? Using a set method of the widget, not `setEnv`?

Please advise. Thank you!

**Comment by reszelaz** [comment]
Thanks for the report @kklmn! Do you mean that the expconf widget is not updated with the changes? This was fixed in sardana 2.6.0.

**Comment by kklmn** [comment]
Yes, I mean the expconf widget, please see the title :)
We have 2.5.

BTW, to tell the version is not straightforward. Please include `__version__` to Sardana. Also in Taurus/Help/About an info about Sardana would make sense. 

Ok, thanks @reszelaz! I'll ask our Controls for the updated version.
