### ISSUE TITLE
Drag & drop in TaurusForm

### ISSUE THREAD

**Issue by stanislaw55** [taurus-org/taurus#937]
Hi,
Is it possible to change order of elements in TaurusForm just by performing drag & drop operation?
I know it is possible by right click -> Modify contents and then changing order by using up and down arrows. 
When I tried to drag&drop one element of form, it just got multiplied, not moved. Tested with Taurus 4.5.1

**Comment by cmft** [comment]
Hi @stanislaw55 ,
It is not possible. As you said the order only can be modified via `right click -> Modify contents`

**Comment by stanislaw55** [comment]
Okay, thanks for quick answer!
