### ISSUE TITLE
resuse sardana poolmotor interface for own tango motors

### ISSUE THREAD

**Issue by dschick** [taurus-org/taurus#942]
Hej,

I like to build a GUI for a bunch of TANGO motors and I pretty much like the way how motors are displayed with the Sardana PoolMotor widget.

Is there a simple way to resuse that code to display any TANGO motor with according mapping to the attributes and commands?
Maybe some has done something like this already?

Best

Daniel

**Comment by teresanunez** [comment]
Hi Daniel,
                 have you tried modifying the T_FORM_CUSTOM_WIDGET_MAP in the file
tauruscustomsettings.py?.
By default it is:

T_FORM_CUSTOM_WIDGET_MAP = \
    {'SimuMotor': ('sardana.taurus.qt.qtgui.extra_pool.PoolMotorTV', (), {}),
     'Motor': ('sardana.taurus.qt.qtgui.extra_pool.PoolMotorTV', (), {}),
     'PseudoMotor': ('sardana.taurus.qt.qtgui.extra_pool.PoolMotorTV', (), {}),
     'PseudoCounter': ('sardana.taurus.qt.qtgui.extra_pool.PoolChannelTV', (), {}),
     'CTExpChannel': ('sardana.taurus.qt.qtgui.extra_pool.PoolChannelTV', (), {}),
     'ZeroDExpChannel': ('sardana.taurus.qt.qtgui.extra_pool.PoolChannelTV', (), {}),
     'OneDExpChannel': ('sardana.taurus.qt.qtgui.extra_pool.PoolChannelTV', (), {}),
     'TwoDExpChannel': ('sardana.taurus.qt.qtgui.extra_pool.PoolChannelTV', (), {}),
     'IORegister': ('sardana.taurus.qt.qtgui.extra_pool.PoolIORegisterTV', (), {})
     }

I think you could add the class of your motors and map it to the PoolMotorTV, like the class Motor is.
I did it some years ago for my motors and at that point it worked.

                            Regards,
                                             Teresa

**Comment by teresanunez** [comment]
Well, of course, it will only match the attributes with the same name ... in our case the important
attributes were called like the ones in the Pool.

**Comment by dschick** [comment]
thanks a lot @teresanunez ,

maybe to try another route: are there some default taurus templates available to build a decent motor panel for Tango Motors with similar features as the PoolMotorTV?

**Comment by teresanunez** [comment]
Hi @dschick, I think the best would be to have a look at the code of the PoolMotorTV itself:

src/sardana/taurus/qt/qtgui/extra_pool/poolmotor.py

You can take as an example for creating your own one.

**Comment by cpascual** [comment]
No comments in many weeks, so I assume this can be closed now. @dschick , feel free to reopen if there is something else
