### ISSUE TITLE
Jul19 manual release tests: win10 py3qt5

### ISSUE THREAD

**Issue by mrosanes** [taurus-org/taurus#959]
This issue is created for reporting the results of the manual tests for Jul19 release on windows 10 with python3 and qt5. 

Using a clean windows10 machine (provisioned with vagrant: taurus-vagrant). Using Conda environment py3qt5 (conda activate py3qt5), from inside the vagrant VM.

Using tar.gz from appveyor at commit 62bdfdb59be (from develop branch).

--

Note: only some tests were performed. Not tested qwt5 related checks (since it is not available for py3)

Note2: used TANGO_HOST controls05, because using controls01 (Tango7) problems with API_EventTimeout appeared: maybe to be changed in taurus-vagrant Readme. (Even disabling firewall, I got the API_EventTimeouts, when using controls01).

**Comment by mrosanes** [comment]
### Installation

For tips on how to prepare an environment for installation, see

- [x] Install Taurus from the an artifact of Appveyor (tgz or msi): `pip install <tarball_artifact_URL>`
- [ ] Install taurus-pyqtgraph from the master branch of its repo: 
      `pip install https://github.com/taurus-org/taurus_pyqtgraph/archive/master.zip`.
- [x] Check installed version of taurus: `taurus --version`
- [ ] Check installed version of taurus_pyqtgraph: `taurus tpg --version`

### taurus demo

- [x] Execute `taurus demo`
- [x] Test all of the buttons of the taurus demo. All demos should launch correctly and without raising exceptions
- [ ] For TaurusLabel, check foreground role, the background role, the prefix, the suffix, the formatter, etc.
- [ ] For TaurusLabel, in order to test the background role=value, you can use the following attribute: `eval:["FAULT","ON","OFF","ALARM"][randint(4)]`
- [ ] For TaurusLabel, use a model with fragment (e.g., `sys/tg_test/1/ampli#rvalue.magnitude`, `eval:Q('1mm')#rvalue.unit"`, `eval:10*arange(9)#rvalue[3:4]`)
- [ ] For LCD: Test the foreground roles and the background role
- [ ] For Led: Test the colors, ON color, Off color. (hint: you can use `eval:False` as a model for testing)

**Comment by mrosanes** [comment]
### taurus guiqwt image

- [x] Execute `taurus guiqwt image --demo`
- [x] try to resize the image and pan it using the mouse.
- [x] check the cross section tools, the color maps, etc.
**Cross sections and ROIs can be added but not removed, the image becomes full of crosses if adding more and more: maybe only one cross (or ROI) should be kept.**
- [x] replace the image using the "Change Taurus Model" button (choose , eg, sys/tg_test/1/double_image_ro)

**Comment by mrosanes** [comment]
### taurus guiqwt trend2d

- [x] Execute: `taurus --polling-period 333 guiqwt trend2d --demo`
- [x] Execute: `taurus --polling-period 333 guiqwt trend2d -xt --demo`  **(known to fail in 4.1.0)**
**TypeError: QwtScaleDiv() takes 0, 2, 3 or 5 argument(s) (4 given)**
- [x] Execute: `taurus --polling-period 333 guiqwt trend2d -xe --demo`
- [x] Test auto-scroll and auto-scale tools (from context menu)
- [x] Test Save & restore config (change axes range, zoom, tool status colormap etc & check that everything is restored)
**Config cannot be saved; only an image .png can be saved**

**Comment by mrosanes** [comment]
### taurus designer
- [x] Execute `taurus designer`. Check that the taurus widgets are present in the catalog
**taurus widgets are not present in taurus designer**
- [x] Create an empty widget and drag various taurus widgets to it (they should be correctly dropped)

**Comment by mrosanes** [comment]
### taurus device
- [x] Execute: `taurus device sys/tg_test/1`
**On anaconda prompt this bug is reported:**
https://gist.github.com/mrosanes/4e0684e67710a2b811fd6c641280b0a1
- [x] Check that it opens correctly and that the attrs and commands are populated
**The images and tables opened with the buttons cannot be closed (with the cross)**
- [x] Execute SwitchStates command (see that the state label changes to FAULT and its color to red) and then execute the Init command and the label returns to RUNNING (blue)
**It works, but a lot of API_EventTimeout appear**

**Comment by mrosanes** [comment]
### taurus panel
- [x] Execute: `taurus panel`
- [x] Navigate in the tree and select the TangoTest device (the attr an command panels should be populated)
**The panel is populated, but there is a Pop up appearing of Event channel not responding anymore** 
- [x] Execute SwitchStates command to put it in FAULT, close the GUI and reopen it. Repeat previous point again.

**Comment by mrosanes** [comment]
### taurus config
- [x] Open an ini file with taurus config and check that it is loaded correctly.
**Popup: "No module named 'PyQt4", when trying to 'taurus config tgconf_macrogui.ini', from C:\Miniconda\envs\py3qt5\Lib\site-packages\taurus\qt\qtgui\taurusgui\conf\tgconf_macrogui**

**Comment by mrosanes** [comment]
### taurus icons catalog
- [x] Launch `taurus icons`. Several tabs with an array of icons [should be displayed](http://taurus-scada.org/en/latest/devel/icon_guide.html#taurus-icon-catalog)
- [x] Check that tooltips give info on each icon
- [x] Click on some icons and check that they give a bigger view of the icon and more info.

**Comment by mrosanes** [comment]
### taurus form
(basically try all features described in the [user's guide](http://taurus-scada.org/users/ui/index.html)

- [x] Launch `taurus form sys/tg_test/1/short_scalar`
**Activating polling: API_EventTimeout;
ERROR: poll_reply error**
- [ ] go to label context menu, change the configuration and set range to (-1000, 1000), alarm to (-500, 500) and unit to `mm`. Close the form and relaunch. The new units should be used. Change the the write value and check that the orange color is used when in warning values, and that the write widget does not allow to write values out of range.
- [ ] Test to drag and drop of this attribute onto the same form many times (4 times)
      (If it crashes, you are seeing bug #96)
- [ ] Open "Modify Contents" and add sys/tg_test/1 and all of its attributes. They should all show ok
- [ ] Test the compact mode  (switch to compact, noncompact; edit when in compact mode, ...) for a single
      value (from the context menu of a value label)
- [ ] Test compact mode for all values (from the context menu of the whole form)
- [ ] Test changing labels
- [ ] Test changing the formatter for a single value (from the context menu of a value label) (use, e.g. `>>{}<<`). Do this in compact and non compact modes.
- [ ] Test changing the formatter for all values (from the context menu of the whole form)
- [ ] Test re-order of values with "Modify contents"
- [ ] Test the different "show" buttons (tables, images, spectra)
- [ ] Change the write widget of double_scalar by a TaurusWheelEdit
- [ ] Change other read and write widgets
- [ ] After the previous changes, you should have a quite "custom" form. Use "Save current Settings" and save 
      to "tf.pck". Close the form and reopen it with `taurus form --config tf.pck`
- [ ] ... other features from [user's guide](http://taurus-scada.org/users/ui/index.html)

**Comment by mrosanes** [comment]
### taurus gui
(basically try all features described in the [user's guide](http://taurus-scada.org/users/ui/index.html)

- [x] Launch `taurus gui example01`
** - Nexus Browser not present**
** - AttributeError: 'DevFailed' object has no attribute 'rvalue'**
- [x] Test (un)lock view
Locked view allows me to move panels around: put them inside the main GUI and outside again; and also move them around the GUI. Then, if I unlock and I lock again, the GUI this time is well locked. 
- [ ] Create a new panel (a TaurusForm) and drag and drop several models from other forms
- [ ] Move panels around (with view unlocked!) and hide ("close") and re-show them
- [ ] Test saving and restoring perspectives
- [ ] Test drag&drop from a form to a trend
- [ ] Test clicking on "example01 synoptic" elements and check that the panels raised
- [ ] Test that selecting a panel changes the selection on "example01 synoptic"
- [ ] Test the actions in the menus
- [ ] Create a new TaurusGui (call it `foogui`) with `taurus newgui` (follow the wizard)
- [ ] Install `foogui` with pip (using a virtualenv may be a good idea)
- [ ] launch `foogui` using the script that has been installed
- [ ] ... other features from [user's guide](http://taurus-scada.org/users/ui/index.html)

**Comment by mrosanes** [comment]
### taurus tpg plot (needs taurus_pyqtgraph installed)
- [ ] Execute: `taurus tpg plot "eval:Q(rand(333),'mm')" sys/tg_test/1/wave`
- [ ] Check zoom / panning (drag with right / left button), and Use (A) button to auto-range
- [ ] Test inspector tool
- [ ] Move curves between axes by using the plot configuration option in context menu
- [ ] With curves in Y1 and Y2, test zooms and panning on separate axes (drag with right/left on the axis)
- [ ] Test plot configuration dialog
- [ ] Test changing curve titles
- [ ] Open the "Input data selection" dialog and add/remove/reorder/edit models. Try adding models both for X and Y
- [ ] NOT YET READY <s>Test Save & restore config (change curve properties, zoom, etc & check that everything is restored)</s>

**Comment by mrosanes** [comment]
### taurus tpg trend  (needs taurus_pyqtgraph installed)
- [ ] Execute: `taurus tpg trend "eval:Q(rand(),'mm')" sys/tg_test/1/ampli`
- [ ] Execute: `taurus tpg trend -xe "eval:Q(rand(),'mm')" sys/tg_test/1/ampli`
- [ ] Check zoom / panning (drag with right / left button), and Use (A) button to auto-range
- [ ] Test inspector tool
- [ ] Move curves between axes by using the plot configuration option in context menu
- [ ] With curves in Y1 and Y2, test zooms and panning on separate axes (drag with right/left on the axis)
- [ ] Test plot configuration dialog
- [ ] Test Forced reading tool
- [ ] Test autopanning tool
- [ ] Test autoscale x mode
- [ ] NOT YET READY <s> Test Save & restore config (change curve properties, zoom, etc & check that everything is restored)</s>

**Comment by mrosanes** [comment]
Output of automatic tests (taurus testsuite) for Win10 py3qt5: 
https://gist.github.com/mrosanes/5a4cafb3d5c4458ab1e54453f3714bda

**Comment by cpascual** [comment]
All relevant issues found have been already fixed and/or reported in the tracker, and none is considered release-critical. I am closing this test issue. Thanks @mrosanes for the tests!
