### ISSUE TITLE
Synoptics not shown in example01

### ISSUE THREAD

**Issue by cpascual** [taurus-org/taurus#963]
To reproduce (with taurus v 4.6.0a): 

launch `taurus gui example01`

The synoptics are not loaded.

Just guessing... Maybe it has to do with #918 ?

**Comment by stanislaw55** [comment]
> Just guessing... Maybe it has to do with #918 ?

Indeed, it was. I've provided fix in #964

**Comment by cpascual** [comment]
Thanks a lot @stanislaw55  for the quick response!
