### ISSUE TITLE
taurus widgets not present in 'taurus designer'

### ISSUE THREAD

**Issue by mrosanes** [taurus-org/taurus#968]
Taurus widgets not present in 'taurus designer' (tests of Jul19 release)

Found on:
win10 py3qt5
and on:
debian9 py2qt4
debian py3qt5

https://github.com/taurus-org/taurus/issues/959
https://github.com/taurus-org/taurus/issues/965

**Comment by cpascual** [comment]
Fixed in https://github.com/cpascual/taurus/commit/697d11975d8120b891d7624645b4a63c81dbb8bd
