### ISSUE TITLE
taurus gui example01 (win py3qt5): lock view

### ISSUE THREAD

**Issue by mrosanes** [taurus-org/taurus#971]
When performing manual tests for release Jul19, on win10 vm, with conda environment py3qt5:

Problem in lock view. 
When opening the gui: locked view is allowing to move panels around: put them inside the main GUI and outside again; and also move them around the GUI. Then, if we unlock and we lock again, the GUI now is well locked.

How to reproduce:
Execute:
taurus gui example01 

move panels around (out and in the main GUI); even if lock view is active, the panels can be moved and placed inside and outside the main Example01 GUI at our will.

**Comment by cpascual** [comment]
This is a duplicate of #574. Rejecting
