### ISSUE TITLE
Jul19 manual release tests: debian10 py3qt5

### ISSUE THREAD

**Issue by cpascual** [taurus-org/taurus#977]
This issue is created for reporting the results of the manual tests for [Jul19 release](https://github.com/taurus-org/taurus/pull/962) on debian10 (buster) with python3 and qt5.

The tests are done by @mrosanes and @cpascual

**Comment by cpascual** [comment]
### Installation

- [ ] Install Taurus from the an artifact of Appveyor (tgz or msi): `pip install <tarball_artifact_URL>`
> Using a debian buster taurus-test:buster pristine docker container deployed with:
> ```
> xhost +local:
> docker run -d --name=taurus-buster -h taurus-test -e DISPLAY=$DISPLAY -e QT_X11_NO_MITSHM=1 -v /tmp/.X11-unix:/tmp/.X11-unix cpascual/taurus-test:debian-buster
> docker exec -it taurus-buster bash
> ```
> and then installing from latest appveyor artifact from the release-Jan19 branch with:
> ```
> pip install https://ci.appveyor.com/api/buildjobs/g0ecp4g47ybyxvky/artifacts/dist%2Ftaurus-4.6.0a0.tar.gz
> ```

- [ ] Install taurus-pyqtgraph from the master branch of its repo: 

      `pip install https://github.com/taurus-org/taurus_pyqtgraph/archive/master.zip`.
- [ ] Check installed version of taurus: `taurus --version`
- [ ] Check installed version of taurus_pyqtgraph: `taurus tpg --version`

**Comment by mrosanes** [comment]
### taurus designer
- [ ] Execute `taurus designer`. Check that the taurus widgets are present in the catalog
- [ ] Create an empty widget and drag various taurus widgets to it (they should be correctly dropped)

**Comment by cpascual** [comment]
### taurus demo

- [ ] Execute `taurus demo`
- [ ] Test all of the buttons of the taurus demo. All demos should launch correctly and without raising exceptions
- [ ] For TaurusLabel, check foreground role, the background role, the prefix, the suffix, the formatter, etc.
- [ ] For TaurusLabel, in order to test the background role=value, you can use the following attribute: `eval:["FAULT","ON","OFF","ALARM"][randint(4)]`
- [ ] For TaurusLabel, use a model with fragment (e.g., `sys/tg_test/1/ampli#rvalue.magnitude`, `eval:Q('1mm')#rvalue.units`, `eval:10*arange(9)#rvalue[3:4]`)
- [ ] For LCD: Test the foreground roles and the background role
- [ ] For Led: Test the colors, ON color, Off color. (hint: you can use `eval:False` as a model for testing)

**Comment by mrosanes** [comment]
### taurus guiqwt image

- [ ] Execute `taurus guiqwt image --demo`
- [ ] try to resize the image and pan it using the mouse.
- [ ] check the cross section tools, the color maps, etc.
- [ ] replace the image using the "Change Taurus Model" button (choose , eg, sys/tg_test/1/double_image_ro)

**Comment by mrosanes** [comment]
### taurus guiqwt trend2d

- [ ] Execute: `taurus --polling-period 333 guiqwt trend2d --demo`
- [ ] Execute: `taurus --polling-period 333 guiqwt trend2d -xt --demo`  **(known to fail in 4.1.0)**
- [ ] Execute: `taurus --polling-period 333 guiqwt trend2d -xe --demo`
- [ ] Test auto-scroll and auto-scale tools (from context menu)

**Comment by mrosanes** [comment]
### taurus device
- [ ] Execute: `taurus device sys/tg_test/1`
- [ ] Check that it opens correctly and that the attrs and commands are populated
- [ ] Execute SwitchStates command (see that the state label changes to FAULT and its color to red)
      and then execute the Init command and the label returns to RUNNING (blue)

**Comment by cpascual** [comment]
### taurus panel
- [ ] Execute: `taurus panel`
- [ ] Navigate in the tree and select the TangoTest device (the attr an command panels should be populated)
- [ ] Execute SwitchStates command to put it in FAULT, close the GUI and reopen it. Repeat previous point again.

**Comment by cpascual** [comment]
### taurus form
(basically try all features described in the [user's guide](http://taurus-scada.org/users/ui/index.html)

- [ ] Launch `taurus form sys/tg_test/1/short_scalar`
- [ ] go to label context menu, change the configuration and set range to (-1000, 1000), alarm to (-500, 500) and unit to `mm`. Close the form and relaunch. The new units should be used. Change the the write value and check that the orange color is used when in warning values, and that the write widget does not allow to write values out of range.
- [ ] Test to drag and drop of this attribute onto the same form many times (4 times)
      (If it crashes, you are seeing bug #96)
- [ ] Open "Modify Contents" and add sys/tg_test/1 and all of its attributes. They should all show ok
- [ ] Test the compact mode  (switch to compact, noncompact; edit when in compact mode, ...) for a single
      value (from the context menu of a value label)
- [ ] Test compact mode for all values (from the context menu of the whole form)
- [ ] Test changing labels
- [ ] Test changing the formatter for a single value (from the context menu of a value label) (use, e.g. `>>{}<<`). Do this in compact and non compact modes.
- [ ] Test changing the formatter for all values (from the context menu of the whole form)
- [ ] Test re-order of values with "Modify contents"
- [ ] Test the different "show" buttons (tables, images, spectra)
- [ ] Change the write widget of double_scalar by a TaurusWheelEdit
- [ ] Change other read and write widgets
- [ ] After the previous changes, you should have a quite "custom" form. Use "Save current Settings" and save 
      to "tf.pck". Close the form and reopen it with `taurus form --config tf.pck`
- [ ] ... other features from [user's guide](http://taurus-scada.org/users/ui/index.html)

**Comment by mrosanes** [comment]
### taurus icons catalog
- [ ] Launch `taurus icons`. Several tabs with an array of icons [should be displayed](http://taurus-scada.org/devel/icon_guide.html#taurus-icon-catalog)
- [ ] Check that tooltips give info on each icon
- [ ] Click on some icons and check that they give a bigger view of the icon and more info.

**Comment by cpascual** [comment]
# Generic issues: some generic issues detected in one or more tests

- Missing console logs. Console output is a way less verbose than expected (this may be related with the taurus-test buster container?)
- Missing icons. Many icons are not displayed. For example all in Model chooser except the collapse/expand ones

**Comment by mrosanes** [comment]
### taurus gui
(basically try all features described in the [user's guide](http://taurus-scada.org/users/ui/index.html)

- [ ] Launch `taurus gui example01`
- [ ] Test (un)lock view
- [ ] Create a new panel (a TaurusForm) and drag and drop several models from other forms
- [ ] Move panels around (with view unlocked!) and hide ("close") and re-show them
- [ ] Test saving and restoring perspectives
- [ ] Test drag&drop from a form to a trend (won't work if using the tpg.TaurusTrend, until [this](https://github.com/taurus-org/taurus_pyqtgraph/issues/25)) is fixed
- [ ] Test drag&drop from a form to a plot
- [ ] Test clicking on "example01 synoptic" elements and check that the panels raised
- [ ] Test that selecting a panel changes the selection on "example01 synoptic"
- [ ] Test the actions in the menus
- [ ] Create a new TaurusGui (call it `foogui`) with `taurus newgui` (follow the wizard)
- [ ] Install `foogui` with pip (using a virtualenv may be a good idea)
- [ ] launch `foogui` using the script that has been installed
- [ ] ... other features from [user's guide](http://taurus-scada.org/users/ui/index.html)

**Comment by mrosanes** [comment]
### taurus config
- [x] Open an ini file with taurus config and check that it is loaded correctly.
> BUG: ini file is totally empty if opening as: taurus config mygui.ini
> BUG: from inside 'taurus config' application, 'Open File', the tree of directories cannot be navigated and no ini file can be chosen to be opened.

**Comment by mrosanes** [comment]
### taurus tpg plot (needs taurus_pyqtgraph installed)
- [ ] Execute: `taurus tpg plot "eval:Q(rand(333),'mm')" sys/tg_test/1/wave`
- [ ] Check zoom / panning (drag with right / left button), and Use (A) button to auto-range
- [ ] Test inspector tool
- [ ] Move curves between axes by using the plot configuration option in context menu
- [ ] With curves in Y1 and Y2, test zooms and panning on separate axes (drag with right/left on the axis)
- [ ] Test plot configuration dialog
- [ ] Test changing curve titles
- [ ] Open the "Input data selection" dialog and add/remove/reorder/edit models. Try adding models both for X and Y
- [ ] NOT YET READY <s>Test Save & restore config (change curve properties, zoom, etc & check that everything is restored)</s>

**Comment by mrosanes** [comment]
### taurus tpg trend  (needs taurus_pyqtgraph installed)
- [ ] Execute: `taurus tpg trend "eval:Q(rand(),'mm')" sys/tg_test/1/ampli`
- [ ] Execute: `taurus tpg trend -xe "eval:Q(rand(),'mm')" sys/tg_test/1/ampli`
- [ ] Check zoom / panning (drag with right / left button), and Use (A) button to auto-range
- [ ] Test inspector tool
- [ ] Move curves between axes by using the plot configuration option in context menu
- [ ] With curves in Y1 and Y2, test zooms and panning on separate axes (drag with right/left on the axis)
- [ ] Test plot configuration dialog
- [ ] Test Forced reading tool
- [ ] Test autopanning tool
- [ ] Test autoscale x mode
- [ ] NOT YET READY <s> Test Save & restore config (change curve properties, zoom, etc & check that everything is restored)</s>

**Comment by cpascual** [comment]
All relevant issues found have been already reported in the tracker, and none is considered release-critical. I am closing this test issue. Thanks @mrosanes for the tests!
