### ISSUE TITLE
Taurus guiqwt trend2d failure

### ISSUE THREAD

**Issue by amilan** [taurus-org/taurus#979]
Running the following command:
```shell
taurus --polling-period 333 guiqwt trend2d -xt --demo
```
In CentOS7, using python 2.7 and pyqt4, gives the following error:

```shell
TypeError: QwtScaleDiv() takes 0, 2, 3 or 5 argument(s) (4 given)
```

**Comment by cpascual** [comment]
I am closing this as a duplicate of #505

**Comment by amilan** [comment]
Ups, sorry for the duplicated issue.
