### ISSUE TITLE
Jul19 manual (partial) release tests: debian9 py3qt5

### ISSUE THREAD

**Issue by cpascual** [taurus-org/taurus#983]
This issue is created for reporting the results of the manual tests for Jul19 release on debian9(stretch) with python3 and qt5.

The full checklist is not done. Only a few selected tests are done, to check issues found in other platforms.

The tests are done by  @cpascual and @mrosanes

**Comment by cpascual** [comment]
### Installation

> The installation is done on a pristine taurus-test:debian-stretch-py3qt5 container deployed with
> ```
> xhost +local:
> docker run -d --name=taurus-stretch -h taurus-test -e DISPLAY=$DISPLAY -e QT_X11_NO_MITSHM=1 -v /tmp/.X11-unix:/tmp/.X11-unix cpascual/taurus-test:debian-stretch-pyqt5
> docker exec -it taurus-stretch bash
> ```

- [x] Install Taurus from the an artifact of Appveyor (tgz or msi): `pip install <tarball_artifact_URL>`

> installing from latest appveyor artifact from the release-Jan19 branch with:
> ```
> pip3 install https://ci.appveyor.com/api/buildjobs/g0ecp4g47ybyxvky/artifacts/dist%2Ftaurus-4.6.0a0.tar.gz
> ```

- [x] Install taurus-pyqtgraph from the master branch of its repo: 
   `pip3 install https://github.com/taurus-org/taurus_pyqtgraph/archive/master.zip`

> PROBLEM: I ran into #984 , and I worked around it by manually editting the METADATA file

- [x] Install taurus-pyqtgraph from the master branch of its repo: 
   `pip3 install https://github.com/taurus-org/taurus_pyqtgraph/archive/master.zip`
- [x] Check installed version of taurus: `taurus --version`
> taurus, version 4.6.0-alpha
- [x] Check installed version of taurus_pyqtgraph: `taurus tpg --version`
> tpg, version 0.2.5a0 (with taurus 4.6.0a0)

**Comment by mrosanes** [comment]
### taurus designer
- [x] Execute `taurus designer`. Check that the taurus widgets are present in the catalog
- [x] Create an empty widget and drag various taurus widgets to it (they should be correctly dropped)

**Comment by mrosanes** [comment]
# Generic issues

Some generic issues detected in one or more tests

- A few errors are logged related to OpenGL (which vary from host machine to host machine). These are quite certainly related with running on docker.
```
libGL error: failed to open drm device: No such file or directory
libGL error: failed to load driver: i965
```

**Comment by mrosanes** [comment]
### taurus config
- [x] Open an ini file with taurus config and check that it is loaded correctly.

**Comment by mrosanes** [comment]
### taurus form
(basically try all features described in the [user's guide](http://taurus-scada.org/users/ui/index.html)

- [x] Launch `taurus form sys/tg_test/1/short_scalar`
- [x] go to label context menu, change the configuration and set range to (-1000, 1000), alarm to (-500, 500) and unit to `mm`. Close the form and relaunch. The new units should be used. Change the the write value and check that the orange color is used when in warning values, and that the write widget does not allow to write values out of range.
- [x] Test to drag and drop of this attribute onto the same form many times (5 times)
> bug #96: It crashes some of the times dragging/dropping (normally if dragging/dropping fast). Not 100% reproducible in debian9.

**Comment by mrosanes** [comment]
### taurus tpg plot (needs taurus_pyqtgraph installed)
- [x] Execute: `taurus tpg plot "eval:Q(rand(333),'mm')" sys/tg_test/1/wave`
- [x] Check zoom / panning (drag with right / left button), and Use (A) button to auto-range
- [x] Test inspector tool

**Comment by cpascual** [comment]
The critical bugs have been tested and passed.
