### ISSUE TITLE
Transient corba system exception

### ISSUE THREAD

**Issue by danyan90** [taurus-org/taurus#995]
when I invoke an example code 
```python
import sys
from taurus.external.qt import Qt
from taurus.qt.qtgui.application import TaurusApplication

app = TaurusApplication(sys.argv, cmd_line_parser=None,)
panel = Qt.QWidget()
layout = Qt.QHBoxLayout()
panel.setLayout(layout)
from taurus.qt.qtgui.display import TaurusLabel
w = TaurusLabel()
layout.addWidget(w)
w.model = 'sys/taurustest/1/position'

panel.show()
sys.exit(app.exec_())
```

I receive 
```console
MainThread     INFO     2019-08-30 18:11:11,116 TaurusRootLogger: Using PyQt5 (v5.9.2 with Qt 5.9.6 and Python 3.7.3)
MainThread     INFO     2019-08-30 18:11:18,500 taurus.qt.qtgui.icon.icon: Setting Tango icon theme (from C:\tango\Anaconda3\lib\site-packages\taurus\qt\qtgui\icon\)
MainThread     INFO     2019-08-30 18:11:24,655 TaurusRootLogger: Plugin "taurus_pyqtgraph" loaded as "taurus.qt.qtgui.tpg"
MainThread     WARNING  2019-08-30 18:11:43,464 sys/taurustest/1: Could not create HW object: TRANSIENT CORBA system exception: TRANSIENT_NoUsableProfile
```
and that 
<img width="126" alt="Снимок экрана 2019-08-30 в 18 15 43" src="https://user-images.githubusercontent.com/50834722/64031971-347ee900-cb52-11e9-8df5-0eb54c1d88b0.png">

**Comment by danyan90** [comment]
when I invoke an example code 
```python
import sys
from taurus.external.qt import Qt
from taurus.qt.qtgui.application import TaurusApplication

app = TaurusApplication(sys.argv, cmd_line_parser=None,)
panel = Qt.QWidget()
layout = Qt.QHBoxLayout()
panel.setLayout(layout)
from taurus.qt.qtgui.display import TaurusLabel
w = TaurusLabel()
layout.addWidget(w)
w.model = 'sys/taurustest/1/position'

panel.show()
sys.exit(app.exec_())
```

I receive 
```console
MainThread     INFO     2019-08-30 18:11:11,116 TaurusRootLogger: Using PyQt5 (v5.9.2 with Qt 5.9.6 and Python 3.7.3)
MainThread     INFO     2019-08-30 18:11:18,500 taurus.qt.qtgui.icon.icon: Setting Tango icon theme (from C:\tango\Anaconda3\lib\site-packages\taurus\qt\qtgui\icon\)
MainThread     INFO     2019-08-30 18:11:24,655 TaurusRootLogger: Plugin "taurus_pyqtgraph" loaded as "taurus.qt.qtgui.tpg"
MainThread     WARNING  2019-08-30 18:11:43,464 sys/taurustest/1: Could not create HW object: TRANSIENT CORBA system exception: TRANSIENT_NoUsableProfile
```
and that 
<img width="126" alt="Снимок экрана 2019-08-30 в 18 15 43" src="https://user-images.githubusercontent.com/50834722/64031971-347ee900-cb52-11e9-8df5-0eb54c1d88b0.png">

**Comment by cmft** [comment]
Hi @danyan90 ,
The example uses a TANGO model `'sys/taurustest/1/position'`. and the debug system is saying that ` Could not create HW object`  it is cause you do not have running the tango device server (DS).

See http://taurus-scada.org/devel/examples.html#setup

The launcher of this DS is in `/home/YOUR_USER/miniconda3/envs/test/lib/python3.6/site-packages/taurus/core/tango/test/res` and you have to create a instance in the tango system. See [tango doc](https://tango-controls.readthedocs.io/en/latest/tutorials-and-howtos/how-tos/how-to-start-device-server.html),  if you need more details to run the DS.

Carlos

**Comment by danyan90** [comment]
Hi Carlos
I had downloaded a DS file from [here](http://taurus-scada.org/devel/examples.html) 
and launched it :
```console
python PATH\TaurusTest taurustest
```
before that, I had created Device server in Jive of course (using tools/create server) 
And Astor shows, as I understand, that everything is OK, and DS running : 
<img width="345" alt="Снимок экрана 2019-09-02 в 15 52 41" src="https://user-images.githubusercontent.com/50834722/64116194-55397f80-cd9a-11e9-9b15-5a6be23983c0.png">

**Comment by cmft** [comment]
Forget this (I was confuse with the name)

> The launcher of this DS is in /home/YOUR_USER/miniconda3/envs/test/lib/python3.6/site-packages/taurus/core/tango/test/res and you have to create a instance in the tango system. See tango doc, if you need more details to run the DS.

Ok, you have the DS running, so the name must be another. In jive, check the device info, what is the name of your device? If it is not `sys/taurustest/1`  replace the device name in the example or recreate it.

`w.model = 'sys/taurustest/1/position'` by `YOUR_DEVICE_NAME/position`

![Screenshot_20190902_152258](https://user-images.githubusercontent.com/6168722/64117487-99765100-cd95-11e9-8e9b-e59d0ce8cd69.png)

**Comment by danyan90** [comment]
So, I made everything word by word from the instruction to Taurus examples, and I have the same device name as it should be. 

PS
 thats what I invoke and receive:
```console
(base) C:\Users\tango>python desktop\taurustest.py taurustest
In TaurusTestClass  constructor
In  sys/taurustest/1 ::init_device()
```

**Comment by cmft** [comment]
Hola @danyan90,
it is OK.  Reading the output again seems that device is unreachable.

Could you run this code and copy me the output?

```
import tango

print(tango.ApiUtil.get_env_var('TANGO_HOST'))
print(tango.Database())
d = tango.DeviceProxy('sys/taurustest/1')
d.status()
```

**Comment by danyan90** [comment]
```console
localhost:10000
Database(tango-MSU.edc.local, 10000)

Process finished with exit code 0

```

**Comment by cpascual** [comment]
I think that the last line of @cmft's snippet was meant to be: `print(d.status())`  (otherwise it has no output unless run in an interactive python)

**Comment by danyan90** [comment]
I thought so too, but I decided not to argue =)
added to previous post

**Comment by cpascual** [comment]
From the output in your snippet, the only thing that looks strange to me is that the output of `tango.Database()` does not match the the content of `TANGO_HOST`.

Try to set the `TANGO_HOST` env var to `tango-MSU.edc.local:10000`

And then try to access the `sys/taurustest/1/position` both with tango and taurus:

```python
import tango
import taurus

m = "sys/taurustest/1/position"
print("TANGO", tango.AttributeProxy(m).read().value)
print("TAURUS", taurus.Attribute(m).read().rvalue)
```

In my case I get:
```console
TANGO 50.0
TAURUS 50.0 mm
```

**Comment by danyan90** [comment]
```console
TANGO 50.0
MainThread     WARNING  2019-09-03 20:02:53,196 sys/taurustest/1: Could not create HW object: TRANSIENT CORBA system exception: TRANSIENT_NoUsableProfile
MainThread     WARNING  2019-09-03 20:02:53,768 sys/taurustest/1: Could not create HW object: TRANSIENT CORBA system exception: TRANSIENT_NoUsableProfile
Traceback (most recent call last):
  File "C:/tango/newproject1/1.py", line 6, in <module>
    print("TAURUS", taurus.Attribute(m).read().rvalue)
  File "C:\tango\Anaconda3\lib\site-packages\taurus\core\tango\tangoattribute.py", line 558, in read
    raise e
  File "C:\tango\Anaconda3\lib\site-packages\taurus\core\tango\tangoattribute.py", line 543, in read
    v = dev.read_attribute(self.getSimpleName())
  File "C:\tango\Anaconda3\lib\site-packages\taurus\core\tango\tangodevice.py", line 81, in __getattr__
    raise AttributeError("'%s' has no attribute '%s'" % (cls_name, name))
AttributeError: 'TangoDevice' has no attribute 'read_attribute'
```

**Comment by danyan90** [comment]
> Try to set the TANGO_HOST env var to tango-MSU.edc.local:10000
After that I can't connect to Tango DB
```console
Can't build connection to TANGO database server, exiting
```

**Comment by cpascual** [comment]
I may be wrong but I suspect that the issue is precisely with how the tango DB address is set.
It seems that pytango is using a different mechanism than taurus when discovering the address.

To try to debug it a little more, please run the following:

```
import taurus, tango, os

tr = os.environ.get("TANGO_ROOT", "")
print("TANGO_ROOT=", tr)
rc = os.path.join(tr, 'tangorc')
if os.path.exists(rc):
    print("{}=\n-------\n{}\n-------\n".format(rc, open(rc, "r").read()))
else:
    print('cannot find', rc)
    
print("TANGO_HOST=", os.environ.get('TANGO_HOST'))
print("tg apiutil host=",tango.ApiUtil.get_env_var('TANGO_HOST'))
print("taurus default auth=",taurus.Authority().getFullName())

```

**Comment by danyan90** [comment]
```console
TANGO_ROOT= C:\Program Files\tango
cannot find C:\Program Files\tango\tangorc
TANGO_HOST= localhost:10000
tg apiutil host= localhost:10000
taurus default auth= tango://tango-MSU.edc.local:10000
```

**Comment by cpascual** [comment]
We just fixed issue #998 that may be related with this.
Can you check if the issue is gone with the latest code in develop?
If not, please report again the results of the snippet in https://github.com/taurus-org/taurus/issues/995#issuecomment-527840955 when running with the latest develop version.

**Comment by danyan90** [comment]
Sorry, I'm a newbee, could you please explain: I should update taurus from pip or edit some codes by myself?

**Comment by cpascual** [comment]
Assuming that you originally installed taurus with pip, then just into the anaconda prompt that you use for launching taurus and do:
```
pip install --force-reinstall https://github.com/taurus-org/taurus/archive/develop.zip
```

**Comment by danyan90** [comment]
Oh! It really helped! 
<img width="123" alt="Снимок экрана 2019-09-05 в 20 56 52" src="https://user-images.githubusercontent.com/50834722/64366871-d05f9780-d01f-11e9-8b07-1a7918f60319.png">
but I have ten same errors:
```console
TimerLoop 1    WARNING  2019-09-05 20:54:31,385 TaurusPollingTimer[3000].Timer on _pollAttributes: loop function took more than loop interval (3.0s)
```
I think it's not so important
Thank you very much!
P.S.
I'm very glad to know, that it was a bug in Taurus, and not I am a fool 😂

**Comment by cpascual** [comment]
I am glad that it helped.
Thanks a lot for your patience and for reporting!

It is interesting because we have had the FQDN name conversion in taurus working for a few releases without finding problems in any system. And in just one week we simultaneously found two independent corner cases in which the FQDN conversion was messing things up...

At the very least this stresses the need of more coverage in our unit tests!
