### ISSUE TITLE
autoApply single element in taurusform

### ISSUE THREAD

**Issue by fscholz-desy** [taurus-org/taurus#996]
Hello,

I'm applying to single attributes in a taurusform the writeWidgetClass like this:

`
self.ui.taurusform_inter[4].writeWidgetClass = 'TaurusWheelEdit'
self.ui.taurusform_inter[5].writeWidgetClass = 'TaurusWheelEdit' 
`

Now my question, is it possible to apply the 'autoApply' property to one single Attribute in the taurusform? 
Somehow like this:

`self.ui.taurusForm_inter[4].writeWidgetClass.autoApply()`

I've tried different things but had no success.
Do you have any solution?

Thanks

**Comment by cpascual** [comment]
I think that what you are looking for want is the following:

```python
self.ui.taurusForm_inter[4].writeWidget().setAutoApply(True)
```

... or, using the property (which the `TaurusWheelEdit` has, but maybe not all other widgets have):
```python
self.ui.taurusForm_inter[4].writeWidget().autoApply =True

**Comment by fscholz-desy** [comment]
I tested both and it works!
Thanks!
