### ISSUE TITLE
taurusmodelchooser broken on tango/taurus fresh install

### ISSUE THREAD

**Issue by pierreH23** [taurus-org/taurus#997]
Hello !
learning Tango Controls, Taurus & friends is a long way ...
To prepare a real application I decided to reinstall from scratch starting with updated versions : python3, qt5 and from pip3 : pyqt5, taurus 4.6.1, pytango 9.3.1 (on mint 19.1).
But 'taurusmodelchooser' doesn't run anymore and crash when I select a model with : 
`TypeError: setData(self, str, Union[QByteArray, bytes, bytearray]): argument 2 has unexpected type 'str' at line 358` (taurusmodelchooser.py)

I inspected the source code and the  #886 issue ... at my competence level, I found a workaround : replace 
`md.setData(taurus.qt.qtcore.mimetypes.TAURUS_MODEL_LIST_MIME_TYPE, str("\r\n".join(models)))`
by
`md.setData(taurus.qt.qtcore.mimetypes.TAURUS_MODEL_LIST_MIME_TYPE, bytes("\r\n".join(models),encoding='utf8'))`
and
`taurus.qt.qtcore.mimetypes.TAURUS_MODEL_MIME_TYPE, str(models[0]))`
by
`md.setData(taurus.qt.qtcore.mimetypes.TAURUS_MODEL_MIME_TYPE, bytes(models[0],encoding='utf8'))`
Is it correct ?
Many thanks
Pierre Héricourt
CELIA/CNRS
Université Bordeaux / France

**Comment by cpascual** [comment]
Hi @pierreH23, thanks a lot for the report.
I think that you are right. This is another place similar to what we fixed in #886. Would you mind proposing a PR?

**Comment by pierreH23** [comment]
Hi Carlos,
sorry, it was a really dirty workaround, I didn't use git ... I have to read the documentation and learn how to pull requests. If it's not too late, I could try to learn how to this week !
Thanks
Pierre

**Comment by cpascual** [comment]
Do not worry!
IMHO, even for 1-person work it is a good idea to learn and use git, but for Free Software collaborations, it is a must! 
If you want to practice on the PR workflow using this issue, I reccomend to start by reading our [CONTRIBUTING.md] guidelines (and its links).

But if you cannot do it at this moment, don't worry, just say so and I'll propose the PR myself.

Cheers,

**Comment by cpascual** [comment]
Hi @pierreH23 , I found that this is blocking a demo we want to do, so I am going to propose the PR myself. Just saying so that you do not waste time duplicating.

**Comment by pierreH23** [comment]
Hi Carlos, I will pratice my 'git' on next bug ;) Many thanks. Pierre
